<?php
/**
 * Home Why Umoya widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/home_why.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Home_Why extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'home_why';
	}
}
