<?php
/**
 * Home Signature Journey widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/home_signature_journey.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Home_Signature_Journey extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'home_signature_journey';
	}
}
