<?php
/**
 * SJ Inclusions & Offers widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/sj_inclusions.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class SJ_Inclusions extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'sj_inclusions';
	}
}
