<?php
/**
 * Home Founder’s Circle widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/home_founders_circle.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Home_Founders_Circle extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'home_founders_circle';
	}
}
