<?php
/**
 * Groups Plan a Journey Form widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/fg_plan_form.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class FG_Plan_Form extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'fg_plan_form';
	}
}
