<?php
/**
 * SJ Inquiry Popup widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/sj_form_popup.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class SJ_Form_Popup extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'sj_form_popup';
	}
}
