<?php
/**
 * Privacy Policy Page widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/page_privacy.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Page_Privacy extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'page_privacy';
	}
}
