<?php
/**
 * SJ Journey Chapters widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/sj_chapters.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class SJ_Chapters extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'sj_chapters';
	}
}
