<?php
/**
 * About Our Mission widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/ab_mission.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class About_Mission extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'ab_mission';
	}
}
