<?php
/**
 * Home Inquiry Popup widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/home_form_popup.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Home_Form_Popup extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'home_form_popup';
	}
}
