<?php
/**
 * Site Navigation widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/site_nav.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Site_Nav extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'site_nav';
	}
}
