<?php
/**
 * P&T Design Your Journey Form widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/pt_design_form.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class PT_Design_Form extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'pt_design_form';
	}
}
