<?php
/**
 * P&T Hero widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/pt_hero.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class PT_Hero extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'pt_hero';
	}
}
