<?php
/**
 * Contact Enquiry Forms widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/ct_forms.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Contact_Forms extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'ct_forms';
	}
}
