<?php
/**
 * About Closing CTA widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/ab_cta.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class About_CTA extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'ab_cta';
	}
}
