<?php
/**
 * Home Film & Award widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/home_film_award.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Home_Film_Award extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'home_film_award';
	}
}
