<?php
/**
 * Groups Planning Steps widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/fg_how.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class FG_How extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'fg_how';
	}
}
