<?php
/**
 * FC Hero widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\Section_Widget,
 * driven by includes/sections/fc_hero.json.
 */

namespace Umoya_EW\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class FC_Hero extends \Umoya_EW\Section_Widget {

	protected function section_key() {
		return 'fc_hero';
	}
}
