/**
 * Emitters: turn a derived section into the files the plugin ships.
 *
 * Nothing here is clever. The template is the source markup with echo splices
 * already applied; this module only wraps it in a PHP header, wraps the
 * section's script so Elementor can (re-)initialise it, and writes the schema
 * the widget reads at runtime.
 */

/**
 * PHP discards the single newline that immediately follows a `?>`. Every echo
 * that sits at the end of a line would therefore silently swallow its own line
 * break, closing tags would ride up onto the previous line, and the rendered
 * markup would no longer match the source -- the exact class of quiet loss this
 * compiler exists to prevent.
 *
 * The fix moves that whitespace inside the PHP block, so `?>` is never adjacent
 * to a newline. It matches a `?>` that closes a completed statement or block
 * (`;` or `}`) and is followed by a line break -- shapes the compiler emits and
 * the section HTML never contains.
 */
export function guardPhpNewlines( markup ) {
	// The capture takes the WHOLE following run of line breaks and indentation.
	// Taking only the first line break leaves a second one immediately after
	// `?>` for PHP to eat, which silently swallows a blank line.
	return markup.replace( /([;}])\s*\?>((?:\r?\n[ \t]*)+)/g, ( match, terminator, whitespace ) => {
		return terminator + ' echo ' + phpDoubleQuoted( whitespace ) + '; ?>';
	} );
}

function phpDoubleQuoted( value ) {
	return '"' + value.replace( /\\/g, '\\\\' ).replace( /"/g, '\\"' ).replace( /\$/g, '\\$' ).replace( /\r/g, '\\r' ).replace( /\n/g, '\\n' ).replace( /\t/g, '\\t' ) + '"';
}

export function emitTemplate( section, templateMarkup ) {
	return [
		'<?php',
		'/**',
		' * ' + section.title + ' -- render template.',
		' *',
		' * GENERATED by tools/uew from ' + section.source + '. Do not edit by hand:',
		' * edit the section HTML and re-run `node tools/uew/build.mjs`.',
		' *',
		' * @var array $c Escaped scalar content values, keyed by control id.',
		' * @var array $r Repeater rows, each row an array of escaped values.',
		' * @var array $s Rebuilt inline style attributes, keyed by property-id list.',
		' */',
		'',
		"if ( ! defined( 'ABSPATH' ) ) {",
		'\texit;',
		'}',
		'?>',
	].join( '\n' ) + '\n' + templateMarkup;
}

/**
 * Wrap the section's own scripts so they run in three places that matter:
 * a normal front-end page load, an Elementor editor canvas (where widgets are
 * injected long after DOM ready), and a plain HTML paste with no Elementor at
 * all. The bodies themselves are copied through untouched.
 */
export function emitScript( section, scripts ) {
	const body = scripts.join( '\n\n' ).replace( /\n/g, '\n\t\t' );
	const rootSelector = section.root_selector;
	const requiresRoot = section.script_requires_root !== false;
	const portalIds = ( section.portals || [] ).map( ( portal ) => portal.selector.replace( /^#/, '' ) );

	// Only sections that move a dialog to <body> need the editor clean-up below.
	const retire = ! portalIds.length ? '' : `
	var PORTAL_IDS = ${ JSON.stringify( portalIds ) };

	/*
	 * In the editor every control change re-renders the widget, bringing a
	 * fresh copy of each dialog that moves itself to <body> -- while the
	 * previous copy is still there, with the previous run's listeners still
	 * attached. A trigger would then open both: the fresh one on top and a
	 * stale one underneath that reappears when the fresh one is closed.
	 *
	 * Each copy outside the widget being initialised is retired before the
	 * section script runs again: hidden for good, and without its id so the
	 * script's getElementById() finds the fresh one. On a published page there
	 * is only ever one copy, so this does nothing there.
	 */
	function uewRetireStalePortals( scopeElement ) {
		for ( var i = 0; i < PORTAL_IDS.length; i++ ) {
			var copies = document.querySelectorAll( '[id="' + PORTAL_IDS[ i ] + '"]' );
			if ( copies.length < 2 ) {
				continue;
			}
			for ( var j = 0; j < copies.length; j++ ) {
				if ( scopeElement.contains( copies[ j ] ) ) {
					continue;
				}
				copies[ j ].removeAttribute( 'id' );
				copies[ j ].setAttribute( 'data-uew-retired', '1' );
				copies[ j ].style.setProperty( 'display', 'none', 'important' );
			}
		}
	}
`;

	return `/**
 * ${ section.title } -- section behaviour.
 *
 * GENERATED by tools/uew from ${ section.source }. Do not edit by hand.
 *
 * The section's original script bodies are reproduced verbatim inside
 * uewRun(). What is added around them is the Elementor lifecycle: widgets are
 * injected into the editor canvas long after DOMContentLoaded, so a bare IIFE
 * would query an element that does not exist yet and the section would look
 * "broken" in the editor. Registering on frontend/element_ready fixes that, and
 * the data-uew-ready latch keeps a double call harmless.
 */
( function () {
	'use strict';

	var ROOT_SELECTOR = ${ JSON.stringify( rootSelector ) };
	var WIDGET_NAME = ${ JSON.stringify( section.name ) };
${ retire }
	function uewRun() {
${ '\t\t' + body }
	}

	function uewInit( scope ) {
		var context = scope && scope.length ? scope[ 0 ] : ( scope || document );
		var root = context.querySelector ? context.querySelector( ROOT_SELECTOR ) : null;

		if ( ! root && context !== document && context.matches && context.matches( ROOT_SELECTOR ) ) {
			root = context;
		}
		if ( ! root ) {
			root = document.querySelector( ROOT_SELECTOR );
		}
		if ( ! root${ requiresRoot ? '' : ' && false' } ) {
			return;
		}
		if ( root && root.getAttribute( 'data-uew-ready' ) === '1' ) {
			return;
		}
		if ( root ) {
			root.setAttribute( 'data-uew-ready', '1' );
		}
${ portalIds.length ? `
		if ( context !== document && context.contains ) {
			uewRetireStalePortals( context );
		}
` : '' }
		uewRun();
	}

	function uewRegister() {
		if ( ! window.elementorFrontend || ! window.elementorFrontend.hooks ) {
			return false;
		}
		window.elementorFrontend.hooks.addAction( 'frontend/element_ready/' + WIDGET_NAME + '.default', uewInit );
		return true;
	}

	if ( ! uewRegister() ) {
		// Elementor fires this through jQuery, not as a native DOM event, so a
		// plain addEventListener would never hear it.
		if ( window.jQuery ) {
			window.jQuery( window ).on( 'elementor/frontend/init', uewRegister );
		} else {
			window.addEventListener( 'elementor/frontend/init', uewRegister );
		}
	}

	// Plain page load (and any context where Elementor's frontend never boots).
	if ( document.readyState === 'loading' ) {
		document.addEventListener( 'DOMContentLoaded', function () {
			uewInit( document );
		} );
	} else {
		uewInit( document );
	}
}() );
`;
}

export function emitCss( section, css ) {
	return `/**
 * ${ section.title } -- section styles.
 *
 * GENERATED by tools/uew from ${ section.source }. Do not edit by hand.
 * This is the section's own stylesheet, copied through unchanged. Elementor
 * style controls layer their generated CSS on top of it; they never replace it.
 */
${ css.trimEnd() }
`;
}

export function emitWidgetClass( section ) {
	return `<?php
/**
 * ${ section.title } widget.
 *
 * GENERATED by tools/uew. Every behaviour lives in Umoya_EW\\Section_Widget,
 * driven by includes/sections/${ section.key }.json.
 */

namespace Umoya_EW\\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class ${ section.class_name } extends \\Umoya_EW\\Section_Widget {

	protected function section_key() {
		return '${ section.key }';
	}
}
`;
}

export function emitSchema( schema ) {
	return JSON.stringify( schema, null, '\t' ) + '\n';
}
