<?php
/**
 * About How We Choose -- render template.
 *
 * GENERATED by tools/uew from about/section-05-how-we-choose.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — ABOUT US — SECTION 05: HOW WE CHOOSE
=================================================================
  Centred statement on white — the honesty/ownership position.
  Sits between Our Story (cream) and the Hosts grid.

  ANCHOR: id="ab-choose"
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="ab-choose" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="ab-ch-c ab-ch-rv">
    <span class="ab-ch-eye"><?php echo $c['eyebrow_text']; ?></span>
    <h2 class="ab-ch-ttl"><?php echo $c['title_text']; ?></h2>
    <?php $__i = 0; foreach ( $r['rep_p_ab_ch_p'] as $it ) : if ( $__i ++ ) { echo '
    '; } ?><p class="ab-ch-p <?php echo $it['_uew_item_class']; ?>"><?php echo $it['p']; ?></p><?php endforeach; echo "\n  "; ?></div>
</section>
