<?php
/**
 * About The Umoya Difference -- render template.
 *
 * GENERATED by tools/uew from about/section-07-difference.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — ABOUT US — SECTION 07: THE UMOYA DIFFERENCE
=================================================================
  Four icon cards covering what sets an Umoya journey apart.
  Icons are inline SVG (stroke: terracotta) — no icon fonts.

  ANCHOR: id="ab-difference"
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="ab-difference" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="ab-df-c">

    <div class="ab-df-head ab-df-rv">
      <span class="ab-df-eye"><?php echo $c['eyebrow_text']; ?></span>
      <h2 class="ab-df-ttl"><?php echo $c['title_text']; ?></h2>
    </div>

    <div class="ab-df-grid" role="list">

      <?php $__i = 0; foreach ( $r['rep_div_ab_df_card'] as $it ) : if ( $__i ++ ) { echo '

      '; } ?><div class="<?php echo array( 'ab-df-card ab-df-rv', 'ab-df-card ab-df-rv d1', 'ab-df-card ab-df-rv d2', 'ab-df-card ab-df-rv d3' )[ ( ( (int) $it['_uew_n'] ) - 1 ) % 4 ]; ?> <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['role']; ?>">
        <span class="ab-df-ic" aria-hidden="<?php echo $it['aria_hidden']; ?>">
          <svg viewBox="<?php echo $it['viewbox']; ?>"><?php echo $it['svg_markup']; ?></svg>
        </span>
        <h3 class="ab-df-h"><?php echo $it['h']; ?></h3>
        <p class="ab-df-p"><?php echo $it['p']; ?></p>
      </div><?php endforeach; echo "\n\n    "; ?></div>
  </div>
</section>
