<?php
/**
 * About Hero -- render template.
 *
 * GENERATED by tools/uew from about/section-01-hero.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — ABOUT US — SECTION 01: HERO
=================================================================
  Centred hero. The mockup calls for a background VIDEO (brand film
  or trip B-roll); this is built video-ready:
  • The <img> poster paints instantly.
  • The <video> fades in only once it can actually autoplay
    (mobile-safe), so the poster never flashes to black.
  ★ SWAP: point the <source> at the final brand film. To ship the
  still only, delete the <video> block and its script.

  ANCHOR: id="ab-hero" — first content widget after the site nav.
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="ab-hero" aria-label="<?php echo $c['section_aria_label']; ?>">

  <div class="ab-h-bg">
    <!-- Poster paints instantly; the video fades in once it can autoplay -->
    <img
      src="<?php echo $c['image_src']; ?>"
      alt="<?php echo $c['image_alt']; ?>"
    />
    <!-- ★ SWAP: final brand film / trip B-roll. Delete this block to keep the still. -->
    <video
      id="ab-hero-vid"<?php echo $c['video_autoplay']; ?><?php echo $c['video_muted']; ?><?php echo $c['video_loop']; ?><?php echo $c['video_playsinline']; ?> webkit-playsinline preload="<?php echo $c['video_preload']; ?>"
      poster="<?php echo $c['video_poster']; ?>"
      aria-label="<?php echo $c['video_aria_label']; ?>"
      style="<?php echo $s['video_inline_style']; ?>"<?php echo $c['video_controls']; ?><?php echo $c['video_disablepictureinpicture']; echo "\n    "; ?>>
      <source src="<?php echo $c['video_source_src']; ?>" type="<?php echo $c['video_source_type']; ?>" />
    </video>
  </div>

  <div class="ab-h-content">
    <span class="ab-h-eye"><?php echo $c['eyebrow_text']; ?></span>
    <h1 class="ab-h-title"><?php echo $c['title_text']; ?></h1>
    <p class="ab-h-sub"><?php echo $c['subtitle_text']; ?></p>
  </div>

</section>
