<?php
/**
 * About Meet Our Hosts -- render template.
 *
 * GENERATED by tools/uew from about/section-06-hosts.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — ABOUT US — SECTION 06: MEET OUR HOSTS
=================================================================
  Six host cards. Each is a real, named person (or place) who
  receives guests on an Umoya journey.

  ANCHOR: id="ab-hosts"

  IMAGES: all six cards now carry client-approved photography.

  Two identity notes worth preserving:
  • Lucia Motloung is ZAV_6354. An earlier link pointed at ZAV_6406,
    which is the Eyethu building — not her.
  • ZAV_6406 is the ONE approved Eyethu image and is used site-wide
    (here, and as the Soweto image on the Founder's Circle journey
    section). Do not substitute another Eyethu shot.

  Superseded files still sit on the server (nothing is ever deleted)
  and should NOT be referenced:
    umoya_about_eyethu_heritage_hall.jpg      (older, flatter Eyethu)
    umoya_compressed_about_tshabalala_family.jpg (brightened copy of it)
    umoya_compressed_about_host_lucia.jpg     (actually ZAV_6406 — misnamed)

  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="ab-hosts" aria-label="<?php echo $c['c_section_aria_label']; ?>">
  <div class="ab-ho-c">

    <div class="ab-ho-head ab-ho-rv">
      <span class="ab-ho-eye"><?php echo $c['c_ab_ho_eye_text']; ?></span>
      <h2 class="ab-ho-ttl"><?php echo $c['c_ab_ho_ttl_text']; ?></h2>
      <p class="ab-ho-lead"><?php echo $c['c_ab_ho_lead_text']; ?></p>
    </div>

    <div class="ab-ho-grid" role="list">

      <!-- Lucia Motloung — ZAV_6354, confirmed by the client and already on
           the server. (The earlier link resolved to ZAV_6406, which was the
           Eyethu photo — deliberately not used here.) -->
      <?php $__i = 0; foreach ( $r['rep_article_ab_ho_card'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><article class="<?php echo array( 'ab-ho-card ab-ho-rv', 'ab-ho-card ab-ho-rv d1', 'ab-ho-card ab-ho-rv d2', 'ab-ho-card ab-ho-rv', 'ab-ho-card ab-ho-rv d1', 'ab-ho-card ab-ho-rv d2' )[ ( ( (int) $it['_uew_n'] ) - 1 ) % 6 ]; ?> <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['role']; ?>">
        <div class="ab-ho-img"><?php echo $it['notes']; ?><img class="ab-ho-pic" src="<?php echo $it['src']; ?>" alt="<?php echo $it['alt']; ?>" loading="<?php echo $it['loading']; ?>" decoding="<?php echo $it['decoding']; ?>">
        </div>
        <div class="ab-ho-body">
          <div class="ab-ho-role"><?php echo $it['role_2']; ?></div>
          <h3 class="ab-ho-name"><?php echo $it['name']; ?></h3>
          <p class="ab-ho-desc"><?php echo $it['desc']; ?></p>
        </div>
      </article><?php endforeach; echo "\n\n    "; ?></div>
  </div>
</section>
