<?php
/**
 * About Our Story -- render template.
 *
 * GENERATED by tools/uew from about/section-04-our-story.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — ABOUT US — SECTION 04: OUR STORY
=================================================================
  Founder's story — portrait left, copy right.

  ANCHOR: id="ab-story"
  ★ SWAP: the portrait is a labelled placeholder — drop in the
  Wilson Nyah portrait (or a trip photo of him) by replacing the
  .ab-st-ph block with an <img class="ab-st-pic" …>.
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="ab-story" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="ab-st-c">
    <div class="ab-st-grid">

      <!-- Wilson Nyah portrait — client-supplied -->
      <div class="ab-st-photo ab-st-rv">
        <img class="ab-st-pic" src="<?php echo $c['image_src']; ?>" alt="<?php echo $c['image_alt']; ?>" loading="<?php echo $c['image_loading']; ?>" decoding="<?php echo $c['image_decoding']; ?>">
      </div>

      <div class="ab-st-rv d1">
        <span class="ab-st-eye"><?php echo $c['eyebrow_text']; ?></span>
        <h2 class="ab-st-ttl"><?php echo $c['title_text']; ?></h2>
        <?php $__i = 0; foreach ( $r['rep_p_ab_st_p'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><p class="ab-st-p <?php echo $it['_uew_item_class']; ?>"><?php echo $it['p']; ?></p><?php endforeach; echo "\n      "; ?></div>

    </div>
  </div>
</section>
