<?php
/**
 * About Who We Are -- render template.
 *
 * GENERATED by tools/uew from about/section-02-who-we-are.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — ABOUT US — SECTION 02: WHO WE ARE
=================================================================
  Two-column: the meaning of "Umoya" (copy left) + a photo
  carousel (right). The carousel auto-advances with a gentle eased
  crossfade and has dot navigation.

  ANCHOR: id="ab-who"
  ★ SWAP: the four carousel frames use existing Umoya CDN trip
  photography — replace with the final approved selection.
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="ab-who" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="ab-wh-c">
    <div class="ab-wh-grid">

      <div class="ab-wh-rv">
        <span class="ab-wh-eye"><?php echo $c['eyebrow_text']; ?></span>
        <h2 class="ab-wh-ttl"><?php echo $c['title_text']; ?></h2>
        <p class="ab-wh-pron"><?php echo $c['text_text']; ?></p>
        <?php $__i = 0; foreach ( $r['rep_p_ab_wh_p'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><p class="ab-wh-p <?php echo $it['_uew_item_class']; ?>"><?php echo $it['p']; ?></p><?php endforeach; echo "\n      "; ?></div>

      <!-- Six client-approved frames. Slides 5 and 6 reuse images already on
           the server (ZAV_8817 = the solo-travel shot; ZAV_8926) rather than
           re-uploading duplicates. -->
      <div class="ab-wh-carousel ab-wh-rv d1" data-ab-carousel role="region" aria-roledescription="<?php echo $c['slide_aria_roledescription']; ?>" aria-label="<?php echo $c['slide_aria_label']; ?>">
        <?php $__i = 0; foreach ( $r['rep_div_ab_wh_slide'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><div class="<?php echo ( 1 === ( (int) $it['_uew_n'] ) ? 'ab-wh-slide ab-on' : 'ab-wh-slide' ); ?> <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['l1_role']; ?>" aria-roledescription="<?php echo $it['l1_aria_roledescription']; ?>" aria-label="<?php echo $it['_uew_n'] . ' of ' . $it['_uew_count']; ?>">
          <img src="<?php echo $it['l1_src']; ?>" alt="<?php echo $it['l1_alt']; ?>" loading="<?php echo $it['l1_loading']; ?>" decoding="<?php echo $it['l1_decoding']; ?>">
        </div><?php endforeach; echo "\n\n        "; ?><div class="ab-wh-dots" role="tablist" aria-label="<?php echo $c['dot_aria_label']; ?>">
          <?php $__i = 0; foreach ( $r['rep_div_ab_wh_slide'] as $it ) : if ( $__i ++ ) { echo '
          '; } ?><button class="<?php echo ( 1 === ( (int) $it['_uew_n'] ) ? 'ab-wh-dot ab-on' : 'ab-wh-dot' ); ?> <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['l2_role']; ?>" aria-selected="<?php echo ( 1 === ( (int) $it['_uew_n'] ) ? 'true' : 'false' ); ?>" aria-label="<?php echo 'Show image ' . $it['_uew_n']; ?>"></button><?php endforeach; echo "\n        "; ?></div>
      </div>

    </div>
  </div>
</section>
