<?php
/**
 * Contact Enquiry Forms -- render template.
 *
 * GENERATED by tools/uew from contact/section-02-forms.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — CONTACT — SECTION 02: THE TWO ENQUIRY PANELS
=================================================================
  Built from "Mockups (footer, contact)/Umoya_Contact_Page_Mockup.html".
  Field order, labels, placeholders, option lists and button text
  are the mockup's, verbatim. The mockup's fonts and sampled hexes
  are NOT carried over — the routing doc states the mockup colours
  are illustrative — so this uses font-family: inherit and the
  brand palette.

  TWO PANELS, TWO HUBSPOT FORMS
    Panel 1  Plan a Journey    → "Contact Page Journey Inquiry"
                                 1e38d41f-3e99-4605-94cc-9057857a4e82
                                 source = contact_page_journey
    Panel 2  General & Media   → "Contact Page General & Media Inquiry"
                                 ffececd7-b401-43cb-8ee2-858b5d62892c
                                 source = contact_page_general

  Separate forms so "plan my trip" and "I am a journalist" never
  land in the same conversion number. Both created 2026-08-29 via
  tools/hubspot-sync.mjs create-forms.

  SUBMIT PATH — identical to every other Umoya form:
    1. POST /wp-json/umoya/v1/submissions (WordPress stores the lead,
       then forwards it to HubSpot)
    2. if WordPress is unreachable → POST straight to the HubSpot
       Forms API and queue the WordPress backup in localStorage
  WordPress-first means a HubSpot outage never loses a lead.

  PROPERTY MAPPING — mirrored server-side in class-submissions.php
  ($source_aliases). Both tables must stay in step; asserted by
  tools/verify-alias-mapping.mjs.

    Panel 1  MERGE1 → salutation             MERGE2 → country
             MERGE3 → city                   MERGE4 → preferred_travel_season
             MERGE5 → preferred_travel_year  MERGE6 → party_size
             MERGE7 → founders_circle_message
    Panel 2  MERGE2 → enquiry_type           MERGE3 → organization
             MERGE7 → founders_circle_message

  FULL NAME: panel 2 asks for one "Full name" field, as the mockup
  does, but HubSpot stores firstname/lastname. The visible field is
  split into two hidden inputs on every keystroke, so the split is
  already in the DOM if a no-JS native POST ever fires.

  POPIA: consent boxes are never pre-ticked, and the exact wording
  agreed to is sent with the submission so the consent register can
  show what was consented to. The required consent box on panel 2
  is NOT in the mockup — it was added for parity with every other
  Umoya form, since panel 2 also processes personal data. See
  _NOTES.md.

  data-hs-do-not-collect stops HubSpot's collectedforms.js filing a
  duplicate "captured form" record alongside our clean API call.

  ANCHORS: #ct-plan and #ct-general — link straight to a panel.
  ELEMENTOR: place between section-01-hero and section-03-direct.
  BRAND: font-family: inherit; palette tokens only. ES5 IIFE.
  A11y: 44px targets, 16px input floor, one <h2> per panel.
=================================================================
-->
<section id="umoya-contact-forms" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="ct-f-c">
    <!-- One hidden target for both forms: keeps a no-JS native POST from
         navigating the visitor away from the page. -->
    <iframe name="umoyaContactFrame" title="<?php echo $c['embed_title']; ?>" aria-hidden="true" style="<?php echo $s['embed_inline_style']; ?>"<?php echo $c['embed_allowfullscreen']; ?>></iframe>

    <div class="ct-f-grid">

      <!-- ══════════ PANEL 1 — PLAN A JOURNEY ══════════ -->
      <div class="ct-f-card ct-f-rv" id="ct-plan">
        <h2 class="ct-f-ttl"><?php echo $c['title_text']; ?></h2>
        <p class="ct-f-sub"><?php echo $c['subtitle_text']; ?></p>

        <form
          data-hs-do-not-collect="<?php echo $c['form_data_hs_do_not_collect']; ?>"
          class="ct-f-form"
          id="ctPlanForm"
          action="<?php echo $c['form_action']; ?>"
          method="<?php echo $c['form_method']; ?>"
          target="<?php echo $c['form_target']; ?>"<?php echo $c['form_novalidate']; echo "\n          "; ?>aria-label="<?php echo $c['form_aria_label']; ?>"
          data-hubspot-portal-id="<?php echo $c['form_data_hubspot_portal_id']; ?>"
          data-hubspot-form-id="<?php echo $c['form_data_hubspot_form_id']; ?>"
          data-umoya-form-source="<?php echo $c['form_data_umoya_form_source']; ?>"
          data-wordpress-backup-endpoint="<?php echo $c['form_data_wordpress_backup_endpoint']; ?>"
          data-hubspot-consent-text="<?php echo $c['form_data_hubspot_consent_text']; ?>"
        >
          <input type="<?php echo $c['field_type']; ?>" name="<?php echo $c['field_name']; ?>" value="<?php echo $c['field_value']; ?>"<?php echo $c['field_required']; ?><?php echo $c['field_disabled']; ?><?php echo $c['field_readonly']; ?><?php echo $c['field_checked']; ?>>
          <input type="<?php echo $c['field_type_2']; ?>" name="<?php echo $c['field_name_2']; ?>" value="<?php echo $c['field_value_2']; ?>"<?php echo $c['field_required_2']; ?><?php echo $c['field_disabled_2']; ?><?php echo $c['field_readonly_2']; ?><?php echo $c['field_checked_2']; ?>>
          <input type="<?php echo $c['field_type_3']; ?>" name="<?php echo $c['field_name_3']; ?>" value="<?php echo $c['field_value_3']; ?>"<?php echo $c['field_required_3']; ?><?php echo $c['field_disabled_3']; ?><?php echo $c['field_readonly_3']; ?><?php echo $c['field_checked_3']; ?>>
          <input type="<?php echo $c['field_type_4']; ?>" name="<?php echo $c['field_name_4']; ?>" value="<?php echo $c['field_value_4']; ?>"<?php echo $c['field_required_4']; ?><?php echo $c['field_disabled_4']; ?><?php echo $c['field_readonly_4']; ?><?php echo $c['field_checked_4']; ?>>
          <input type="<?php echo $c['field_type_5']; ?>" name="<?php echo $c['field_name_5']; ?>" value="<?php echo $c['field_value_5']; ?>"<?php echo $c['field_required_5']; ?><?php echo $c['field_disabled_5']; ?><?php echo $c['field_readonly_5']; ?><?php echo $c['field_checked_5']; ?>>
          <input type="<?php echo $c['field_type_6']; ?>" name="<?php echo $c['field_name_6']; ?>" value="<?php echo $c['field_value_6']; ?>"<?php echo $c['field_required_6']; ?><?php echo $c['field_disabled_6']; ?><?php echo $c['field_readonly_6']; ?><?php echo $c['field_checked_6']; ?>>
          <input type="<?php echo $c['field_type_7']; ?>" name="<?php echo $c['field_name_7']; ?>" value="<?php echo $c['field_value_7']; ?>"<?php echo $c['field_required_7']; ?><?php echo $c['field_disabled_7']; ?><?php echo $c['field_readonly_7']; ?><?php echo $c['field_checked_7']; ?>>

          <div class="ct-f-field">
            <label for="ctTitle"><?php echo $c['label_text']; ?></label>
            <select id="ctTitle" name="<?php echo $c['select_name']; ?>"<?php echo $c['select_required']; ?><?php echo $c['select_disabled']; ?><?php echo $c['select_multiple']; ?>>
              <?php $__i = 0; foreach ( $r['rep_option'] as $it ) : if ( $__i ++ ) { echo '
              '; } ?><option value="<?php echo $it['value']; ?>"<?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n            "; ?></select>
          </div>

          <div class="ct-f-row">
            <div class="ct-f-field">
              <label for="ctFirst"><?php echo $c['label_text_2']; ?> <span class="ct-f-req" aria-hidden="true"><?php echo $c['text_text']; ?></span></label>
              <input type="<?php echo $c['anchor_type']; ?>" id="ctFirst" name="<?php echo $c['anchor_name']; ?>" placeholder="<?php echo $c['anchor_placeholder']; ?>"<?php echo $c['anchor_required']; ?> autocomplete="<?php echo $c['anchor_autocomplete']; ?>"<?php echo $c['anchor_disabled']; ?><?php echo $c['anchor_readonly']; ?><?php echo $c['anchor_checked']; ?>>
            </div>
            <div class="ct-f-field">
              <label for="ctLast"><?php echo $c['label_text_3']; ?> <span class="ct-f-req" aria-hidden="true"><?php echo $c['text_text_2']; ?></span></label>
              <input type="<?php echo $c['anchor_type_2']; ?>" id="ctLast" name="<?php echo $c['anchor_name_2']; ?>" placeholder="<?php echo $c['anchor_placeholder_2']; ?>"<?php echo $c['anchor_required_2']; ?> autocomplete="<?php echo $c['anchor_autocomplete_2']; ?>"<?php echo $c['anchor_disabled_2']; ?><?php echo $c['anchor_readonly_2']; ?><?php echo $c['anchor_checked_2']; ?>>
            </div>
          </div>

          <div class="ct-f-row">
            <div class="ct-f-field">
              <label for="ctEmail"><?php echo $c['label_text_4']; ?> <span class="ct-f-req" aria-hidden="true"><?php echo $c['text_text_3']; ?></span></label>
              <input type="<?php echo $c['anchor_type_3']; ?>" id="ctEmail" name="<?php echo $c['anchor_name_3']; ?>" placeholder="<?php echo $c['anchor_placeholder_3']; ?>"<?php echo $c['anchor_required_3']; ?> autocomplete="<?php echo $c['anchor_autocomplete_3']; ?>"<?php echo $c['anchor_disabled_3']; ?><?php echo $c['anchor_readonly_3']; ?><?php echo $c['anchor_checked_3']; ?>>
            </div>
            <div class="ct-f-field">
              <label for="ctPhone"><?php echo $c['label_text_5']; ?></label>
              <input type="<?php echo $c['anchor_type_4']; ?>" id="ctPhone" name="<?php echo $c['anchor_name_4']; ?>" placeholder="<?php echo $c['anchor_placeholder_4']; ?>" autocomplete="<?php echo $c['anchor_autocomplete_4']; ?>"<?php echo $c['anchor_required_4']; ?><?php echo $c['anchor_disabled_4']; ?><?php echo $c['anchor_readonly_4']; ?><?php echo $c['anchor_checked_4']; ?>>
            </div>
          </div>

          <div class="ct-f-row">
            <div class="ct-f-field">
              <label for="ctCountry"><?php echo $c['label_text_6']; ?> <span class="ct-f-req" aria-hidden="true"><?php echo $c['text_text_4']; ?></span></label>
              <!-- Same list and same ISO values as the Founder's Circle form,
                   so the `country` property stays consistent across pages. -->
              <select id="ctCountry" name="<?php echo $c['select_name_2']; ?>"<?php echo $c['select_required_2']; ?><?php echo $c['select_disabled_2']; ?><?php echo $c['select_multiple_2']; ?>>
                <?php $__i = 0; foreach ( $r['rep_option_2'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n              "; ?></select>
            </div>
            <div class="ct-f-field">
              <label for="ctCity"><?php echo $c['label_text_7']; ?></label>
              <input type="<?php echo $c['anchor_type_5']; ?>" id="ctCity" name="<?php echo $c['anchor_name_5']; ?>" placeholder="<?php echo $c['anchor_placeholder_5']; ?>" autocomplete="<?php echo $c['anchor_autocomplete_5']; ?>"<?php echo $c['anchor_required_5']; ?><?php echo $c['anchor_disabled_5']; ?><?php echo $c['anchor_readonly_5']; ?><?php echo $c['anchor_checked_5']; ?>>
            </div>
          </div>

          <span class="ct-f-grouplabel" id="ctWhenLbl"><?php echo $c['text_text_5']; ?></span>
          <div class="ct-f-row ct-f-keep2">
            <div class="ct-f-field">
              <label for="ctMonth" class="ct-f-sr"><?php echo $c['label_text_8']; ?></label>
              <select id="ctMonth" name="<?php echo $c['select_name_3']; ?>"<?php echo $c['select_required_3']; ?><?php echo $c['select_disabled_3']; ?><?php echo $c['select_multiple_3']; ?>>
                <?php $__i = 0; foreach ( $r['rep_option_3'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n              "; ?></select>
            </div>
            <div class="ct-f-field">
              <label for="ctYear" class="ct-f-sr"><?php echo $c['label_text_9']; ?></label>
              <select id="ctYear" name="<?php echo $c['select_name_4']; ?>"<?php echo $c['select_required_4']; ?><?php echo $c['select_disabled_4']; ?><?php echo $c['select_multiple_4']; ?>>
                <?php $__i = 0; foreach ( $r['rep_option_4'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n              "; ?></select>
            </div>
          </div>

          <div class="ct-f-field">
            <label for="ctGuests"><?php echo $c['label_text_10']; ?></label>
            <select id="ctGuests" name="<?php echo $c['select_name_5']; ?>"<?php echo $c['select_required_5']; ?><?php echo $c['select_disabled_5']; ?><?php echo $c['select_multiple_5']; ?>>
              <?php $__i = 0; foreach ( $r['rep_option_5'] as $it ) : if ( $__i ++ ) { echo '
              '; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n            "; ?></select>
          </div>

          <div class="ct-f-field">
            <label for="ctMessage"><?php echo $c['label_text_11']; ?></label>
            <textarea id="ctMessage" name="<?php echo $c['anchor_name_6']; ?>" rows="<?php echo $c['anchor_rows']; ?>" placeholder="<?php echo $c['anchor_placeholder_6']; ?>"<?php echo $c['anchor_required_6']; ?><?php echo $c['anchor_disabled_6']; ?><?php echo $c['anchor_readonly_6']; ?>></textarea>
          </div>

          <label class="ct-f-consent" for="ctConsent">
            <input type="<?php echo $c['anchor_type_6']; ?>" id="ctConsent" name="<?php echo $c['anchor_name_7']; ?>"<?php echo $c['anchor_required_7']; ?><?php echo $c['anchor_disabled_7']; ?><?php echo $c['anchor_readonly_7']; ?><?php echo $c['anchor_checked_6']; ?>>
            <span><?php echo $c['text_text_6']; ?> <a href="<?php echo $c['link_href']; ?>" target="<?php echo $c['link_target']; ?>" rel="<?php echo $c['link_rel']; ?>"><?php echo $c['link_text']; ?></a><?php echo $c['text_text_2_2']; ?> <span class="ct-f-flag"><?php echo $c['text_text_7']; ?></span></span>
          </label>

          <label class="ct-f-consent" for="ctMarketing">
            <input type="<?php echo $c['anchor_type_7']; ?>" id="ctMarketing" name="<?php echo $c['anchor_name_8']; ?>"<?php echo $c['anchor_required_8']; ?><?php echo $c['anchor_disabled_8']; ?><?php echo $c['anchor_readonly_8']; ?><?php echo $c['anchor_checked_7']; ?>>
            <span><?php echo $c['text_text_8']; ?> <span class="ct-f-flag"><?php echo $c['text_text_9']; ?></span></span>
          </label>

          <button type="<?php echo $c['button_type']; ?>" class="ct-f-btn" id="ctPlanBtn"<?php echo $c['button_disabled']; ?>><?php echo $c['button_text']; ?></button>
          <p class="ct-f-legal"><?php echo $c['consent_text']; ?></p>
        </form>
      </div>

      <!-- ══════════ PANEL 2 — GENERAL &amp; MEDIA ══════════ -->
      <div class="ct-f-card ct-f-rv d1" id="ct-general">
        <h2 class="ct-f-ttl"><?php echo $c['title_text_2']; ?></h2>
        <p class="ct-f-sub"><?php echo $c['subtitle_text_2']; ?></p>

        <form
          data-hs-do-not-collect="<?php echo $c['form_data_hs_do_not_collect_2']; ?>"
          class="ct-f-form"
          id="ctGeneralForm"
          action="<?php echo $c['form_action_2']; ?>"
          method="<?php echo $c['form_method_2']; ?>"
          target="<?php echo $c['form_target_2']; ?>"<?php echo $c['form_novalidate_2']; echo "\n          "; ?>aria-label="<?php echo $c['form_aria_label_2']; ?>"
          data-hubspot-portal-id="<?php echo $c['form_data_hubspot_portal_id_2']; ?>"
          data-hubspot-form-id="<?php echo $c['form_data_hubspot_form_id_2']; ?>"
          data-umoya-form-source="<?php echo $c['form_data_umoya_form_source_2']; ?>"
          data-wordpress-backup-endpoint="<?php echo $c['form_data_wordpress_backup_endpoint_2']; ?>"
          data-hubspot-consent-text="<?php echo $c['form_data_hubspot_consent_text_2']; ?>"
        >
          <input type="<?php echo $c['field_type_8']; ?>" name="<?php echo $c['field_name_8']; ?>" value="<?php echo $c['field_value_8']; ?>"<?php echo $c['field_required_8']; ?><?php echo $c['field_disabled_8']; ?><?php echo $c['field_readonly_8']; ?><?php echo $c['field_checked_8']; ?>>
          <input type="<?php echo $c['field_type_9']; ?>" name="<?php echo $c['field_name_9']; ?>" value="<?php echo $c['field_value_9']; ?>"<?php echo $c['field_required_9']; ?><?php echo $c['field_disabled_9']; ?><?php echo $c['field_readonly_9']; ?><?php echo $c['field_checked_9']; ?>>
          <input type="<?php echo $c['field_type_10']; ?>" name="<?php echo $c['field_name_10']; ?>" value="<?php echo $c['field_value_10']; ?>"<?php echo $c['field_required_10']; ?><?php echo $c['field_disabled_10']; ?><?php echo $c['field_readonly_10']; ?><?php echo $c['field_checked_10']; ?>>
          <input type="<?php echo $c['field_type_11']; ?>" name="<?php echo $c['field_name_11']; ?>" value="<?php echo $c['field_value_11']; ?>"<?php echo $c['field_required_11']; ?><?php echo $c['field_disabled_11']; ?><?php echo $c['field_readonly_11']; ?><?php echo $c['field_checked_11']; ?>>
          <input type="<?php echo $c['field_type_12']; ?>" name="<?php echo $c['field_name_12']; ?>" value="<?php echo $c['field_value_12']; ?>"<?php echo $c['field_required_12']; ?><?php echo $c['field_disabled_12']; ?><?php echo $c['field_readonly_12']; ?><?php echo $c['field_checked_12']; ?>>
          <input type="<?php echo $c['field_type_13']; ?>" name="<?php echo $c['field_name_13']; ?>" value="<?php echo $c['field_value_13']; ?>"<?php echo $c['field_required_13']; ?><?php echo $c['field_disabled_13']; ?><?php echo $c['field_readonly_13']; ?><?php echo $c['field_checked_13']; ?>>
          <input type="<?php echo $c['field_type_14']; ?>" name="<?php echo $c['field_name_14']; ?>" value="<?php echo $c['field_value_14']; ?>"<?php echo $c['field_required_14']; ?><?php echo $c['field_disabled_14']; ?><?php echo $c['field_readonly_14']; ?><?php echo $c['field_checked_14']; ?>>
          <!-- Split from the visible "Full name" field on every keystroke -->
          <input type="<?php echo $c['field_type_15']; ?>" name="<?php echo $c['field_name_15']; ?>" value="<?php echo $c['field_value_15']; ?>"<?php echo $c['field_required_15']; ?><?php echo $c['field_disabled_15']; ?><?php echo $c['field_readonly_15']; ?><?php echo $c['field_checked_15']; ?>>
          <input type="<?php echo $c['field_type_16']; ?>" name="<?php echo $c['field_name_16']; ?>" value="<?php echo $c['field_value_16']; ?>"<?php echo $c['field_required_16']; ?><?php echo $c['field_disabled_16']; ?><?php echo $c['field_readonly_16']; ?><?php echo $c['field_checked_16']; ?>>

          <div class="ct-f-field">
            <label for="ctGenName"><?php echo $c['label_text_12']; ?> <span class="ct-f-req" aria-hidden="true"><?php echo $c['text_text_10']; ?></span></label>
            <input type="<?php echo $c['anchor_type_8']; ?>" id="ctGenName" name="<?php echo $c['anchor_name_9']; ?>" placeholder="<?php echo $c['anchor_placeholder_7']; ?>"<?php echo $c['anchor_required_9']; ?> autocomplete="<?php echo $c['anchor_autocomplete_6']; ?>"<?php echo $c['anchor_disabled_9']; ?><?php echo $c['anchor_readonly_9']; ?><?php echo $c['anchor_checked_8']; ?>>
          </div>

          <div class="ct-f-field">
            <label for="ctGenEmail"><?php echo $c['label_text_13']; ?> <span class="ct-f-req" aria-hidden="true"><?php echo $c['text_text_11']; ?></span></label>
            <input type="<?php echo $c['anchor_type_9']; ?>" id="ctGenEmail" name="<?php echo $c['anchor_name_10']; ?>" placeholder="<?php echo $c['anchor_placeholder_8']; ?>"<?php echo $c['anchor_required_10']; ?> autocomplete="<?php echo $c['anchor_autocomplete_7']; ?>"<?php echo $c['anchor_disabled_10']; ?><?php echo $c['anchor_readonly_10']; ?><?php echo $c['anchor_checked_9']; ?>>
          </div>

          <div class="ct-f-field">
            <label for="ctGenOrg"><?php echo $c['label_text_14']; ?></label>
            <input type="<?php echo $c['anchor_type_10']; ?>" id="ctGenOrg" name="<?php echo $c['anchor_name_11']; ?>" placeholder="<?php echo $c['anchor_placeholder_9']; ?>" autocomplete="<?php echo $c['anchor_autocomplete_8']; ?>"<?php echo $c['anchor_required_11']; ?><?php echo $c['anchor_disabled_11']; ?><?php echo $c['anchor_readonly_11']; ?><?php echo $c['anchor_checked_10']; ?>>
          </div>

          <div class="ct-f-field">
            <label for="ctGenType"><?php echo $c['label_text_15']; ?> <span class="ct-f-req" aria-hidden="true"><?php echo $c['text_text_12']; ?></span></label>
            <!-- These values must match the enquiry_type property options in
                 HubSpot exactly, or the enumeration rejects them. -->
            <select id="ctGenType" name="<?php echo $c['select_name_6']; ?>"<?php echo $c['select_required_6']; ?><?php echo $c['select_disabled_6']; ?><?php echo $c['select_multiple_6']; ?>>
              <?php $__i = 0; foreach ( $r['rep_option_6'] as $it ) : if ( $__i ++ ) { echo '
              '; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n            "; ?></select>
          </div>

          <div class="ct-f-field ct-f-grow">
            <label for="ctGenMessage"><?php echo $c['label_text_16']; ?></label>
            <textarea id="ctGenMessage" name="<?php echo $c['anchor_name_12']; ?>" rows="<?php echo $c['anchor_rows_2']; ?>" placeholder="<?php echo $c['anchor_placeholder_10']; ?>"<?php echo $c['anchor_required_12']; ?><?php echo $c['anchor_disabled_12']; ?><?php echo $c['anchor_readonly_12']; ?>></textarea>
          </div>

          <label class="ct-f-consent" for="ctGenConsent">
            <input type="<?php echo $c['anchor_type_11']; ?>" id="ctGenConsent" name="<?php echo $c['anchor_name_13']; ?>"<?php echo $c['anchor_required_13']; ?><?php echo $c['anchor_disabled_13']; ?><?php echo $c['anchor_readonly_13']; ?><?php echo $c['anchor_checked_11']; ?>>
            <span><?php echo $c['text_text_13']; ?> <a href="<?php echo $c['link_href_2']; ?>" target="<?php echo $c['link_target_2']; ?>" rel="<?php echo $c['link_rel_2']; ?>"><?php echo $c['link_text_2']; ?></a><?php echo $c['text_text_2_3']; ?> <span class="ct-f-flag"><?php echo $c['text_text_14']; ?></span></span>
          </label>

          <button type="<?php echo $c['button_type_2']; ?>" class="ct-f-btn is-secondary" id="ctGeneralBtn"<?php echo $c['button_disabled_2']; ?>><?php echo $c['button_text_2']; ?></button>
        </form>
      </div>

    </div>
  </div>
</section>
