<?php
/**
 * Contact Enquiry Forms -- render template.
 *
 * GENERATED by tools/uew from contact/section-02-forms.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — CONTACT — SECTION 02: THE TWO ENQUIRY PANELS
=================================================================
  Built from "Mockups (footer, contact)/Umoya_Contact_Page_Mockup.html".
  Field order, labels, placeholders, option lists and button text
  are the mockup's, verbatim. The mockup's fonts and sampled hexes
  are NOT carried over — the routing doc states the mockup colours
  are illustrative — so this uses font-family: inherit and the
  brand palette.

  TWO PANELS, TWO HUBSPOT FORMS
    Panel 1  Plan a Journey    → "Contact Page Journey Inquiry"
                                 1e38d41f-3e99-4605-94cc-9057857a4e82
                                 source = contact_page_journey
    Panel 2  General & Media   → "Contact Page General & Media Inquiry"
                                 ffececd7-b401-43cb-8ee2-858b5d62892c
                                 source = contact_page_general

  Separate forms so "plan my trip" and "I am a journalist" never
  land in the same conversion number. Both created 2026-08-29 via
  tools/hubspot-sync.mjs create-forms.

  SUBMIT PATH — identical to every other Umoya form:
    1. POST /wp-json/umoya/v1/submissions (WordPress stores the lead,
       then forwards it to HubSpot)
    2. if WordPress is unreachable → POST straight to the HubSpot
       Forms API and queue the WordPress backup in localStorage
  WordPress-first means a HubSpot outage never loses a lead.

  PROPERTY MAPPING — mirrored server-side in class-submissions.php
  ($source_aliases). Both tables must stay in step; asserted by
  tools/verify-alias-mapping.mjs.

    Panel 1  MERGE1 → salutation             MERGE2 → country
             MERGE3 → city                   MERGE4 → preferred_travel_season
             MERGE5 → preferred_travel_year  MERGE6 → party_size
             MERGE7 → founders_circle_message
    Panel 2  MERGE2 → enquiry_type           MERGE3 → organization
             MERGE7 → founders_circle_message

  FULL NAME: panel 2 asks for one "Full name" field, as the mockup
  does, but HubSpot stores firstname/lastname. The visible field is
  split into two hidden inputs on every keystroke, so the split is
  already in the DOM if a no-JS native POST ever fires.

  POPIA: consent boxes are never pre-ticked, and the exact wording
  agreed to is sent with the submission so the consent register can
  show what was consented to. The required consent box on panel 2
  is NOT in the mockup — it was added for parity with every other
  Umoya form, since panel 2 also processes personal data. See
  _NOTES.md.

  data-hs-do-not-collect stops HubSpot's collectedforms.js filing a
  duplicate "captured form" record alongside our clean API call.

  ANCHORS: #ct-plan and #ct-general — link straight to a panel.
  ELEMENTOR: place between section-01-hero and section-03-direct.
  BRAND: font-family: inherit; palette tokens only. ES5 IIFE.
  A11y: 44px targets, 16px input floor, one <h2> per panel.
=================================================================
-->
<section id="umoya-contact-forms" aria-label="<?php echo $c['c_section_aria_label']; ?>">
  <div class="ct-f-c">
    <!-- One hidden target for both forms: keeps a no-JS native POST from
         navigating the visitor away from the page. -->
    <iframe name="umoyaContactFrame" title="<?php echo $c['c_ct_f_c_title']; ?>" aria-hidden="true" style="<?php echo $s['c_ct_f_c_inline_style']; ?>"<?php echo $c['c_ct_f_c_allowfullscreen']; ?>></iframe>

    <div class="ct-f-grid">

      <!-- ══════════ PANEL 1 — PLAN A JOURNEY ══════════ -->
      <div class="ct-f-card ct-f-rv" id="ct-plan">
        <h2 class="ct-f-ttl"><?php echo $c['c_ct_f_card_h2_text']; ?></h2>
        <p class="ct-f-sub"><?php echo $c['c_ct_f_card_p_text']; ?></p>

        <form
          data-hs-do-not-collect="<?php echo $c['c_ct_f_card_form_data_hs_do_not_collect']; ?>"
          class="ct-f-form"
          id="ctPlanForm"
          action="<?php echo $c['c_ct_f_card_form_action']; ?>"
          method="<?php echo $c['c_ct_f_card_form_method']; ?>"
          target="<?php echo $c['c_ct_f_card_form_target']; ?>"<?php echo $c['c_ct_f_card_form_novalidate']; echo "\n          "; ?>aria-label="<?php echo $c['c_ct_f_card_form_aria_label']; ?>"
          data-hubspot-portal-id="<?php echo $c['c_ct_f_card_form_data_hubspot_portal_id']; ?>"
          data-hubspot-form-id="<?php echo $c['c_ct_f_card_form_data_hubspot_form_id']; ?>"
          data-umoya-form-source="<?php echo $c['c_ct_f_card_form_data_umoya_form_source']; ?>"
          data-wordpress-backup-endpoint="<?php echo $c['c_ct_f_card_form_data_wordpress_backup_endpoint']; ?>"
          data-hubspot-consent-text="<?php echo $c['c_ct_f_card_form_data_hubspot_consent_text']; ?>"
        >
          <input type="<?php echo $c['c_ct_f_card_form_type']; ?>" name="<?php echo $c['c_ct_f_card_form_name']; ?>" value="<?php echo $c['c_ct_f_card_form_value']; ?>">
          <input type="<?php echo $c['c_ct_f_card_form_type_2']; ?>" name="<?php echo $c['c_ct_f_card_form_name_2']; ?>" value="<?php echo $c['c_ct_f_card_form_value_2']; ?>">
          <input type="<?php echo $c['c_ct_f_card_form_type_3']; ?>" name="<?php echo $c['c_ct_f_card_form_name_3']; ?>" value="<?php echo $c['c_ct_f_card_form_value_3']; ?>">
          <input type="<?php echo $c['c_ct_f_card_form_type_4']; ?>" name="<?php echo $c['c_ct_f_card_form_name_4']; ?>" value="<?php echo $c['c_ct_f_card_form_value_4']; ?>">
          <input type="<?php echo $c['c_ct_f_card_form_type_5']; ?>" name="<?php echo $c['c_ct_f_card_form_name_5']; ?>" value="<?php echo $c['c_ct_f_card_form_value_5']; ?>">
          <input type="<?php echo $c['c_ct_f_card_form_type_6']; ?>" name="<?php echo $c['c_ct_f_card_form_name_6']; ?>" value="<?php echo $c['c_ct_f_card_form_value_6']; ?>">
          <input type="<?php echo $c['c_ct_f_card_form_type_7']; ?>" name="<?php echo $c['c_ct_f_card_form_name_7']; ?>" value="<?php echo $c['c_ct_f_card_form_value_7']; ?>">

          <div class="ct-f-field">
            <label for="ctTitle"><?php echo $c['c_ct_f_card_form_div_label_text']; ?></label>
            <select id="ctTitle" name="<?php echo $c['c_ct_f_card_form_div_select_name']; ?>"<?php echo $c['c_ct_f_card_form_div_select_required']; ?><?php echo $c['c_ct_f_card_form_div_select_disabled']; ?><?php echo $c['c_ct_f_card_form_div_select_multiple']; ?>>
              <?php $__i = 0; foreach ( $r['rep_option'] as $it ) : if ( $__i ++ ) { echo '
              '; } ?><option value="<?php echo $it['value']; ?>"<?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n            "; ?></select>
          </div>

          <div class="ct-f-row">
            <div class="ct-f-field">
              <label for="ctFirst"><?php echo $c['c_ct_f_row_div_label_text']; ?> <span class="ct-f-req" aria-hidden="true">*</span></label>
              <input type="<?php echo $c['c_ct_f_row_div_input_type']; ?>" id="ctFirst" name="<?php echo $c['c_ct_f_row_div_input_name']; ?>" placeholder="<?php echo $c['c_ct_f_row_div_input_placeholder']; ?>"<?php echo $c['c_ct_f_row_div_input_required']; ?> autocomplete="<?php echo $c['c_ct_f_row_div_input_autocomplete']; ?>"<?php echo $c['c_ct_f_row_div_input_disabled']; ?><?php echo $c['c_ct_f_row_div_input_readonly']; ?>>
            </div>
            <div class="ct-f-field">
              <label for="ctLast"><?php echo $c['c_ct_f_row_div_label_text_2']; ?> <span class="ct-f-req" aria-hidden="true">*</span></label>
              <input type="<?php echo $c['c_ct_f_row_div_input_type_2']; ?>" id="ctLast" name="<?php echo $c['c_ct_f_row_div_input_name_2']; ?>" placeholder="<?php echo $c['c_ct_f_row_div_input_placeholder_2']; ?>"<?php echo $c['c_ct_f_row_div_input_required_2']; ?> autocomplete="<?php echo $c['c_ct_f_row_div_input_autocomplete_2']; ?>"<?php echo $c['c_ct_f_row_div_input_disabled_2']; ?><?php echo $c['c_ct_f_row_div_input_readonly_2']; ?>>
            </div>
          </div>

          <div class="ct-f-row">
            <div class="ct-f-field">
              <label for="ctEmail"><?php echo $c['c_ct_f_row_div_label_text_3']; ?> <span class="ct-f-req" aria-hidden="true">*</span></label>
              <input type="<?php echo $c['c_ct_f_row_div_input_type_3']; ?>" id="ctEmail" name="<?php echo $c['c_ct_f_row_div_input_name_3']; ?>" placeholder="<?php echo $c['c_ct_f_row_div_input_placeholder_3']; ?>"<?php echo $c['c_ct_f_row_div_input_required_3']; ?> autocomplete="<?php echo $c['c_ct_f_row_div_input_autocomplete_3']; ?>"<?php echo $c['c_ct_f_row_div_input_disabled_3']; ?><?php echo $c['c_ct_f_row_div_input_readonly_3']; ?>>
            </div>
            <div class="ct-f-field">
              <label for="ctPhone"><?php echo $c['c_ct_f_row_div_label_text_4']; ?></label>
              <input type="<?php echo $c['c_ct_f_row_div_input_type_4']; ?>" id="ctPhone" name="<?php echo $c['c_ct_f_row_div_input_name_4']; ?>" placeholder="<?php echo $c['c_ct_f_row_div_input_placeholder_4']; ?>" autocomplete="<?php echo $c['c_ct_f_row_div_input_autocomplete_4']; ?>"<?php echo $c['c_ct_f_row_div_input_required_4']; ?><?php echo $c['c_ct_f_row_div_input_disabled_4']; ?><?php echo $c['c_ct_f_row_div_input_readonly_4']; ?>>
            </div>
          </div>

          <div class="ct-f-row">
            <div class="ct-f-field">
              <label for="ctCountry"><?php echo $c['c_ct_f_row_div_label_text_5']; ?> <span class="ct-f-req" aria-hidden="true">*</span></label>
              <!-- Same list and same ISO values as the Founder's Circle form,
                   so the `country` property stays consistent across pages. -->
              <select id="ctCountry" name="<?php echo $c['c_ct_f_row_div_select_name']; ?>"<?php echo $c['c_ct_f_row_div_select_required']; ?><?php echo $c['c_ct_f_row_div_select_disabled']; ?><?php echo $c['c_ct_f_row_div_select_multiple']; ?>>
                <?php $__i = 0; foreach ( $r['rep_option_2'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n              "; ?></select>
            </div>
            <div class="ct-f-field">
              <label for="ctCity"><?php echo $c['c_ct_f_row_div_label_text_6']; ?></label>
              <input type="<?php echo $c['c_ct_f_row_div_input_type_5']; ?>" id="ctCity" name="<?php echo $c['c_ct_f_row_div_input_name_5']; ?>" placeholder="<?php echo $c['c_ct_f_row_div_input_placeholder_5']; ?>" autocomplete="<?php echo $c['c_ct_f_row_div_input_autocomplete_5']; ?>"<?php echo $c['c_ct_f_row_div_input_required_5']; ?><?php echo $c['c_ct_f_row_div_input_disabled_5']; ?><?php echo $c['c_ct_f_row_div_input_readonly_5']; ?>>
            </div>
          </div>

          <span class="ct-f-grouplabel" id="ctWhenLbl"><?php echo $c['c_ct_f_grouplabel_text']; ?></span>
          <div class="ct-f-row ct-f-keep2">
            <div class="ct-f-field">
              <label for="ctMonth" class="ct-f-sr"><?php echo $c['c_ct_f_keep2_ct_f_field_text']; ?></label>
              <select id="ctMonth" name="<?php echo $c['c_ct_f_keep2_ct_f_field_select_name']; ?>"<?php echo $c['c_ct_f_keep2_ct_f_field_select_required']; ?><?php echo $c['c_ct_f_keep2_ct_f_field_select_disabled']; ?><?php echo $c['c_ct_f_keep2_ct_f_field_select_multiple']; ?>>
                <?php $__i = 0; foreach ( $r['rep_option_3'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n              "; ?></select>
            </div>
            <div class="ct-f-field">
              <label for="ctYear" class="ct-f-sr"><?php echo $c['c_ct_f_keep2_text']; ?></label>
              <select id="ctYear" name="<?php echo $c['c_ct_f_keep2_ct_f_field_select_name_2']; ?>"<?php echo $c['c_ct_f_keep2_ct_f_field_select_required_2']; ?><?php echo $c['c_ct_f_keep2_ct_f_field_select_disabled_2']; ?><?php echo $c['c_ct_f_keep2_ct_f_field_select_multiple_2']; ?>>
                <?php $__i = 0; foreach ( $r['rep_option_4'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n              "; ?></select>
            </div>
          </div>

          <div class="ct-f-field">
            <label for="ctGuests"><?php echo $c['c_ct_f_card_form_div_label_text_2']; ?></label>
            <select id="ctGuests" name="<?php echo $c['c_ct_f_card_form_div_select_name_2']; ?>"<?php echo $c['c_ct_f_card_form_div_select_required_2']; ?><?php echo $c['c_ct_f_card_form_div_select_disabled_2']; ?><?php echo $c['c_ct_f_card_form_div_select_multiple_2']; ?>>
              <?php $__i = 0; foreach ( $r['rep_option_5'] as $it ) : if ( $__i ++ ) { echo '
              '; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n            "; ?></select>
          </div>

          <div class="ct-f-field">
            <label for="ctMessage"><?php echo $c['c_ct_f_card_form_div_label_text_3']; ?></label>
            <textarea id="ctMessage" name="<?php echo $c['c_ct_f_card_form_div_textarea_name']; ?>" rows="<?php echo $c['c_ct_f_card_form_div_textarea_rows']; ?>" placeholder="<?php echo $c['c_ct_f_card_form_div_textarea_placeholder']; ?>"<?php echo $c['c_ct_f_card_form_div_textarea_required']; ?><?php echo $c['c_ct_f_card_form_div_textarea_disabled']; ?><?php echo $c['c_ct_f_card_form_div_textarea_readonly']; ?>></textarea>
          </div>

          <label class="ct-f-consent" for="ctConsent">
            <input type="<?php echo $c['c_ct_f_card_form_label_input_type']; ?>" id="ctConsent" name="<?php echo $c['c_ct_f_card_form_label_input_name']; ?>"<?php echo $c['c_ct_f_card_form_label_input_required']; ?><?php echo $c['c_ct_f_card_form_label_input_disabled']; ?><?php echo $c['c_ct_f_card_form_label_input_readonly']; ?><?php echo $c['c_ct_f_card_form_label_input_checked']; ?>>
            <span><?php echo $c['c_ct_f_card_form_label_span_text']; ?> <a href="<?php echo $c['c_ct_f_card_form_label_span_a_href']; ?>" target="<?php echo $c['c_ct_f_card_form_label_span_a_target']; ?>" rel="<?php echo $c['c_ct_f_card_form_label_span_a_rel']; ?>"><?php echo $c['c_ct_f_card_form_label_span_a_text']; ?></a>. <span class="ct-f-flag"><?php echo $c['c_ct_f_card_form_label_span_span_text']; ?></span></span>
          </label>

          <label class="ct-f-consent" for="ctMarketing">
            <input type="<?php echo $c['c_ct_f_card_form_label_input_type_2']; ?>" id="ctMarketing" name="<?php echo $c['c_ct_f_card_form_label_input_name_2']; ?>"<?php echo $c['c_ct_f_card_form_label_input_required_2']; ?><?php echo $c['c_ct_f_card_form_label_input_disabled_2']; ?><?php echo $c['c_ct_f_card_form_label_input_readonly_2']; ?><?php echo $c['c_ct_f_card_form_label_input_checked_2']; ?>>
            <span><?php echo $c['c_ct_f_card_form_label_span_text_2']; ?> <span class="ct-f-flag"><?php echo $c['c_ct_f_card_form_label_span_span_text_2']; ?></span></span>
          </label>

          <button type="<?php echo $c['c_ct_f_card_form_button_type']; ?>" class="ct-f-btn" id="ctPlanBtn"<?php echo $c['c_ct_f_card_form_button_disabled']; ?>><?php echo $c['c_ct_f_card_form_button_text']; ?></button>
          <p class="ct-f-legal"><?php echo $c['c_ct_f_legal_text']; ?></p>
        </form>
      </div>

      <!-- ══════════ PANEL 2 — GENERAL &amp; MEDIA ══════════ -->
      <div class="ct-f-card ct-f-rv d1" id="ct-general">
        <h2 class="ct-f-ttl"><?php echo $c['c_ct_f_card_h2_text_2']; ?></h2>
        <p class="ct-f-sub"><?php echo $c['c_ct_f_card_p_text_2']; ?></p>

        <form
          data-hs-do-not-collect="<?php echo $c['c_ct_f_card_form_data_hs_do_not_collect_2']; ?>"
          class="ct-f-form"
          id="ctGeneralForm"
          action="<?php echo $c['c_ct_f_card_form_action_2']; ?>"
          method="<?php echo $c['c_ct_f_card_form_method_2']; ?>"
          target="<?php echo $c['c_ct_f_card_form_target_2']; ?>"<?php echo $c['c_ct_f_card_form_novalidate_2']; echo "\n          "; ?>aria-label="<?php echo $c['c_ct_f_card_form_aria_label_2']; ?>"
          data-hubspot-portal-id="<?php echo $c['c_ct_f_card_form_data_hubspot_portal_id_2']; ?>"
          data-hubspot-form-id="<?php echo $c['c_ct_f_card_form_data_hubspot_form_id_2']; ?>"
          data-umoya-form-source="<?php echo $c['c_ct_f_card_form_data_umoya_form_source_2']; ?>"
          data-wordpress-backup-endpoint="<?php echo $c['c_ct_f_card_form_data_wordpress_backup_endpoint_2']; ?>"
          data-hubspot-consent-text="<?php echo $c['c_ct_f_card_form_data_hubspot_consent_text_2']; ?>"
        >
          <input type="<?php echo $c['c_ct_f_grid_type']; ?>" name="<?php echo $c['c_ct_f_grid_name']; ?>" value="<?php echo $c['c_ct_f_grid_value']; ?>">
          <input type="<?php echo $c['c_ct_f_grid_type_2']; ?>" name="<?php echo $c['c_ct_f_grid_name_2']; ?>" value="<?php echo $c['c_ct_f_grid_value_2']; ?>">
          <input type="<?php echo $c['c_ct_f_grid_type_3']; ?>" name="<?php echo $c['c_ct_f_grid_name_3']; ?>" value="<?php echo $c['c_ct_f_grid_value_3']; ?>">
          <input type="<?php echo $c['c_ct_f_grid_type_4']; ?>" name="<?php echo $c['c_ct_f_grid_name_4']; ?>" value="<?php echo $c['c_ct_f_grid_value_4']; ?>">
          <input type="<?php echo $c['c_ct_f_grid_type_5']; ?>" name="<?php echo $c['c_ct_f_grid_name_5']; ?>" value="<?php echo $c['c_ct_f_grid_value_5']; ?>">
          <input type="<?php echo $c['c_ct_f_grid_type_6']; ?>" name="<?php echo $c['c_ct_f_grid_name_6']; ?>" value="<?php echo $c['c_ct_f_grid_value_6']; ?>">
          <input type="<?php echo $c['c_ct_f_grid_type_7']; ?>" name="<?php echo $c['c_ct_f_grid_name_7']; ?>" value="<?php echo $c['c_ct_f_grid_value_7']; ?>">
          <!-- Split from the visible "Full name" field on every keystroke -->
          <input type="<?php echo $c['c_ct_f_grid_type_8']; ?>" name="<?php echo $c['c_ct_f_grid_name_8']; ?>" value="<?php echo $c['c_ct_f_grid_value_8']; ?>">
          <input type="<?php echo $c['c_ct_f_grid_type_9']; ?>" name="<?php echo $c['c_ct_f_grid_name_9']; ?>" value="<?php echo $c['c_ct_f_grid_value_9']; ?>">

          <div class="ct-f-field">
            <label for="ctGenName"><?php echo $c['c_ct_f_card_form_div_label_text_4']; ?> <span class="ct-f-req" aria-hidden="true">*</span></label>
            <input type="<?php echo $c['c_ct_f_card_form_div_input_type']; ?>" id="ctGenName" name="<?php echo $c['c_ct_f_card_form_div_input_name']; ?>" placeholder="<?php echo $c['c_ct_f_card_form_div_input_placeholder']; ?>"<?php echo $c['c_ct_f_card_form_div_input_required']; ?> autocomplete="<?php echo $c['c_ct_f_card_form_div_input_autocomplete']; ?>"<?php echo $c['c_ct_f_card_form_div_input_disabled']; ?><?php echo $c['c_ct_f_card_form_div_input_readonly']; ?>>
          </div>

          <div class="ct-f-field">
            <label for="ctGenEmail"><?php echo $c['c_ct_f_card_form_div_label_text_5']; ?> <span class="ct-f-req" aria-hidden="true">*</span></label>
            <input type="<?php echo $c['c_ct_f_card_form_div_input_type_2']; ?>" id="ctGenEmail" name="<?php echo $c['c_ct_f_card_form_div_input_name_2']; ?>" placeholder="<?php echo $c['c_ct_f_card_form_div_input_placeholder_2']; ?>"<?php echo $c['c_ct_f_card_form_div_input_required_2']; ?> autocomplete="<?php echo $c['c_ct_f_card_form_div_input_autocomplete_2']; ?>"<?php echo $c['c_ct_f_card_form_div_input_disabled_2']; ?><?php echo $c['c_ct_f_card_form_div_input_readonly_2']; ?>>
          </div>

          <div class="ct-f-field">
            <label for="ctGenOrg"><?php echo $c['c_ct_f_card_form_div_label_text_6']; ?></label>
            <input type="<?php echo $c['c_ct_f_card_form_div_input_type_3']; ?>" id="ctGenOrg" name="<?php echo $c['c_ct_f_card_form_div_input_name_3']; ?>" placeholder="<?php echo $c['c_ct_f_card_form_div_input_placeholder_3']; ?>" autocomplete="<?php echo $c['c_ct_f_card_form_div_input_autocomplete_3']; ?>"<?php echo $c['c_ct_f_card_form_div_input_required_3']; ?><?php echo $c['c_ct_f_card_form_div_input_disabled_3']; ?><?php echo $c['c_ct_f_card_form_div_input_readonly_3']; ?>>
          </div>

          <div class="ct-f-field">
            <label for="ctGenType"><?php echo $c['c_ct_f_card_form_div_label_text_7']; ?> <span class="ct-f-req" aria-hidden="true">*</span></label>
            <!-- These values must match the enquiry_type property options in
                 HubSpot exactly, or the enumeration rejects them. -->
            <select id="ctGenType" name="<?php echo $c['c_ct_f_card_form_div_select_name_3']; ?>"<?php echo $c['c_ct_f_card_form_div_select_required_3']; ?><?php echo $c['c_ct_f_card_form_div_select_disabled_3']; ?><?php echo $c['c_ct_f_card_form_div_select_multiple_3']; ?>>
              <?php $__i = 0; foreach ( $r['rep_option_6'] as $it ) : if ( $__i ++ ) { echo '
              '; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n            "; ?></select>
          </div>

          <div class="ct-f-field ct-f-grow">
            <label for="ctGenMessage"><?php echo $c['c_ct_f_field_ct_f_grow_label_text']; ?></label>
            <textarea id="ctGenMessage" name="<?php echo $c['c_ct_f_field_ct_f_grow_textarea_name']; ?>" rows="<?php echo $c['c_ct_f_field_ct_f_grow_textarea_rows']; ?>" placeholder="<?php echo $c['c_ct_f_field_ct_f_grow_textarea_placeholder']; ?>"<?php echo $c['c_ct_f_field_ct_f_grow_textarea_required']; ?><?php echo $c['c_ct_f_field_ct_f_grow_textarea_disabled']; ?><?php echo $c['c_ct_f_field_ct_f_grow_textarea_readonly']; ?>></textarea>
          </div>

          <label class="ct-f-consent" for="ctGenConsent">
            <input type="<?php echo $c['c_ct_f_card_form_label_input_type_3']; ?>" id="ctGenConsent" name="<?php echo $c['c_ct_f_card_form_label_input_name_3']; ?>"<?php echo $c['c_ct_f_card_form_label_input_required_3']; ?><?php echo $c['c_ct_f_card_form_label_input_disabled_3']; ?><?php echo $c['c_ct_f_card_form_label_input_readonly_3']; ?><?php echo $c['c_ct_f_card_form_label_input_checked_3']; ?>>
            <span><?php echo $c['c_ct_f_card_form_label_span_text_3']; ?> <a href="<?php echo $c['c_ct_f_card_form_label_span_a_href_2']; ?>" target="<?php echo $c['c_ct_f_card_form_label_span_a_target_2']; ?>" rel="<?php echo $c['c_ct_f_card_form_label_span_a_rel_2']; ?>"><?php echo $c['c_ct_f_card_form_label_span_a_text_2']; ?></a>. <span class="ct-f-flag"><?php echo $c['c_ct_f_card_form_label_span_span_text_3']; ?></span></span>
          </label>

          <button type="<?php echo $c['c_ct_f_card_form_button_type_2']; ?>" class="ct-f-btn is-secondary" id="ctGeneralBtn"<?php echo $c['c_ct_f_card_form_button_disabled_2']; ?>><?php echo $c['c_ct_f_card_form_button_text_2']; ?></button>
        </form>
      </div>

    </div>
  </div>
</section>
