<?php
/**
 * Contact Hero -- render template.
 *
 * GENERATED by tools/uew from contact/section-01-hero.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — CONTACT — SECTION 01: HERO
=================================================================
  Built from "Mockups (footer, contact)/Umoya_Contact_Page_Mockup.html".
  Layout and copy follow the mockup exactly; its fonts and sampled
  hex values do NOT come across — the routing doc is explicit that
  "the colors used in the mockup are illustrative", so this uses
  font-family: inherit and the brand palette only.

  A short centred header rather than a full-bleed image hero: the
  page's job is to get someone into a form, and every scroll before
  the first field is a cost. Anchors #ct-plan / #ct-general are
  reachable from the nav or from a campaign link.

  ELEMENTOR: place after shared/section-00-nav.html on /contact/.
  BRAND: font-family: inherit; palette tokens only. ES5 IIFE.
=================================================================
-->
<section id="umoya-contact-hero" aria-labelledby="ct-hero-title">
  <div class="ct-hero-c">
    <span class="ct-hero-eye ct-hero-rv"><?php echo $c['eyebrow_text']; ?></span>
    <h1 class="ct-hero-ttl ct-hero-rv" id="ct-hero-title"><?php echo $c['title_text']; ?></h1>
    <hr class="ct-hero-rule ct-hero-rv d1">
    <p class="ct-hero-lead ct-hero-rv d1"><?php echo $c['text_text']; ?></p>
  </div>
</section>
