<?php
/**
 * FC Our Approach -- render template.
 *
 * GENERATED by tools/uew from founders-circle-revamp/section-08-our-approach.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA FOUNDER'S CIRCLE — SECTION 06: WHY UMOYA AFRIKA TOURS
=================================================================
  ELEMENTOR USAGE:
  • v4 order: place after the Founding Offer (Section 05A).
  • Layout: two-column — "Our Approach" copy left, brand video right.
  • VIDEO: currently wired to umoya_hd_optimized_720.mp4 — swap the
    <video> src for the final brand film when it is ready.
=================================================================
-->
  <section id="fc-why" aria-label="<?php echo $c['section_aria_label']; ?>">
    <div class="fc-why-wrap">

      <!-- Two-column grid -->
      <div class="fc-why-grid">

        <!-- ── LEFT: Philosophy copy ───────────────── -->
        <div class="fc-why-rev">
          <span class="fc-why-eyebrow"><?php echo $c['eyebrow_our_approach_text']; ?></span>
          <h2 class="fc-why-title"><?php echo $c['title_a_new_company_built_on_lon_text']; ?></h2>
          <span class="fc-why-rule" aria-hidden="true"></span>

          <p class="fc-why-lead"><?php echo $c['lead_it_is_built_on_people_we_kn_text']; ?></p>

          <?php $__i = 0; foreach ( $r['rep_p_fc_why_body'] as $it ) : if ( $__i ++ ) { echo '

          '; } ?><p class="fc-why-body <?php echo $it['_uew_item_class']; ?>"><?php echo $it['body_markup']; ?></p><?php endforeach; echo "\n          "; ?><a href="<?php echo $c['button_travel_with_us_href']; ?>" class="fc-why-btn"><?php echo $c['button_travel_with_us_text']; ?></a>
        </div>

        <!-- ── RIGHT: Video + CTA ─────────────────── -->
        <div class="fc-why-aside fc-why-rev fc-d2">

          <!-- Video block -->
          <div class="fc-vid-wrap">
            <button class="fc-vid-ph" type="<?php echo $c['video_placeholder_type']; ?>" aria-label="<?php echo $c['video_placeholder_aria_label']; ?>" aria-haspopup="dialog" aria-controls="fc-why-video-modal">
              <span class="fc-play" aria-hidden="true">
                <svg viewBox="0 0 24 24"><polygon points="5 3 19 12 5 21 5 3"/></svg>
              </span>
            </button>
          </div>

        </div>

      </div><!-- /.fc-why-grid -->


    </div>
    <div class="fc-video-modal" id="fc-why-video-modal" role="dialog" aria-modal="true" aria-label="<?php echo $c['modal_aria_label']; ?>" hidden>
      <div class="fc-video-backdrop" data-fc-video-close></div>
      <div class="fc-video-dialog">
        <button class="fc-video-close" type="<?php echo $c['close_type']; ?>" aria-label="<?php echo $c['close_aria_label']; ?>" data-fc-video-close>
          <span aria-hidden="true"><?php echo $c['span_text']; ?></span>
        </button>
        <video
          class="fc-video-player"
          src="<?php echo $c['player_src']; ?>"
          preload="<?php echo $c['player_preload']; ?>"
          controls
          controlsList="nodownload"
          playsinline
          aria-label="<?php echo $c['player_aria_label']; ?>">
        </video>
      </div>
    </div>
  </section>
