<?php
/**
 * FC Closing CTA -- render template.
 *
 * GENERATED by tools/uew from founders-circle-revamp/section-11-closing-cta.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA FOUNDER'S CIRCLE — SECTION 11: CLOSING CTA
=================================================================
  "Speak With a Travel Expert" closing (mockup-aligned, v5).
  Centered BROWN section with a transparent outline button that
  fills on hover. Final section before the footer.
  ANCHOR: id="fc-cta" preserved.

  NOTE: this file had been accidentally overwritten with a copy of
  the Travel Essentials section (#fc-details) on 2026-07-10; the
  closing CTA is restored here, with the background set to brown
  per Feedback v5 ("keep the background brown").
=================================================================
-->
<section id="fc-cta" aria-label="<?php echo $c['c_section_aria_label']; ?>">
  <div class="fc-cta-c fc-cta-rv">
    <span class="fc-cta-eye"><?php echo $c['c_fc_cta_eye_text']; ?></span>
    <h2 class="fc-cta-h2"><?php echo $c['c_fc_cta_h2_text']; ?></h2>
    <p class="fc-cta-lead"><?php echo $c['c_fc_cta_lead_text']; ?></p>
    <a href="<?php echo $c['c_fc_cta_btn_href']; ?>" class="fc-cta-btn"><?php echo $c['c_fc_cta_btn_text']; ?></a>
  </div>
</section>
