<?php
/**
 * FC Founding Offer -- render template.
 *
 * GENERATED by tools/uew from founders-circle-revamp/section-07-founding-offer.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA FOUNDER'S CIRCLE — SECTION 05A: THE FOUNDING OFFER
=================================================================
  v4 revamp — brown "Founding Offer" break (mockup-aligned).
  Pricing is intentionally NOT shown here: it is held for a
  personal consultation. Place immediately after the Early Access
  (Be Among the First) section.
  ANCHOR: id="fc-pricing" preserved.
=================================================================
-->
<section id="fc-pricing" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="fc-pri-wrap fc-pri-rv">
    <span class="fc-pri-eye"><?php echo $c['eyebrow_text']; ?></span>
    <h2 class="fc-pri-ttl"><?php echo $c['title_text']; ?></h2>
    <p class="fc-pri-body"><?php echo $c['text_text']; ?></p>
    <a href="<?php echo $c['button_href']; ?>" class="fc-pri-btn"><?php echo $c['button_text']; ?></a>
    <p class="fc-pri-mini"><?php echo $c['text_text_2']; ?></p>
  </div>
</section>
