<?php
/**
 * FC Inquiry Form -- render template.
 *
 * GENERATED by tools/uew from founders-circle-revamp/section-04-inquiry-form.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA FOUNDER'S CIRCLE — SECTION 02: FORM — YOUR HOMECOMING
  Layout  : 100dvh · Grid 1fr / 2fr · no overflow anywhere
  Strategy: clamp()+vh units scale all spacing proportionally.
           Right col is a flex column — card grows to fill space.
           Inside the card: 7-row grid where the textarea row
           is 1fr so it absorbs all leftover height naturally.
           No scrollbars. No overflow. Fits at every viewport ≥768px.
=================================================================
  ELEMENTOR: HTML widget directly below Section 01 (Hero).
  id="fc-form-section" is the anchor for all CTA buttons.
  HUBSPOT: Form keeps the custom visual design and submits through
           HubSpot's Forms API once Portal ID and Form ID are added.
=================================================================
-->
<section id="fc-form-section" aria-label="<?php echo $c['section_aria_label']; ?>">

  <div class="fc-f2-outer">

    <!-- =========================================================
         LEFT — Image panel (1fr)
         Fills the full 100dvh height via position:absolute+inset:0.
         overflow:hidden clips the image to the column — structural only.
         Text is bottom-center aligned.
         ========================================================= -->
    <div class="fc-f2-img-col" aria-hidden="true">
      <img
        src="<?php echo $c['image_src']; ?>"
        alt="<?php echo $c['image_alt']; ?>"
      />
      <div class="fc-f2-img-ov"></div>
      <div class="fc-f2-img-txt">
        <span class="fc-f2-img-eye"><?php echo $c['eyebrow_inquiry_form_text']; ?></span>
        <h2 class="fc-f2-img-ttl"><?php echo $c['title_your_umoya_experience_awaits_text']; ?></h2>
        <span class="fc-f2-img-rule"></span>
      </div>
    </div>

    <!-- =========================================================
         RIGHT — Form panel (2fr)
         Flex column. Card grows. Textarea absorbs leftover height.
         No overflow property on this column.
         ========================================================= -->
    <div class="fc-f2-form-col">
      <div class="fc-f2-inner">

        <!-- SECTION HEADER -->
        <div class="fc-f2-hd fc-f2-rv">
          <span class="fc-f2-eye"><?php echo $c['eyebrow_reserve_your_place_text']; ?></span>
          <h2 class="fc-f2-ttl"><?php echo $c['title_begin_your_journey_text']; ?></h2>
          <span class="fc-f2-rule" aria-hidden="true"></span>
          <p class="fc-f2-sub"><?php echo $c['subtitle_tell_us_about_yourself_and_text']; ?></p>
        </div>

        <!-- FORM CARD -->
        <div class="fc-f2-card fc-f2-rv d1">

          <!--
            HUBSPOT INTEGRATION:
            Paste the HubSpot Portal ID and Form GUID into the data attributes
            on this form. The JavaScript below maps each visible input to the
            HubSpot property names used by the published HubSpot form.
          -->
          <form
            data-hs-do-not-collect="<?php echo $c['form_data_hs_do_not_collect']; ?>"
            class="fc-f2-form"
            id="fc2Form"
            action="<?php echo $c['form_action']; ?>"
            method="<?php echo $c['form_method']; ?>"
            target="<?php echo $c['form_target']; ?>"
            novalidate
            aria-label="<?php echo $c['form_aria_label']; ?>"
            data-hubspot-portal-id="<?php echo $c['form_data_hubspot_portal_id']; ?>"
            data-hubspot-form-id="<?php echo $c['form_data_hubspot_form_id']; ?>"
            data-umoya-form-source="<?php echo $c['form_data_umoya_form_source']; ?>"
            data-wordpress-backup-endpoint="<?php echo $c['form_data_wordpress_backup_endpoint']; ?>"
            data-hubspot-consent-text="<?php echo $c['form_data_hubspot_consent_text']; ?>"
          >
            <?php $__i = 0; foreach ( $r['rep_input'] as $it ) : if ( $__i ++ ) { echo '
            '; } ?><input type="<?php echo $it['type']; ?>" name="<?php echo $it['name']; ?>" value="<?php echo $it['value']; ?>" class="<?php echo $it['_uew_item_class']; ?>"><?php endforeach; echo "\n\n            "; ?><div class="fc-f2-fg">

              <!-- Row 1: Title | spacer -->
              <div class="fc-f2-field">
                <label for="fc2Title"><?php echo $c['label_title_text']; ?></label>
                <select id="fc2Title" name="<?php echo $c['select_name']; ?>">
                  <?php $__i = 0; foreach ( $r['rep_option'] as $it ) : if ( $__i ++ ) { echo '
                  '; } ?><option value="<?php echo $it['value']; ?>"<?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n                "; ?></select>
              </div>
              <div aria-hidden="true"></div>

              <!-- Row 2: First Name | Last Name -->
              <div class="fc-f2-field">
                <label for="fc2First"><?php echo $c['label_text']; ?> <span class="fc-f2-req" aria-hidden="true"><?php echo $c['required_text']; ?></span></label>
                <input type="<?php echo $c['input_type']; ?>" id="fc2First" name="<?php echo $c['input_name']; ?>" placeholder="<?php echo $c['input_placeholder']; ?>" required autocomplete="<?php echo $c['input_autocomplete']; ?>" />
              </div>
              <div class="fc-f2-field">
                <label for="fc2Last"><?php echo $c['label_text_2']; ?> <span class="fc-f2-req" aria-hidden="true"><?php echo $c['required_text_2']; ?></span></label>
                <input type="<?php echo $c['input_type_2']; ?>" id="fc2Last" name="<?php echo $c['input_name_2']; ?>" placeholder="<?php echo $c['input_placeholder_2']; ?>" required autocomplete="<?php echo $c['input_autocomplete_2']; ?>" />
              </div>

              <!-- Row 3: Email | Phone -->
              <div class="fc-f2-field">
                <label for="fc2Email"><?php echo $c['label_text_3']; ?> <span class="fc-f2-req" aria-hidden="true"><?php echo $c['required_text_3']; ?></span></label>
                <input type="<?php echo $c['input_type_3']; ?>" id="fc2Email" name="<?php echo $c['input_name_3']; ?>" placeholder="<?php echo $c['input_placeholder_3']; ?>" required autocomplete="<?php echo $c['input_autocomplete_3']; ?>" />
              </div>
              <div class="fc-f2-field">
                <label for="fc2Phone"><?php echo $c['label_phone_number_text']; ?></label>
                <input type="<?php echo $c['input_type_4']; ?>" id="fc2Phone" name="<?php echo $c['input_name_4']; ?>" placeholder="<?php echo $c['input_placeholder_4']; ?>" autocomplete="<?php echo $c['input_autocomplete_4']; ?>" />
              </div>

              <!-- Row 4: Country | City -->
              <div class="fc-f2-field">
                <label for="fc2Country"><?php echo $c['label_text_4']; ?> <span class="fc-f2-req" aria-hidden="true"><?php echo $c['required_text_4']; ?></span></label>
                <select id="fc2Country" name="<?php echo $c['select_name_2']; ?>" required>
                  <?php $__i = 0; foreach ( $r['rep_option_2'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n                "; ?></select>
              </div>
              <div class="fc-f2-field">
                <label for="fc2City"><?php echo $c['label_city_text']; ?></label>
                <input type="<?php echo $c['input_type_5']; ?>" id="fc2City" name="<?php echo $c['input_name_5']; ?>" placeholder="<?php echo $c['input_placeholder_5']; ?>" autocomplete="<?php echo $c['input_autocomplete_5']; ?>" />
              </div>

              <!-- Row 5: When are you hoping to travel — Month + Year side by side -->
              <div class="fc-f2-field fc-f2-span">
                <label for="fc2Month"><?php echo $c['label_when_are_you_hoping_to_trav_text']; ?></label>
                <div class="fc-f2-when">
                  <select id="fc2Month" name="<?php echo $c['select_name_3']; ?>" aria-label="<?php echo $c['select_aria_label']; ?>">
                    <?php $__i = 0; foreach ( $r['rep_option_3'] as $it ) : if ( $__i ++ ) { echo '
                    '; } ?><option value="<?php echo $it['value']; ?>"<?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n                  "; ?></select>
                  <select id="fc2Year" name="<?php echo $c['select_name_4']; ?>" aria-label="<?php echo $c['select_aria_label_2']; ?>">
                    <?php $__i = 0; foreach ( $r['rep_option_4'] as $it ) : if ( $__i ++ ) { echo '
                    '; } ?><option value="<?php echo $it['value']; ?>"<?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n                  "; ?></select>
                </div>
              </div>

              <!-- Row 6: How many guests will be traveling — full width -->
              <div class="fc-f2-field fc-f2-span">
                <label for="fc2Guests"><?php echo $c['label_how_many_guests_will_be_tra_text']; ?></label>
                <select id="fc2Guests" name="<?php echo $c['select_name_5']; ?>">
                  <?php $__i = 0; foreach ( $r['rep_option_5'] as $it ) : if ( $__i ++ ) { echo '
                  '; } ?><option value="<?php echo $it['value']; ?>"<?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n                "; ?></select>
              </div>

              <!-- Row 7: Textarea — full width, 1fr row, fills leftover height -->
              <div class="fc-f2-field fc-f2-span-grow">
                <label for="fc2Why"><?php echo $c['label_what_are_you_hoping_to_expe_text']; ?></label>
                <textarea
                  id="fc2Why"
                  name="<?php echo $c['textarea_name']; ?>"
                  placeholder="<?php echo $c['textarea_placeholder']; ?>"
                ></textarea>
              </div>

            </div><!-- /.fc-f2-fg -->

            <!-- Consent (POPIA) — required box must be ticked; not pre-checked -->
            <div class="fc-f2-consent">
              <?php $__i = 0; foreach ( $r['rep_label_fc_f2_consent_item'] as $it ) : if ( $__i ++ ) { echo '
              '; } ?><label class="fc-f2-consent-item <?php echo $it['_uew_item_class']; ?>" for="<?php echo $it['for']; ?>">
                <input type="<?php echo $it['type']; ?>" id="<?php echo $it['id']; ?>" name="<?php echo $it['name']; ?>" value="<?php echo $it['value']; ?>"<?php echo $it['aria_required']; ?> />
                <span><?php echo $it['span_markup']; ?></span>
              </label><?php endforeach; echo "\n            "; ?></div>

            <!-- Submit -->
            <div class="fc-f2-submit">
              <button type="<?php echo $c['subtitle_button_request_your_founder_s_circ_type']; ?>" class="fc-f2-sub-btn" id="fc2Btn">
                <?php echo $c['subtitle_button_request_your_founder_s_circ_text']; echo "\n              "; ?></button>
            </div>

            <!-- Legal -->
            <p class="fc-f2-legal">
              <?php echo $c['legal_your_information_is_held_in_text']; echo "\n            "; ?></p>

          </form>
          <iframe name="umoyaSubmissionFrame" title="<?php echo $c['iframe_title']; ?>" style="<?php echo $s['iframe_inline_style']; ?>"></iframe>

        </div><!-- /.fc-f2-card -->

      </div><!-- /.fc-f2-inner -->
    </div><!-- /.fc-f2-form-col -->

  </div><!-- /.fc-f2-outer -->

</section>
