<?php
/**
 * FC Invitation -- render template.
 *
 * GENERATED by tools/uew from founders-circle-revamp/section-02-invitation.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!-- ============================================================
  UMOYA FOUNDER'S CIRCLE — SECTION 2: INTRO STATEMENT
============================================================ -->
<section id="fc-intro" aria-label="<?php echo $c['c_section_aria_label']; ?>">
  <div class="fc-intro-wrap">

    <!-- Decorative line draws the eye down -->
    <div class="fc-dec-line fc-intro-rv fc-d0" aria-hidden="true"></div>

    <span class="fc-intro-eyebrow fc-intro-rv fc-d1"><?php echo $c['c_fc_intro_eyebrow_text']; ?></span>

    <h2 class="fc-intro-heading fc-intro-rv fc-d2">
      <?php echo $c['c_fc_intro_heading_text']; echo "\n    "; ?></h2>

    <p class="fc-intro-body fc-intro-rv fc-d3">
      <?php echo $c['c_fc_intro_body_text']; echo "\n    "; ?></p>

    <div class="fc-intro-rv fc-d4" style="<?php echo $s['c_fc_d4_fc_intro_rv_inline_style']; ?>">
      <a href="<?php echo $c['c_fc_intro_btn_href']; ?>" class="fc-intro-btn"><?php echo $c['c_fc_intro_btn_text']; ?></a>
    </div>

  </div>
</section>
