<?php
/**
 * FC Journey -- render template.
 *
 * GENERATED by tools/uew from founders-circle-revamp/section-05-journey.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA FOUNDER'S CIRCLE — SECTION 05: YOUR JOURNEY BEGINS HERE
=================================================================
  v4 revamp — flat editorial cards.
  • White journey band with CREAM (--cream) framed-photo cards
  • Divider, then a full-width CREAM extensions band with WHITE cards
    on a single row (centered header left, cards right)
  • Cards are flat: no shadow, no radius, no hover; a terracotta rule
    runs down the left edge; the photo is matted inside the card.
  • Header layout matches section-05-journey-interactive-map-image.html
    (title left · stats right; bordered stat bar on mobile).

  BRAND COLOURS ONLY: --cream (#F5F0EB), --white (#FFFFFF),
  --brown (#4B2E2B), --terra (#D97E53). Text hierarchy uses opacity
  tints of the brand brown; no non-brand colours are introduced.
  Card titles + section headings are real <h2>/<h3> so they inherit
  the theme's header (serif) font.
  ANCHOR: id="fc-journey" is the nav target — do not change.
=================================================================
-->
<section id="fc-journey" aria-label="<?php echo $c['section_aria_label']; ?>">

  <!-- ════ White band: header + immersive chapters ════ -->
  <div class="fc-jrn-top">
    <div class="fc-jrn-c">

      <!-- Header row: title left · stats right -->
      <div class="fc-jrn-hd">
        <div>
          <span class="fc-jrn-eye"><?php echo $c['eyebrow_text']; ?></span>
          <h2 class="fc-jrn-ttl"><?php echo $c['title_text']; ?></h2>
        </div>
        <div class="fc-jrn-stats" role="list">
          <?php $__i = 0; foreach ( $r['rep_div_fc_jrn_stat'] as $it ) : if ( $__i ++ ) { echo '
          '; } ?><div class="fc-jrn-stat <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['role']; ?>">
            <div class="fc-jrn-stat-n"><?php echo $it['stat_n']; ?></div>
            <div class="fc-jrn-stat-l" data-short="<?php echo $it['data_short']; ?>"><?php echo $it['stat_l']; ?></div>
          </div><?php endforeach; echo "\n        "; ?></div>
      </div>

      <p class="fc-jrn-lead"><?php echo $c['text_text']; ?></p>

      <!-- Immersive-chapter cards (cream) -->
      <div class="fc-jrn-grid">

        <!-- Chapter I -->
        <?php $__i = 0; foreach ( $r['rep_article_fc_jrn_tile'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><article class="fc-jrn-tile <?php echo $it['_uew_item_class']; ?>">
          <div class="fc-jrn-tile-img"><?php echo $it['tile_img_markup']; ?></div>
          <div class="fc-jrn-tile-body">
            <span class="fc-jrn-loc"><?php echo $it['loc']; ?></span>
            <p class="fc-jrn-desc"><?php echo $it['desc_markup']; ?></p>
          </div>
        </article><?php endforeach; echo "\n\n      "; ?></div>

      <!-- Divider between chapters and optional extensions -->
      <hr class="fc-jrn-divider" aria-hidden="true" />

    </div>
  </div>

  <!-- ════ Cream band: optional extensions (white cards) ════ -->
  <div class="fc-jrn-ext">
    <div class="fc-jrn-c">
      <div class="fc-jrn-ext-row">

        <div class="fc-jrn-ext-head">
          <span class="fc-jrn-eye"><?php echo $c['eyebrow_text_2']; ?></span>
          <h2 class="fc-jrn-subhead"><?php echo $c['heading_text']; ?></h2>
        </div>

        <div class="fc-jrn-grid-2">

          <!-- Extension 1 — Victoria Falls -->
          <?php $__i = 0; foreach ( $r['rep_article_fc_jrn_tile_2'] as $it ) : if ( $__i ++ ) { echo '

          <!-- Extension 2 — Chobe -->
          '; } ?><article class="fc-jrn-tile <?php echo $it['_uew_item_class']; ?>">
            <div class="fc-jrn-tile-img">
              <!--<?php echo $it['note']; ?>-->
              <img class="fc-jrn-pic" src="<?php echo $it['src']; ?>" alt="<?php echo $it['alt']; ?>" loading="<?php echo $it['loading']; ?>" />
              <div class="fc-jrn-tag">
                <h3 class="fc-jrn-tile-ttl"><?php echo $it['tile_ttl']; ?></h3>
              </div>
            </div>
            <div class="fc-jrn-tile-body">
              <span class="fc-jrn-loc"><?php echo $it['loc']; ?></span>
              <p class="fc-jrn-desc"><?php echo $it['desc']; ?></p>
            </div>
          </article><?php endforeach; echo "\n\n        "; ?></div>
      </div>
    </div>
  </div>

</section>
