<?php
/**
 * FC Navigation -- render template.
 *
 * GENERATED by tools/uew from founders-circle-revamp/section-00-nav.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA FOUNDER'S CIRCLE — SECTION 00: STICKY NAVIGATION
=================================================================
  BEHAVIOUR:
  • Renders as a normal in-flow element directly below the hero
  • When user scrolls and the bar reaches the top of the viewport,
    it pins there — position: sticky; top: 0
  • No show/hide animation. No IntersectionObserver on the hero.
    The browser handles the stick natively and performantly.

  IMPORTANT — ELEMENTOR:
  • This widget must be placed immediately AFTER the hero widget
    (Section 01.1) in the Elementor panel — not before it.
  • Do NOT wrap this widget in an Elementor section that has
    overflow: hidden — that will break sticky positioning.
  • The Elementor section container for this widget should have
    no top/bottom padding and no background colour set.

  STRUCTURE:
  • Logo         — left, links to main site
  • Nav links    — centre, 6 section anchors with active state
  • CTA button   — right, anchors to form
  • Hamburger    — mobile only, opens dropdown inside the nav bar
=================================================================
-->
  <!-- ── NAV BAR (sticky) ──────────────────────────────────────── -->
  <nav id="fcNavBar" aria-label="<?php echo $c['section_aria_label']; ?>">

    <div class="fc-nav-inner">

      <!-- Logo -->
      <a class="fc-nav-logo" href="<?php echo $c['logo_href']; ?>" aria-label="<?php echo $c['logo_aria_label']; ?>">
        <img
          src="<?php echo $c['image_src']; ?>"
          alt="<?php echo $c['image_alt']; ?>"
          onerror="this.style.display='none';document.getElementById('fcNLT').style.display='inline';"
        />
        <span class="fc-nav-logo-text" id="fcNLT" style="<?php echo $s['text_inline_style']; ?>"><?php echo $c['text_text']; ?></span>
      </a>

      <!-- Desktop section links -->
      <ul class="fc-nav-links" role="list">
        <?php $__i = 0; foreach ( $r['rep_li_fc_nav_item'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><li class="fc-nav-item <?php echo $it['_uew_item_class']; ?>" data-s="<?php echo $it['data_s']; ?>">
          <a class="fc-nav-link" href="<?php echo $it['href']; ?>"><?php echo $it['link']; ?></a>
        </li><?php endforeach; echo "\n      "; ?></ul>

      <!-- Desktop CTA -->
      <a class="fc-nav-cta" href="<?php echo $c['button_href']; ?>"><?php echo $c['button_text']; ?></a>

      <!-- Hamburger -->
      <button
        class="fc-nav-burger"
        id="fcNavBurger"
        aria-label="<?php echo $c['button_aria_label']; ?>"
        aria-expanded="false"
        aria-controls="fcNavDropdown"<?php echo $c['button_disabled']; echo "\n      "; ?>>
        <span></span>
        <span></span>
        <span></span>
      </button>

      <!-- Mobile dropdown — inside the nav so it follows sticky position -->
      <div class="fc-nav-dropdown" id="fcNavDropdown" role="menu" aria-label="<?php echo $c['container_aria_label']; ?>">

        <ul class="fc-nav-dropdown-list" role="list">
          <?php $__i = 0; foreach ( $r['rep_li_fc_nav_dropdown_item'] as $it ) : if ( $__i ++ ) { echo '
          '; } ?><li class="fc-nav-dropdown-item <?php echo $it['_uew_item_class']; ?>" data-s="<?php echo $it['data_s']; ?>">
            <a class="fc-nav-dropdown-link" href="<?php echo $it['href']; ?>" role="<?php echo $it['role']; ?>"><?php echo $it['dropdown_link']; ?></a>
          </li><?php endforeach; echo "\n        "; ?></ul>

        <div class="fc-nav-dropdown-cta-row">
          <a class="fc-nav-dropdown-cta" href="<?php echo $c['button_href_2']; ?>"><?php echo $c['button_text_2']; ?></a>
        </div>

      </div><!-- /.fc-nav-dropdown -->

    </div><!-- /.fc-nav-inner -->

  </nav>
