<?php
/**
 * FC Membership Privileges -- render template.
 *
 * GENERATED by tools/uew from founders-circle-revamp/section-03-membership-privileges.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA FOUNDER'S CIRCLE — SECTION 04: MEMBER BENEFITS
=================================================================
  ELEMENTOR USAGE:
  • Add an "HTML" widget after Section 03.
  • This is the page's only dark-brown section — it provides
    tonal contrast between the surrounding cream sections.
  • IMAGE: Hosted on the Umoya site for reliable loading.
  • The checklist uses a terracotta circle check icon per item.
=================================================================
-->
  <section id="fc-benefits" aria-label="<?php echo $c['section_aria_label']; ?>">
    <div class="fc-ben-wrap">
      <div class="fc-ben-grid">

        <!-- ── COPY + CHECKLIST (left) ────────────── -->
        <div class="fc-ben-reveal">
          <span class="fc-ben-eyebrow"><?php echo $c['eyebrow_text']; ?></span>
          <h2 class="fc-ben-title"><?php echo $c['title_text']; ?></h2>
          <span class="fc-ben-rule" aria-hidden="true"></span>

          <ul class="fc-ben-list" aria-label="<?php echo $c['list_aria_label']; ?>">

            <?php $__i = 0; foreach ( $r['rep_li'] as $it ) : if ( $__i ++ ) { echo '

            '; } ?><li class="<?php echo $it['_uew_item_class']; ?>">
              <span class="fc-chk" aria-hidden="<?php echo $it['aria_hidden']; ?>">
                <svg viewBox="<?php echo $it['viewbox']; ?>"><polyline points="<?php echo $it['icon_points']; ?>"/></svg>
              </span>
              <?php echo $it['li']; echo "\n            "; ?></li><?php endforeach; echo "\n\n          "; ?></ul>

          <a href="<?php echo $c['button_href']; ?>" class="fc-ben-btn"><?php echo $c['button_text']; ?></a>
        </div>

        <!-- ── IMAGE (right) ──────────────────────── -->
        <div class="fc-ben-photo fc-ben-reveal fc-d1">
          <img
            src="<?php echo $c['image_src']; ?>"
            alt="<?php echo $c['image_alt']; ?>"
            loading="<?php echo $c['image_loading']; ?>"
          />
        </div>

      </div>
    </div>
  </section>
