<?php
/**
 * FC Why Umoya -- render template.
 *
 * GENERATED by tools/uew from founders-circle-revamp/section-09-why-umoya.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA FOUNDER'S CIRCLE — SECTION 06B: BRAND PILLARS
=================================================================
  ELEMENTOR USAGE:
  • Add an "HTML" widget after Section 06 (Why Umoya).
  • Layout: full-bleed background image with four text columns
    anchored to the bottom of the section.
  • Mobile: horizontal infinite-swipe carousel with partial
    column visibility to invite scrolling.
=================================================================
-->
<section id="fc-pillars" aria-label="<?php echo $c['section_aria_label']; ?>">

  <!-- Background image -->
  <div class="fc-pil-bg" aria-hidden="true">
    <img src="<?php echo $c['image_src']; ?>"
         alt="<?php echo $c['image_alt']; ?>" loading="<?php echo $c['image_loading']; ?>" />
  </div>

  <!-- Content -->
  <div class="fc-pil-content">
    <div class="fc-pil-header">
      <h2 class="fc-pil-heading"><?php echo $c['title_text']; ?></h2>
    </div>
    <div class="fc-pil-grid" role="list">

      <div class="fc-pil-col fc-pil-rv" role="listitem">
        <h3 class="fc-pil-title"><?php echo $c['title_text_2']; ?></h3>
        <p class="fc-pil-body"><?php echo $c['text_text']; ?></p>
      </div>

      <div class="fc-pil-col fc-pil-rv d1" role="listitem">
        <h3 class="fc-pil-title"><?php echo $c['title_text_3']; ?></h3>
        <p class="fc-pil-body"><?php echo $c['text_text_2']; ?></p>
      </div>

      <div class="fc-pil-col fc-pil-rv d2" role="listitem">
        <h3 class="fc-pil-title"><?php echo $c['title_text_4']; ?></h3>
        <p class="fc-pil-body"><?php echo $c['text_text_3']; ?></p>
      </div>

      <div class="fc-pil-col fc-pil-rv d3" role="listitem">
        <h3 class="fc-pil-title"><?php echo $c['title_text_5']; ?></h3>
        <p class="fc-pil-body"><?php echo $c['text_text_4']; ?></p>
      </div>

    </div>
  </div>

</section>
