<?php
/**
 * Groups Hero -- render template.
 *
 * GENERATED by tools/uew from for-groups/section-01-hero.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — FOR GROUPS — SECTION 01: HERO
=================================================================
  Full-bleed image hero, left-aligned content (per the mockup).

  ANCHOR: id="fg-hero" — first content widget after the site nav.
  IMAGE: extracted from the client mockup and uploaded to the
  Umoya CDN (umoya_groups_hero.jpg).
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="fg-hero" aria-label="<?php echo $c['section_aria_label']; ?>">

  <div class="fg-h-bg">
    <img
      src="<?php echo $c['image_src']; ?>"
      alt="<?php echo $c['image_alt']; ?>"
    />
  </div>

  <div class="fg-h-content">
    <span class="fg-h-eye"><?php echo $c['eyebrow_text']; ?></span>
    <h1 class="fg-h-title"><?php echo $c['title_text']; ?></h1>
    <p class="fg-h-sub"><?php echo $c['subtitle_text']; ?></p>
    <div class="fg-h-btns">
      <a href="<?php echo $c['button_href']; ?>" class="fg-h-btn fg-h-btn-primary">
        <?php echo $c['button_text']; echo "\n        "; ?><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" aria-hidden="true">
          <line x1="5" y1="12" x2="19" y2="12"/>
          <polyline points="13 6 19 12 13 18"/>
        </svg>
      </a>
      <a href="<?php echo $c['button_href_2']; ?>" class="fg-h-btn fg-h-btn-ghost"><?php echo $c['button_text_2']; ?></a>
    </div>
  </div>

</section>
