<?php
/**
 * Groups Planning Steps -- render template.
 *
 * GENERATED by tools/uew from for-groups/section-05-how-it-works.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — FOR GROUPS — SECTION 05: PLANNING FOR YOUR GROUP
=================================================================
  Four numbered steps, from first enquiry to arrival.

  ANCHOR: id="fg-how"
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="fg-how" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="fg-hw-c">

    <div class="fg-hw-head fg-hw-rv">
      <span class="fg-hw-eye"><?php echo $c['eyebrow_text']; ?></span>
      <h2 class="fg-hw-ttl"><?php echo $c['title_text']; ?></h2>
    </div>

    <div class="fg-hw-steps" role="list">

      <?php $__i = 0; foreach ( $r['rep_div_fg_hw_step'] as $it ) : if ( $__i ++ ) { echo '

      '; } ?><div class="<?php echo 'fg-hw-step fg-hw-rv d' . $it['_uew_n']; ?> <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['role']; ?>">
        <div class="fg-hw-n"><?php echo $it['n']; ?></div>
        <h3 class="fg-hw-h"><?php echo $it['h']; ?></h3>
        <p class="fg-hw-p"><?php echo $it['p']; ?></p>
      </div><?php endforeach; echo "\n\n    "; ?></div>
  </div>
</section>
