<?php
/**
 * Groups Intro -- render template.
 *
 * GENERATED by tools/uew from for-groups/section-02-intro.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — FOR GROUPS — SECTION 02: INTRO
=================================================================
  Centred editorial intro on cream.
  ANCHOR: id="fg-intro"
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="fg-intro" aria-label="<?php echo $c['c_section_aria_label']; ?>">
  <div class="fg-in-c fg-in-rv">
    <span class="fg-in-eye"><?php echo $c['c_fg_in_eye_text']; ?></span>
    <h2 class="fg-in-ttl"><?php echo $c['c_fg_in_ttl_text']; ?></h2>
    <p class="fg-in-body"><?php echo $c['c_fg_in_body_text']; ?></p>
  </div>
</section>
