<?php
/**
 * Groups For the Organizer -- render template.
 *
 * GENERATED by tools/uew from for-groups/section-04-for-the-organizer.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — FOR GROUPS — SECTION 04: FOR THE ORGANIZER
=================================================================
  The page's dark-brown accent band — the promise made to the
  person who brings everyone along. Four icon+copy items.

  ANCHOR: id="fg-organizer"
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="fg-organizer" aria-label="<?php echo $c['c_section_aria_label']; ?>">
  <div class="fg-og-c">

    <div class="fg-og-head fg-og-rv">
      <span class="fg-og-eye"><?php echo $c['c_fg_og_eye_text']; ?></span>
      <h2 class="fg-og-ttl"><?php echo $c['c_fg_og_ttl_text']; ?></h2>
      <p class="fg-og-lead"><?php echo $c['c_fg_og_lead_text']; ?></p>
    </div>

    <div class="fg-og-grid" role="list">

      <?php $__i = 0; foreach ( $r['rep_div_fg_og_item'] as $it ) : if ( $__i ++ ) { echo '

      '; } ?><div class="<?php echo array( 'fg-og-item fg-og-rv', 'fg-og-item fg-og-rv d1', 'fg-og-item fg-og-rv d2', 'fg-og-item fg-og-rv d3' )[ ( ( (int) $it['_uew_n'] ) - 1 ) % 4 ]; ?> <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['role']; ?>">
        <span class="fg-og-ic" aria-hidden="<?php echo $it['aria_hidden']; ?>">
          <svg viewBox="<?php echo $it['viewbox']; ?>"><?php echo $it['svg_markup']; ?></svg>
        </span>
        <div>
          <h3 class="fg-og-h"><?php echo $it['h']; ?></h3>
          <p class="fg-og-p"><?php echo $it['p']; ?></p>
        </div>
      </div><?php endforeach; echo "\n\n    "; ?></div>
  </div>
</section>
