<?php
/**
 * Groups Travel Fit for Any Size -- render template.
 *
 * GENERATED by tools/uew from for-groups/section-07-sizes.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — FOR GROUPS — SECTION 07: TRAVEL FIT FOR ANY SIZE
=================================================================
  Short centred statement on how Umoya scales from a close circle
  to a full chapter (back-to-back departures).

  ANCHOR: id="fg-sizes"
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="fg-sizes" aria-label="<?php echo $c['c_section_aria_label']; ?>">
  <div class="fg-sz-c fg-sz-rv">
    <span class="fg-sz-eye"><?php echo $c['c_fg_sz_eye_text']; ?></span>
    <h2 class="fg-sz-ttl"><?php echo $c['c_fg_sz_ttl_text']; ?></h2>
    <p class="fg-sz-body"><?php echo $c['c_fg_sz_body_text']; ?></p>
  </div>
</section>
