<?php
/**
 * Groups Who Travels With Us -- render template.
 *
 * GENERATED by tools/uew from for-groups/section-03-who-travels.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — FOR GROUPS — SECTION 03: WHO TRAVELS WITH US
=================================================================
  Four photo cards covering the group types Umoya hosts.

  ANCHOR: id="fg-who"
  IMAGES: extracted from the client mockup and uploaded to the
  Umoya CDN (umoya_groups_*.jpg).
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="fg-who" aria-label="<?php echo $c['c_section_aria_label']; ?>">
  <div class="fg-wh-c">

    <div class="fg-wh-head fg-wh-rv">
      <span class="fg-wh-eye"><?php echo $c['c_fg_wh_eye_text']; ?></span>
      <h2 class="fg-wh-ttl"><?php echo $c['c_fg_wh_ttl_text']; ?></h2>
    </div>

    <div class="fg-wh-grid" role="list">

      <?php $__i = 0; foreach ( $r['rep_article_fg_wh_card'] as $it ) : if ( $__i ++ ) { echo '

      '; } ?><article class="<?php echo array( 'fg-wh-card fg-wh-rv', 'fg-wh-card fg-wh-rv d1', 'fg-wh-card fg-wh-rv d2', 'fg-wh-card fg-wh-rv d3' )[ ( ( (int) $it['_uew_n'] ) - 1 ) % 4 ]; ?> <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['role']; ?>">
        <div class="fg-wh-media"><?php echo $it['notes']; ?><img<?php echo $it['extra_attributes']; ?> src="<?php echo $it['src']; ?>" alt="<?php echo $it['alt']; ?>" loading="<?php echo $it['loading']; ?>" decoding="<?php echo $it['decoding']; ?>">
        </div>
        <div class="fg-wh-body">
          <h3 class="fg-wh-name"><?php echo $it['name']; ?></h3>
          <p class="fg-wh-desc"><?php echo $it['desc']; ?></p>
        </div>
      </article><?php endforeach; echo "\n\n    "; ?></div>
  </div>
</section>
