<?php
/**
 * Home About -- render template.
 *
 * GENERATED by tools/uew from homepage-revamp/homepage-section-02-about.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!-- UMOYA - HOMEPAGE SECTION 02: ABOUT -->
<section id="umoya-about" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="umoya-about-layout">
    <div class="umoya-about-copy">
      <div class="umoya-about-inner umoya-about-rv">
        <span class="umoya-about-eye"><?php echo $c['eyebrow_text']; ?></span>
        <h2><?php echo $c['heading_text']; ?></h2>
        <span class="umoya-about-rule" aria-hidden="true"></span>
        <div class="umoya-about-body">
          <p><?php echo $c['text_text']; ?></p>

        </div>
      </div>
    </div>

    <figure class="umoya-about-media" aria-label="<?php echo $c['figure_aria_label']; ?>">
      <img
        src="<?php echo $c['image_src']; ?>"
        alt="<?php echo $c['image_alt']; ?>"
        loading="<?php echo $c['image_loading']; ?>"
        decoding="<?php echo $c['image_decoding']; ?>"
        fetchpriority="<?php echo $c['image_fetchpriority']; ?>"
      />
    </figure>
  </div>

</section>
