<?php
/**
 * Home Navigation -- render template.
 *
 * GENERATED by tools/uew from homepage-revamp/homepage-section-00-nav.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<div id="umoyaHomepageNavMount">
  <nav id="umoyaHomepageNav" aria-label="<?php echo $c['c_nav_aria_label']; ?>">
    <div class="umoya-nav-inner">
      <a class="umoya-nav-logo" href="<?php echo $c['c_umoya_nav_logo_href']; ?>" aria-label="<?php echo $c['c_umoya_nav_logo_aria_label']; ?>">
        <img
          src="<?php echo $c['c_img_src']; ?>"
          alt="<?php echo $c['c_img_alt']; ?>"
          onerror="this.style.display='none';document.getElementById('umoyaHomeNavLogoText').style.display='inline';"
        >
        <span class="umoya-nav-logo-text" id="umoyaHomeNavLogoText" style="<?php echo $s['c_umoya_nav_logo_text_inline_style']; ?>"><?php echo $c['c_umoya_nav_logo_text_text']; ?></span>
      </a>

      <ul class="umoya-nav-links" role="list">
        <?php $__i = 0; foreach ( $r['rep_li_umoya_nav_item'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><li class="umoya-nav-item <?php echo $it['_uew_item_class']; ?>" data-section="<?php echo $it['data_section']; ?>">
          <a class="umoya-nav-link" href="<?php echo $it['href']; ?>"><?php echo $it['link']; ?></a>
        </li><?php endforeach; echo "\n      "; ?></ul>

      <a class="umoya-nav-cta" href="<?php echo $c['c_umoya_nav_cta_href']; ?>"><?php echo $c['c_umoya_nav_cta_text']; ?></a>

      <button
        class="umoya-nav-burger"
        type="<?php echo $c['c_umoya_nav_burger_type']; ?>"
        aria-label="<?php echo $c['c_umoya_nav_burger_aria_label']; ?>"
        aria-expanded="false"
        aria-controls="umoyaHomepageNavDropdown"<?php echo $c['c_umoya_nav_burger_disabled']; echo "\n      "; ?>>
        <span></span>
        <span></span>
        <span></span>
      </button>

      <div class="umoya-nav-dropdown" id="umoyaHomepageNavDropdown" aria-label="<?php echo $c['c_umoya_nav_dropdown_aria_label']; ?>">
        <ul class="umoya-nav-dropdown-list" role="list">
          <?php $__i = 0; foreach ( $r['rep_li_umoya_nav_dropdown_item'] as $it ) : if ( $__i ++ ) { echo '
          '; } ?><li class="umoya-nav-dropdown-item <?php echo $it['_uew_item_class']; ?>" data-section="<?php echo $it['data_section']; ?>">
            <a class="umoya-nav-dropdown-link" href="<?php echo $it['href']; ?>"><?php echo $it['dropdown_link']; ?></a>
          </li><?php endforeach; echo "\n        "; ?></ul>

        <div class="umoya-nav-dropdown-cta-row">
          <a class="umoya-nav-dropdown-cta" href="<?php echo $c['c_umoya_nav_dropdown_cta_href']; ?>"><?php echo $c['c_umoya_nav_dropdown_cta_text']; ?></a>
        </div>
      </div>
    </div>

  </nav>
</div>
