<?php
/**
 * Home Founder’s Circle -- render template.
 *
 * GENERATED by tools/uew from homepage-revamp/homepage-section-07-founders-circle.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<section id="umoya-founder-cta" aria-label="<?php echo $c['c_section_aria_label']; ?>">
  <div class="umoya-founder-inner">
    <div class="umoya-founder-copy">
      <span class="umoya-founder-eye"><?php echo $c['c_umoya_founder_eye_text']; ?></span>
      <h2><?php echo $c['c_h2_text']; ?></h2>
      <p><?php echo $c['c_p_text']; ?></p>
      <a class="umoya-founder-btn" href="<?php echo $c['c_umoya_founder_btn_href']; ?>"><?php echo $c['c_umoya_founder_btn_text']; ?></a>
    </div>
  </div>
</section>
