<?php
/**
 * Home Signature Journey -- render template.
 *
 * GENERATED by tools/uew from homepage-revamp/homepage-section-03-signature-journey.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
  UMOYA HOMEPAGE - SECTION 03: SIGNATURE JOURNEY
  Purpose: centered journey section with a wide image carousel and copy below.
  Elementor: paste this as one HTML widget. The CTA uses the shared Umoya popup trigger.
-->
<span id="umoya-journey-anchor" style="<?php echo $s['anchor_inline_style']; ?>" aria-hidden="true"></span>
<section id="umoya-journey" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="umoya-journey-wrap umoya-journey-rv">
    <!-- Intro band follows the reference layout: title block left, key numbers right. -->
    <header class="umoya-journey-intro">
      <div class="umoya-journey-intro-copy">
        <span class="umoya-journey-kicker"><?php echo $c['eyebrow_text']; ?></span>
        <h2 class="umoya-journey-heading"><?php echo $c['title_text']; ?></h2>
      </div>

      <dl class="umoya-journey-stats" aria-label="<?php echo $c['stats_aria_label']; ?>">
        <?php $__i = 0; foreach ( $r['rep_div_umoya_journey_stat'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><div class="umoya-journey-stat <?php echo $it['_uew_item_class']; ?>">
          <dt><?php echo $it['dt']; ?></dt>
          <dd><?php echo $it['dd']; ?></dd>
        </div><?php endforeach; echo "\n      "; ?></dl>
    </header>

    <!-- Image carousel — 3 slides, one per immersive chapter. Dot order follows image order. -->
    <div class="umoya-journey-carousel" aria-label="<?php echo $c['slide_aria_label']; ?>">
      <img class="umoya-journey-image is-active" src="<?php echo $c['image_src']; ?>" alt="<?php echo $c['image_alt']; ?>" loading="<?php echo $c['image_loading']; ?>" decoding="<?php echo $c['image_decoding']; ?>" fetchpriority="<?php echo $c['image_fetchpriority']; ?>">
      <?php $__i = 0; foreach ( $r['rep_img_umoya_journey_image'] as $it ) : if ( $__i ++ ) { echo '
      '; } ?><img class="umoya-journey-image <?php echo $it['_uew_item_class']; ?>" src="<?php echo $it['src']; ?>" alt="<?php echo $it['alt']; ?>" loading="<?php echo $it['loading']; ?>" decoding="<?php echo $it['decoding']; ?>"><?php endforeach; echo "\n\n      "; ?><!-- Captions paired 1:1 with the images above -->
      <div class="umoya-journey-slide-cap is-active" data-journey-cap="<?php echo $c['container_data_journey_cap']; ?>">
        <span class="umoya-journey-slide-kicker"><?php echo $c['eyebrow_text_2']; ?></span>
        <p class="umoya-journey-slide-title"><?php echo $c['title_text_2']; ?></p>
      </div>
      <?php $__i = 0; foreach ( $r['rep_div_umoya_journey_slide_cap'] as $it ) : if ( $__i ++ ) { echo '
      '; } ?><div class="umoya-journey-slide-cap <?php echo $it['_uew_item_class']; ?>" data-journey-cap="<?php echo '' . $it['_uew_n'] . ''; ?>">
        <span class="umoya-journey-slide-kicker"><?php echo $it['slide_kicker']; ?></span>
        <p class="umoya-journey-slide-title"><?php echo $it['slide_title']; ?></p>
      </div><?php endforeach; echo "\n\n      "; ?><div class="umoya-journey-dots" aria-label="<?php echo $c['dot_aria_label']; ?>">
        <button class="umoya-journey-dot is-active" type="<?php echo $c['dot_type']; ?>" data-journey-dot="<?php echo $c['dot_data_journey_dot']; ?>" aria-label="<?php echo $c['dot_aria_label_2']; ?>" aria-current="true"<?php echo $c['dot_disabled']; ?>></button>
        <?php $__i = 0; foreach ( $r['rep_button_umoya_journey_dot'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><button class="umoya-journey-dot <?php echo $it['_uew_item_class']; ?>" type="<?php echo $it['type']; ?>" data-journey-dot="<?php echo '' . $it['_uew_n'] . ''; ?>" aria-label="<?php echo $it['aria_label']; ?>" aria-current="<?php echo $it['aria_current']; ?>"></button><?php endforeach; echo "\n      "; ?></div>
    </div>

    <!-- Text content sits below the carousel, aligned to the same width. -->
    <div class="umoya-journey-copy">
      <p class="umoya-journey-body"><?php echo $c['text_text']; ?></p>

      <ul class="umoya-journey-highlights" aria-label="<?php echo $c['list_aria_label']; ?>">
        <li class="umoya-journey-highlight">
          <span class="umoya-journey-check" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none"><path d="M5 12.5l4.2 4.2L19 7" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
          </span>
          <span><?php echo $c['text_text_2']; ?></span>
        </li>
      </ul>

      <a class="umoya-journey-cta" href="<?php echo $c['button_href']; ?>">
        <?php echo $c['button_text']; echo "\n        "; ?><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg>
      </a>
    </div>
  </div>

</section>
