<?php
/**
 * Home Legends -- render template.
 *
 * GENERATED by tools/uew from homepage-revamp/homepage-section-05-legends.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA HOMEPAGE — NEW SECTION: THE UMOYA DIFFERENCE (LEGENDS)
=================================================================
  v4 revamp — NEW section from the mockup ("It is who opens the
  door"), with the client's updated header and copy:
  "Signature Moments Guided by South African Legends".

  4 cultural custodians: Lucia Motloung · Antoinette Sithole ·
  Christo Brand · Ntsiki Biyela.

  IMAGES: per the client (July 19 feedback), good portraits of these
  people were not available, so each card uses an ASSOCIATIVE image
  that describes what the person is known for rather than a portrait:
  Lucia → Luc Mo wines · Antoinette → Hector Pieterson Memorial ·
  Christo → Robben Island · Ntsiki → the Cape Winelands.
  These are the intended images (no longer "coming soon" stand-ins).
  ELEMENTOR: place after the Ways to Travel section.
=================================================================
-->
<section id="umoya-legends" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="umoya-leg-wrap">

    <div class="umoya-leg-head umoya-leg-rv">
      <span class="umoya-leg-eye"><?php echo $c['eyebrow_text']; ?></span>
      <h2><?php echo $c['heading_text']; ?></h2>
      <p class="umoya-leg-lead"><?php echo $c['text_text']; ?></p>
    </div>

    <div class="umoya-leg-grid">

      <article class="umoya-leg-card umoya-leg-rv" aria-label="<?php echo $c['card_aria_label']; ?>">
        <div class="umoya-leg-media">
          <!-- Client-chosen associative image (July 19 feedback): Luc Mo wines / "The Welcome", in place of a portrait -->
          <img src="<?php echo $c['image_src']; ?>" alt="<?php echo $c['image_alt']; ?>" loading="<?php echo $c['image_loading']; ?>" decoding="<?php echo $c['image_decoding']; ?>">
        </div>
        <div class="umoya-leg-body">
          <span class="umoya-leg-role"><?php echo $c['text_text_2']; ?></span>
          <h3 class="umoya-leg-name"><?php echo $c['heading_text_2']; ?></h3>
          <p class="umoya-leg-desc"><?php echo $c['text_text_3']; ?></p>
        </div>
      </article>

      <article class="umoya-leg-card umoya-leg-rv d1" aria-label="<?php echo $c['card_aria_label_2']; ?>">
        <div class="umoya-leg-media">
          <!-- Client-chosen associative image (July 19 feedback): the Hector Pieterson Memorial, in place of a portrait -->
          <img src="<?php echo $c['image_src_2']; ?>" alt="<?php echo $c['image_alt_2']; ?>" loading="<?php echo $c['image_loading_2']; ?>" decoding="<?php echo $c['image_decoding_2']; ?>">
        </div>
        <div class="umoya-leg-body">
          <span class="umoya-leg-role"><?php echo $c['text_text_4']; ?></span>
          <h3 class="umoya-leg-name"><?php echo $c['heading_text_3']; ?></h3>
          <p class="umoya-leg-desc"><?php echo $c['text_text_5']; ?></p>
        </div>
      </article>

      <article class="umoya-leg-card umoya-leg-rv d2" aria-label="<?php echo $c['card_aria_label_3']; ?>">
        <div class="umoya-leg-media">
          <!-- Client-chosen associative image (July 19 feedback): Robben Island, in place of a portrait -->
          <img src="<?php echo $c['image_src_3']; ?>" alt="<?php echo $c['image_alt_3']; ?>" loading="<?php echo $c['image_loading_3']; ?>" decoding="<?php echo $c['image_decoding_3']; ?>">
        </div>
        <div class="umoya-leg-body">
          <span class="umoya-leg-role"><?php echo $c['text_text_6']; ?></span>
          <h3 class="umoya-leg-name"><?php echo $c['heading_text_4']; ?></h3>
          <p class="umoya-leg-desc"><?php echo $c['text_text_7']; ?></p>
        </div>
      </article>

      <article class="umoya-leg-card umoya-leg-rv d3" aria-label="<?php echo $c['card_aria_label_4']; ?>">
        <div class="umoya-leg-media">
          <!-- Client-chosen associative image (July 19 feedback): the Cape Winelands, in place of a portrait -->
          <img src="<?php echo $c['image_src_4']; ?>" alt="<?php echo $c['image_alt_4']; ?>" loading="<?php echo $c['image_loading_4']; ?>" decoding="<?php echo $c['image_decoding_4']; ?>">
        </div>
        <div class="umoya-leg-body">
          <span class="umoya-leg-role"><?php echo $c['text_text_8']; ?></span>
          <h3 class="umoya-leg-name"><?php echo $c['heading_text_5']; ?></h3>
          <p class="umoya-leg-desc"><?php echo $c['text_text_9']; ?></p>
        </div>
      </article>

    </div>
  </div>

</section>
