<?php
/**
 * Home Legends -- render template.
 *
 * GENERATED by tools/uew from homepage-revamp/homepage-section-05-legends.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA HOMEPAGE — NEW SECTION: THE UMOYA DIFFERENCE (LEGENDS)
=================================================================
  v4 revamp — NEW section from the mockup ("It is who opens the
  door"), with the client's updated header and copy:
  "Signature Moments Guided by South African Legends".

  4 cultural custodians: Lucia Motloung · Antoinette Sithole ·
  Christo Brand · Ntsiki Biyela.

  IMAGES: per the client (July 19 feedback), good portraits of these
  people were not available, so each card uses an ASSOCIATIVE image
  that describes what the person is known for rather than a portrait:
  Lucia → Luc Mo wines · Antoinette → Hector Pieterson Memorial ·
  Christo → Robben Island · Ntsiki → the Cape Winelands.
  These are the intended images (no longer "coming soon" stand-ins).
  ELEMENTOR: place after the Ways to Travel section.
=================================================================
-->
<section id="umoya-legends" aria-label="<?php echo $c['c_section_aria_label']; ?>">
  <div class="umoya-leg-wrap">

    <div class="umoya-leg-head umoya-leg-rv">
      <span class="umoya-leg-eye"><?php echo $c['c_umoya_leg_eye_text']; ?></span>
      <h2><?php echo $c['c_h2_text']; ?></h2>
      <p class="umoya-leg-lead"><?php echo $c['c_umoya_leg_lead_text']; ?></p>
    </div>

    <div class="umoya-leg-grid">

      <?php $__i = 0; foreach ( $r['rep_article_umoya_leg_card'] as $it ) : if ( $__i ++ ) { echo '

      '; } ?><article class="<?php echo array( 'umoya-leg-card umoya-leg-rv', 'umoya-leg-card umoya-leg-rv d1', 'umoya-leg-card umoya-leg-rv d2', 'umoya-leg-card umoya-leg-rv d3' )[ ( ( (int) $it['_uew_n'] ) - 1 ) % 4 ]; ?> <?php echo $it['_uew_item_class']; ?>" aria-label="<?php echo $it['aria_label']; ?>">
        <div class="umoya-leg-media"><?php echo $it['notes']; ?><img src="<?php echo $it['src']; ?>" alt="<?php echo $it['alt']; ?>" loading="<?php echo $it['loading']; ?>" decoding="<?php echo $it['decoding']; ?>">
        </div>
        <div class="umoya-leg-body">
          <span class="umoya-leg-role"><?php echo $it['role']; ?></span>
          <h3 class="umoya-leg-name"><?php echo $it['name']; ?></h3>
          <p class="umoya-leg-desc"><?php echo $it['desc']; ?></p>
        </div>
      </article><?php endforeach; echo "\n\n    "; ?></div>
  </div>

</section>
