<?php
/**
 * Home Film & Award -- render template.
 *
 * GENERATED by tools/uew from homepage-revamp/homepage-section-08-film-award.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA HOMEPAGE — NEW SECTION: BRAND FILM + AWARD
=================================================================
  v4 revamp — NEW section. The brand film and the ITFFA award move
  out of the top of the page (mockup position) and live here as a
  supporting proof point, per the client's recommendation.

  • Film: "Let Your Story Begin" — native YouTube embed showing the
    video's first frame and player controls in place (lazy-loaded).
  • Award: Silver Award — Best Country Tourism Film, International
    Tourism Film Festival Africa 2026. The laurel icon is a
    PLACEHOLDER — swap for the official ITFFA badge (★ SWAP).
  ELEMENTOR: place after the Founder's Circle invitation.
=================================================================
-->
<section id="umoya-film" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="umoya-film-wrap">

    <!-- LEFT — copy, left-aligned, with the award badge beneath it -->
    <div class="umoya-film-copy umoya-film-rv">
      <span class="umoya-film-eye"><?php echo $c['eyebrow_text']; ?></span>
      <h2><?php echo $c['heading_text']; ?></h2>
      <div class="umoya-film-lead">
        <?php $__i = 0; foreach ( $r['rep_p'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><p class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['p_markup']; ?></p><?php endforeach; echo "\n      "; ?></div>
    </div>

    <!-- RIGHT — film, with the award badge directly beneath it (client
         feedback: sitting under the body copy "felt a little off"). -->
    <div class="umoya-film-media umoya-film-rv d1">
      <!-- Native YouTube player: shows the video's first frame + YouTube
           controls in place, so visitors press play right on the embed. -->
      <div class="umoya-film-frame">
        <iframe
          src="<?php echo $c['embed_src']; ?>"
          title="<?php echo $c['embed_title']; ?>"
          loading="<?php echo $c['embed_loading']; ?>"
          allow="<?php echo $c['embed_allow']; ?>"<?php echo $c['embed_allowfullscreen']; echo "\n          "; ?>referrerpolicy="<?php echo $c['embed_referrerpolicy']; ?>"
        ></iframe>
      </div>

      <!-- Award callout -->
      <div class="umoya-film-award" role="note" aria-label="<?php echo $c['container_aria_label']; ?>">
        <!-- ★ SWAP: replace this placeholder laurel with the official ITFFA award badge -->
        <span class="umoya-film-award-icon" aria-hidden="true">
          <svg viewBox="0 0 24 24">
            <circle cx="12" cy="9" r="5"/>
            <path d="M8.5 13.5L7 21l5-2.6L17 21l-1.5-7.5"/>
          </svg>
        </span>
        <span>
          <span class="umoya-film-award-title"><?php echo $c['title_text']; ?></span>
          <span class="umoya-film-award-sub"><?php echo $c['subtitle_text']; ?></span>
        </span>
      </div>
    </div>

  </div>

</section>
