<?php
/**
 * Home Speak With an Expert -- render template.
 *
 * GENERATED by tools/uew from homepage-revamp/homepage-section-11-speak-with-expert.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA HOMEPAGE — SPEAK WITH AN EXPERT (CLOSING CTA)
=================================================================
  v4 revamp — extracted from the Travel Essentials footer into its
  own section (mockup copy format). Background stays BROWN per the
  client's note; the button is transparent with a cream outline and
  fills on hover.
  ELEMENTOR: final HTML widget before the footer. The button opens
  the shared inquiry popup via data-umoya-form-popup.
=================================================================
-->
<section id="umoya-speak-expert" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="umoya-spk-wrap umoya-spk-rv">
    <span class="umoya-spk-eye"><?php echo $c['eyebrow_text']; ?></span>
    <h2><?php echo $c['heading_text']; ?></h2>
    <p class="umoya-spk-lead"><?php echo $c['text_text']; ?></p>
    <button type="<?php echo $c['button_type']; ?>" class="umoya-spk-btn" data-umoya-form-popup<?php echo $c['button_disabled']; ?>><?php echo $c['button_text']; ?></button>
  </div>

</section>
