<?php
/**
 * Home Inquiry Popup -- render template.
 *
 * GENERATED by tools/uew from homepage-revamp/homepage-form-popup.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<div id="umoya-form-popup" class="umoya-form-popup" aria-hidden="true">
  <div class="umoya-form-dialog" role="dialog" aria-modal="true" aria-labelledby="umoya-form-title">
    <button type="<?php echo $c['button_type']; ?>" class="umoya-form-close" data-umoya-form-close aria-label="<?php echo $c['button_aria_label']; ?>"<?php echo $c['button_disabled']; ?>>
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
    </button>

    <div class="umoya-form-image" aria-hidden="true">
      <img src="<?php echo $c['image_src']; ?>" alt="<?php echo $c['image_alt']; ?>">
      <div class="umoya-form-image-copy">
        <span><?php echo $c['text_text']; ?></span>
        <h2><?php echo $c['heading_text']; ?></h2>
      </div>
    </div>

    <div class="umoya-form-panel">
      <div class="umoya-form-head">
        <span><?php echo $c['text_text_2']; ?></span>
        <h2 id="umoya-form-title"><?php echo $c['heading_text_2']; ?></h2>
        <p><?php echo $c['text_text_3']; ?></p>
      </div>

      <div class="umoya-form-card">
        <form
          data-hs-do-not-collect="<?php echo $c['form_data_hs_do_not_collect']; ?>"
          id="umoyaPopupForm"
          class="umoya-popup-form"
          action="<?php echo $c['form_action']; ?>"
          method="<?php echo $c['form_method']; ?>"
          target="<?php echo $c['form_target']; ?>"<?php echo $c['form_novalidate']; echo "\n          "; ?>data-hubspot-portal-id="<?php echo $c['form_data_hubspot_portal_id']; ?>"
          data-hubspot-form-id="<?php echo $c['form_data_hubspot_form_id']; ?>"
          data-umoya-form-source="<?php echo $c['form_data_umoya_form_source']; ?>"
          data-wordpress-backup-endpoint="<?php echo $c['form_data_wordpress_backup_endpoint']; ?>"
          data-hubspot-consent-text="<?php echo $c['form_data_hubspot_consent_text']; ?>"
        >
          <?php $__i = 0; foreach ( $r['rep_input'] as $it ) : if ( $__i ++ ) { echo '
          '; } ?><input type="<?php echo $it['type']; ?>" name="<?php echo $it['name']; ?>" value="<?php echo $it['value']; ?>" class="<?php echo $it['_uew_item_class']; ?>"><?php endforeach; echo "\n          "; ?><div class="umoya-form-grid">
            <div class="umoya-field">
              <label for="umoyaTitle"><?php echo $c['label_text']; ?></label>
              <select id="umoyaTitle" name="<?php echo $c['select_name']; ?>"<?php echo $c['select_required']; ?><?php echo $c['select_disabled']; ?><?php echo $c['select_multiple']; ?>>
                <?php $__i = 0; foreach ( $r['rep_option'] as $it ) : if ( $__i ++ ) { echo '
                '; } ?><option value="<?php echo $it['value']; ?>"<?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n              "; ?></select>
            </div>
            <div class="umoya-field-spacer" aria-hidden="true"></div>

            <div class="umoya-field">
              <label for="umoyaFirst"><?php echo $c['label_text_2']; ?></label>
              <input id="umoyaFirst" name="<?php echo $c['anchor_name']; ?>" type="<?php echo $c['anchor_type']; ?>" placeholder="<?php echo $c['anchor_placeholder']; ?>"<?php echo $c['anchor_required']; ?> autocomplete="<?php echo $c['anchor_autocomplete']; ?>"<?php echo $c['anchor_disabled']; ?><?php echo $c['anchor_readonly']; ?><?php echo $c['anchor_checked']; ?>>
            </div>
            <div class="umoya-field">
              <label for="umoyaLast"><?php echo $c['label_text_3']; ?></label>
              <input id="umoyaLast" name="<?php echo $c['anchor_name_2']; ?>" type="<?php echo $c['anchor_type_2']; ?>" placeholder="<?php echo $c['anchor_placeholder_2']; ?>"<?php echo $c['anchor_required_2']; ?> autocomplete="<?php echo $c['anchor_autocomplete_2']; ?>"<?php echo $c['anchor_disabled_2']; ?><?php echo $c['anchor_readonly_2']; ?><?php echo $c['anchor_checked_2']; ?>>
            </div>

            <div class="umoya-field">
              <label for="umoyaEmail"><?php echo $c['label_text_4']; ?></label>
              <input id="umoyaEmail" name="<?php echo $c['anchor_name_3']; ?>" type="<?php echo $c['anchor_type_3']; ?>" placeholder="<?php echo $c['anchor_placeholder_3']; ?>"<?php echo $c['anchor_required_3']; ?> autocomplete="<?php echo $c['anchor_autocomplete_3']; ?>"<?php echo $c['anchor_disabled_3']; ?><?php echo $c['anchor_readonly_3']; ?><?php echo $c['anchor_checked_3']; ?>>
            </div>
            <div class="umoya-field">
              <label for="umoyaPhone"><?php echo $c['label_text_5']; ?></label>
              <input id="umoyaPhone" name="<?php echo $c['anchor_name_4']; ?>" type="<?php echo $c['anchor_type_4']; ?>" placeholder="<?php echo $c['anchor_placeholder_4']; ?>" autocomplete="<?php echo $c['anchor_autocomplete_4']; ?>"<?php echo $c['anchor_required_4']; ?><?php echo $c['anchor_disabled_4']; ?><?php echo $c['anchor_readonly_4']; ?><?php echo $c['anchor_checked_4']; ?>>
            </div>

            <div class="umoya-field">
              <label for="umoyaCountry"><?php echo $c['label_text_6']; ?></label>
              <select id="umoyaCountry" name="<?php echo $c['select_name_2']; ?>"<?php echo $c['select_required_2']; ?><?php echo $c['select_disabled_2']; ?><?php echo $c['select_multiple_2']; ?>>
                  <?php $__i = 0; foreach ( $r['rep_option_2'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n                "; ?></select>
            </div>
            <div class="umoya-field">
              <label for="umoyaCity"><?php echo $c['label_text_7']; ?></label>
              <input id="umoyaCity" name="<?php echo $c['anchor_name_5']; ?>" type="<?php echo $c['anchor_type_5']; ?>" placeholder="<?php echo $c['anchor_placeholder_5']; ?>" autocomplete="<?php echo $c['anchor_autocomplete_5']; ?>"<?php echo $c['anchor_required_5']; ?><?php echo $c['anchor_disabled_5']; ?><?php echo $c['anchor_readonly_5']; ?><?php echo $c['anchor_checked_5']; ?>>
            </div>

            <div class="umoya-field full">
              <label for="umoyaMonth"><?php echo $c['label_text_8']; ?></label>
              <div class="umoya-when">
                <select id="umoyaMonth" name="<?php echo $c['select_name_3']; ?>" aria-label="<?php echo $c['select_aria_label']; ?>"<?php echo $c['select_required_3']; ?><?php echo $c['select_disabled_3']; ?><?php echo $c['select_multiple_3']; ?>>
                  <?php $__i = 0; foreach ( $r['rep_option_3'] as $it ) : if ( $__i ++ ) { echo '
                  '; } ?><option value="<?php echo $it['value']; ?>"<?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n                "; ?></select>
                <select id="umoyaYear" name="<?php echo $c['select_name_4']; ?>" aria-label="<?php echo $c['select_aria_label_2']; ?>"<?php echo $c['select_required_4']; ?><?php echo $c['select_disabled_4']; ?><?php echo $c['select_multiple_4']; ?>>
                  <?php $__i = 0; foreach ( $r['rep_option_4'] as $it ) : if ( $__i ++ ) { echo '
                  '; } ?><option value="<?php echo $it['value']; ?>"<?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n                "; ?></select>
              </div>
            </div>

            <div class="umoya-field full">
              <label for="umoyaGuests"><?php echo $c['label_text_9']; ?></label>
              <select id="umoyaGuests" name="<?php echo $c['select_name_5']; ?>"<?php echo $c['select_required_5']; ?><?php echo $c['select_disabled_5']; ?><?php echo $c['select_multiple_5']; ?>>
                <?php $__i = 0; foreach ( $r['rep_option_5'] as $it ) : if ( $__i ++ ) { echo '
                '; } ?><option value="<?php echo $it['value']; ?>"<?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n              "; ?></select>
            </div>

            <div class="umoya-field full">
              <label for="umoyaMessage"><?php echo $c['label_text_10']; ?></label>
              <textarea id="umoyaMessage" name="<?php echo $c['anchor_name_6']; ?>" placeholder="<?php echo $c['anchor_placeholder_6']; ?>"<?php echo $c['anchor_required_6']; ?><?php echo $c['anchor_disabled_6']; ?><?php echo $c['anchor_readonly_6']; ?>></textarea>
            </div>
          </div>

          <!-- Consent (POPIA) — required box must be ticked; not pre-checked -->
          <div class="umoya-consent">
            <?php $__i = 0; foreach ( $r['rep_label_umoya_consent_item'] as $it ) : if ( $__i ++ ) { echo '
            '; } ?><label class="umoya-consent-item <?php echo $it['_uew_item_class']; ?>" for="<?php echo $it['for']; ?>">
              <input type="<?php echo $it['type']; ?>" id="<?php echo $it['id']; ?>" name="<?php echo $it['name']; ?>" value="<?php echo $it['value']; ?>"<?php echo $it['aria_required']; ?>>
              <span><?php echo $it['span_markup']; ?></span>
            </label><?php endforeach; echo "\n          "; ?></div>

          <button type="<?php echo $c['button_type_2']; ?>" class="umoya-form-submit"<?php echo $c['button_disabled_2']; ?>><?php echo $c['button_text']; ?></button>
          <p class="umoya-form-status" role="status" aria-live="polite"></p>
          <p class="umoya-form-legal"><?php echo $c['consent_text']; ?></p>
        </form>
        <iframe name="umoyaPopupSubmissionFrame" title="<?php echo $c['embed_title']; ?>" style="<?php echo $s['embed_inline_style']; ?>"<?php echo $c['embed_allowfullscreen']; ?>></iframe>
      </div>
    </div>
  </div>
</div>
