<?php
/**
 * Home Travel Essentials -- render template.
 *
 * GENERATED by tools/uew from homepage-revamp/homepage-section-10-travel-essentials.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA HOMEPAGE — TRAVEL ESSENTIALS (FAQ)
=================================================================
  ELEMENTOR USAGE:
  - Add an "HTML" widget after the Why Umoya (pillars) section.
  - The accordion is collapsible: clicking any item expands it
    and collapses any previously open item (one open at a time).
  - Item 1 is open by default via the fc-det-open class.
  - 5 items: Departures, Personalization, Travel Protection,
    Journey Structure, Cuisine and Dietary Care.
  - The "Speak with an expert" CTA now lives in its OWN section
    (homepage-section-11-speak-with-expert.html) — do not
    re-add it here.
=================================================================
-->
  <section id="fc-details" aria-label="<?php echo $c['c_section_aria_label']; ?>">
    <div class="fc-det-wrap">

      <!-- Section header -->
      <div class="fc-det-hd fc-det-rev">
        <span class="fc-det-eyebrow"><?php echo $c['c_fc_det_eyebrow_text']; ?></span>
        <h2 class="fc-det-title"><?php echo $c['c_fc_det_title_text']; ?></h2>
        <span class="fc-det-rule" aria-hidden="true"></span>
        <p class="fc-det-lead"><?php echo $c['c_fc_det_lead_text']; ?></p>
      </div>

      <!-- Accordion list -->
      <div class="fc-acc fc-det-rev fc-d1" role="list">

        <!-- Item 1: Guaranteed Departures (open by default) -->
        <?php $__i = 0; foreach ( $r['rep_div_fc_acc_item'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><div class="<?php echo ( 1 === ( (int) $it['_uew_n'] ) ? 'fc-acc-item fc-det-open' : 'fc-acc-item' ); ?> <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['role']; ?>">
          <button
            class="fc-acc-btn"
            aria-expanded="<?php echo ( 1 === ( (int) $it['_uew_n'] ) ? 'true' : 'false' ); ?>"
            aria-controls="<?php echo 'fc-det-body-' . ( (int) $it['_uew_n'] + 1 ); ?>"
            id="<?php echo 'fc-det-btn-' . ( (int) $it['_uew_n'] + 1 ); ?>"
          >
            <div class="fc-acc-left">
              <div class="fc-acc-icon" aria-hidden="<?php echo $it['aria_hidden']; ?>">
                <svg viewBox="<?php echo $it['viewbox']; ?>"><?php echo $it['svg_markup']; ?></svg>
              </div>
              <div>
                <p class="fc-acc-title"><?php echo $it['title']; ?></p>
                <p class="fc-acc-sub"><?php echo $it['sub']; ?></p>
              </div>
            </div>
            <div class="fc-acc-chev" aria-hidden="<?php echo $it['aria_hidden_2']; ?>">
              <svg viewBox="<?php echo $it['viewbox_2']; ?>"><polyline points="<?php echo $it['icon_points']; ?>"/></svg>
            </div>
          </button>
          <div class="fc-acc-body" id="<?php echo 'fc-det-body-' . ( (int) $it['_uew_n'] + 1 ); ?>" role="<?php echo $it['role_2']; ?>" aria-labelledby="<?php echo 'fc-det-btn-' . ( (int) $it['_uew_n'] + 1 ); ?>">
            <div class="fc-acc-content"><?php echo $it['content_markup']; ?></div>
          </div>
        </div><?php endforeach; echo "\n\n      "; ?></div><!-- /.fc-acc -->

    </div>
  </section>
