<?php
/**
 * Home Hotel Stays -- render template.
 *
 * GENERATED by tools/uew from homepage-revamp/homepage-section-06-hotel-stays.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — HOMEPAGE (REVAMP) SECTION 06: HOTEL STAYS
  Featured hotel: CAPE GRACE (A Fairmont Hotel · V&A Waterfront)
=================================================================
  Full-bleed (edge-to-edge) cinematic carousel band.

  MOTION — rebuilt to be fail-proof:
  • The images SLIDE horizontally. Motion is driven by a JS
    requestAnimationFrame tween that writes `transform` every frame
    (NO CSS transition, NO drag) — so the slide is always visible,
    with no reliance on transition/reflow timing.
  • Auto-advances every 5s on a continuous, seamless loop
    (cloned edge slides; an instant jump off the clone keeps it
    endless). The arrows trigger the same slide.
  • Text sits FIXED, top-left, over the images and never moves.

  Tall/thin luxury line-arrows on the far left/right (no chrome,
  no hover; scale-down on click). Bottom-left note links to the
  Signature Journey stays. "Featured Hotel" badge makes clear
  Cape Grace is the featured stay, not the only one.

  Standalone Elementor HTML widget (not a generator source file).
  BRAND: font-family: inherit; palette tokens only. Scoped to
  #umoya-accommodations. ES5 IIFE, IntersectionObserver-paused when
  off-screen. Autoplay is intentional and runs regardless of the OS
  "reduce motion" setting. Each slide carries an earthy fallback
  background so the slide is visible even before/without images.
=================================================================
-->
<section id="umoya-accommodations" role="region" aria-roledescription="<?php echo $c['section_aria_roledescription']; ?>" aria-label="<?php echo $c['section_aria_label']; ?>">
  <!-- IMAGE LAYER -->
  <div class="umoya-hs-viewport" data-hs-viewport>
    <div class="umoya-hs-track" data-hs-track>
      <?php $__i = 0; foreach ( $r['rep_div_umoya_hs_slide'] as $it ) : if ( $__i ++ ) { echo '
      '; } ?><div class="umoya-hs-slide <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['role']; ?>" aria-roledescription="<?php echo $it['aria_roledescription']; ?>" aria-label="<?php echo 'Cape Grace — ' . $it['_uew_n'] . ' of ' . $it['_uew_count']; ?>" style="<?php echo $it['style']; ?>">
        <img src="<?php echo $it['src']; ?>" alt="<?php echo $it['alt']; ?>" loading="<?php echo $it['loading']; ?>"<?php echo $it['fetchpriority']; ?> decoding="<?php echo $it['decoding']; ?>">
      </div><?php endforeach; echo "\n    "; ?></div>
  </div>

  <!-- SCRIM -->
  <div class="umoya-hs-scrim" aria-hidden="true"></div>

  <!-- FIXED TEXT (top-left) -->
  <div class="umoya-hs-content">
    <div class="umoya-hs-inner">
      <div class="umoya-hs-kicker">
        <span class="umoya-hs-eye"><?php echo $c['eyebrow_text']; ?></span>
        <span class="umoya-hs-badge">
          <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2l2.9 6.26L21.6 9l-5 4.6 1.3 7.4L12 17.6 6.1 21l1.3-7.4-5-4.6 6.7-.74L12 2z"/></svg>
          <?php echo $c['label_text']; echo "\n        "; ?></span>
      </div>
      <h2 class="umoya-hs-name"><?php echo $c['heading_text']; ?></h2>
      <span class="umoya-hs-place"><?php echo $c['text_text']; ?></span>
      <a class="umoya-hs-btn" href="<?php echo $c['button_href']; ?>" target="<?php echo $c['button_target']; ?>" rel="<?php echo $c['button_rel']; ?>">
        <?php echo $c['button_text']; echo "\n        "; ?><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M7 17L17 7" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/><path d="M9 7h8v8" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>
      </a>
    </div>
  </div>

  <!-- NOTE pinned to the bottom -->
  <div class="umoya-hs-foot">
    <p class="umoya-hs-note"><?php echo $c['text_text_2']; ?> <a href="<?php echo $c['link_href']; ?>" target="<?php echo $c['link_target']; ?>" rel="<?php echo $c['link_rel']; ?>"><?php echo $c['link_text']; ?></a><?php echo $c['text_text_2_2']; ?></p>
  </div>

  <!-- ARROWS (thin line-arrows) -->
  <button class="umoya-hs-arrow umoya-hs-prev" type="<?php echo $c['arrow_type']; ?>" data-hs-prev aria-label="<?php echo $c['arrow_aria_label']; ?>"<?php echo $c['arrow_disabled']; ?>>
    <svg viewBox="0 0 56 16" fill="none" aria-hidden="true">
      <path d="M55 8 H3 M11 2 L3 8 L11 14" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
  </button>
  <button class="umoya-hs-arrow umoya-hs-next" type="<?php echo $c['arrow_type_2']; ?>" data-hs-next aria-label="<?php echo $c['arrow_aria_label_2']; ?>"<?php echo $c['arrow_disabled_2']; ?>>
    <svg viewBox="0 0 56 16" fill="none" aria-hidden="true">
      <path d="M1 8 H53 M45 2 L53 8 L45 14" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
  </button>

</section>
