<?php
/**
 * 404 Page -- render template.
 *
 * GENERATED by tools/uew from shared/page-404.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — 404 / PAGE NOT FOUND  (Elementor HTML widget)
=================================================================
  Replaces the Tevily theme's default 404 body, which currently reads
  "The page requested could not be found. This could be a spelling
  error in the URL or a removed page." — accurate, but it reads like a
  server log.

  The live 404 already returns a correct HTTP 404 status and already
  renders the new site footer, so this is a content swap only. Do NOT
  turn it into a normal published page: a 200-status "404 page" is
  invisible to search engines and they will keep the dead URL indexed.

  WHERE IT GOES
    Elementor Pro → Templates → Theme Builder → Single → 404 Page.
    Compose that template as:
      shared/section-00-nav.html   (first)
      this widget
      shared/section-99-footer.html (last)
    If the theme's own 404 heading still prints above this, remove it —
    two <h1>s on one page is the one thing to check after pasting.

  BACKGROUND IMAGE
    umoya_compressed_img001238.jpeg — the Sabi Sand safari landscape
    already used on the Signature Journey and homepage. Chosen on
    weight as much as on looks: 326 KB, 4724×3154. The obvious
    alternatives were 2.1–2.7 MB, which is the wrong thing to spend a
    visitor's bandwidth on when they have already hit a dead end, on an
    origin with this site's documented TTFB. umoya_image-1.jpg is
    lighter still (207 KB) but is a 3.51:1 letterbox strip that crops
    badly on a tall phone.

    background-color is set to the brand brown as well, so the copy is
    readable before the image arrives — or if it never does.

  OVERLAY AND CONTRAST
    A radial overlay, darkest where the text sits and lighter at the
    edges so the photograph still reads. Worst case — a pure-white
    patch of image directly behind the words — the cream copy still
    measures about 10.5:1.

    The eyebrow is CREAM, not the usual terracotta. Terracotta on this
    overlay measures about 4.0:1, which is fine for the headline's
    italic word (large text needs 3:1) and for the rule (decorative),
    but short of the 4.5:1 that 12px text needs. Terracotta still
    appears twice — the rule and the emphasis — so the accent is not
    lost.

  WHY THERE IS NO JAVASCRIPT
    Every other section uses an IntersectionObserver reveal. This one
    deliberately does not. A 404 is already a failure state; its
    content must be on screen unconditionally.

  BRAND: font-family: inherit; palette tokens only. Scoped to
  #umoya-404. WCAG AA (44px targets, 12px type floor).
=================================================================
-->
<section id="umoya-404" aria-labelledby="um404-title">
  <span class="um404-mark" aria-hidden="true"><?php echo $c['c_um404_mark_text']; ?></span>

  <div class="um404-c">
    <span class="um404-eye"><?php echo $c['c_um404_eye_text']; ?></span>

    <!--
      Copy alternates, if the client prefers something plainer — swap the
      <h1> and the lead together so the metaphor does not half-survive:
        "This page has <em>moved on</em>"
        "We can't find that <em>page</em>"
    -->
    <h1 class="um404-ttl" id="um404-title"><?php echo $c['c_um404_ttl_text']; ?></h1>
    <hr class="um404-rule">
    <p class="um404-lead"><?php echo $c['c_um404_lead_text']; ?></p>

    <div class="um404-actions">
      <?php $__i = 0; foreach ( $r['rep_a_um404_btn'] as $it ) : if ( $__i ++ ) { echo '
      '; } ?><a class="<?php echo ( 1 === ( (int) $it['_uew_n'] ) ? 'um404-btn' : 'um404-btn is-ghost' ); ?> <?php echo $it['_uew_item_class']; ?>" href="<?php echo $it['href']; ?>"><?php echo $it['um404_btn']; ?></a><?php endforeach; echo "\n    "; ?></div>
  </div>
</section>

<!--
=================================================================
  _NOTES
=================================================================
  1. STATUS CODE. The live 404 already returns a real HTTP 404 —
     confirmed by requesting a random URL. Keep it that way. Build
     this as the Theme Builder 404 template, never as a published
     page with its own slug.

  2. TWO <h1>s. The Tevily 404 prints its own "404 / Page Not Found"
     heading. If it still shows above this widget, delete it — this
     widget carries the page's <h1>.

  3. NO SCRIPT, DELIBERATELY. Do not add a scroll-reveal here for
     consistency's sake; nothing on an error page should depend on JS
     running.

  4. NO LINK LIST. An earlier draft carried a five-item "Or continue
     from here" row. Removed on request — the shared nav above and the
     footer below already offer every one of those destinations, and
     repeating them a third time on one screen added nothing. The two
     buttons are the whole recovery path now.

  5. BACKGROUND WEIGHT. If the image is ever swapped, check the file
     size first. Several of the obvious candidates in the uploads
     folder are 2–2.7 MB full-resolution exports sitting in the
     "optimized" folder despite the name. CLAUDE.md's image procedure
     (2400px long edge, quality 82, 300–800 KB) is the standard to
     hold a replacement to.

  6. CONTRAST. Cream copy measures about 10.5:1 against the overlay
     even over a pure-white patch of photograph. Terracotta measures
     about 4.0:1 there, which is why it is used only on the rule and
     the headline's italic word, never on 12px text. If the overlay is
     ever lightened, re-check both.

  7. PRE-EXISTING, NOT INTRODUCED HERE: white on terracotta
     (#FFFFFF on #D97E53) is 2.97:1, below AA for the button label.
     That is the site's established button on every page, so it is kept
     here for consistency rather than diverging on one screen — but it
     is worth fixing site-wide.
=================================================================
-->
