<?php
/**
 * Cookie Policy Page -- render template.
 *
 * GENERATED by tools/uew from shared/page-cookie-policy.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — COOKIE POLICY  (Elementor HTML widget)
=================================================================
  Publish at /cookie-policy/. The footer does NOT link here directly —
  its "Cookie Settings" entry is a CookieYes trigger — but this page
  is the URL to set as the cookie policy link INSIDE the CookieYes
  banner configuration, which is an outstanding non-code step.
  Section 3 of the Privacy Policy links here too.

  REPLACES the version currently live. That page is still v1.0 and
  still renders the literal placeholder "Effective date: [INSERT DATE]".
  This is v1.2 from "Revised footer docs/Umoya_Cookie_Policy (v2).txt",
  with real dates and, new in this revision, the named per-cookie
  inventory (__cf_bm, m, _ga_*, the CookieYes consent cookie) and
  CookieYes itself identified as the consent platform. Copy is VERBATIM.

  ONE ADDITION, no copy changed: section 4 tells the reader they can
  "change your preferences at any time by clicking the cookie-settings
  link in the footer". A CookieYes trigger button is placed right there
  so they can do it without hunting for the footer. It uses the same
  .cky-banner-element hook and the same not-loaded guard as
  shared/section-99-footer.html — see the comment on that button.

  ELEMENTOR: nav first, this widget, footer last.
  BRAND: font-family: inherit; palette tokens only. ES5 IIFE.
=================================================================
-->
<section id="umoya-cookie-policy" aria-labelledby="ck-title">
  <div class="ck-c">

    <header>
      <span class="ck-eye"><?php echo $c['eyebrow_text']; ?></span>
      <h1 class="ck-ttl" id="ck-title"><?php echo $c['title_text']; ?></h1>
      <hr class="ck-rule">
      <p class="ck-meta">
        <?php echo $c['text_text']; echo "\n      "; ?></p>
    </header>

    <!-- ═══════════ 1 ═══════════ -->
    <div class="ck-sec">
      <h2 class="ck-h2"><span class="ck-num"><?php echo $c['text_text_2']; ?></span><?php echo $c['heading_text']; ?></h2>
      <p class="ck-p"><?php echo $c['content_text']; ?> <a href="<?php echo $c['link_href']; ?>"><?php echo $c['link_text']; ?></a><?php echo $c['content_text_2']; ?></p>
    </div>

    <!-- ═══════════ 2 ═══════════ -->
    <div class="ck-sec">
      <h2 class="ck-h2"><span class="ck-num"><?php echo $c['text_text_3']; ?></span><?php echo $c['heading_text_2']; ?></h2>
      <?php $__i = 0; foreach ( $r['rep_p_ck_p'] as $it ) : if ( $__i ++ ) { echo '
      '; } ?><p class="ck-p <?php echo $it['_uew_item_class']; ?>"><?php echo $it['ck_p']; ?></p><?php endforeach; echo "\n    "; ?></div>

    <!-- ═══════════ 3 ═══════════ -->
    <div class="ck-sec">
      <h2 class="ck-h2"><span class="ck-num"><?php echo $c['text_text_4']; ?></span><?php echo $c['heading_text_3']; ?></h2>
      <p class="ck-p"><?php echo $c['text_text_5']; ?></p>

      <h3 class="ck-h3"><?php echo $c['heading_text_4']; ?></h3>
      <?php $__i = 0; foreach ( $r['rep_p_ck_p_2'] as $it ) : if ( $__i ++ ) { echo '
      '; } ?><p class="ck-p <?php echo $it['_uew_item_class']; ?>"><?php echo $it['ck_p']; ?></p><?php endforeach; echo "\n      "; ?><ul class="ck-list">
        <?php $__i = 0; foreach ( $r['rep_li_ck_li'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><li class="ck-li <?php echo $it['_uew_item_class']; ?>"><?php echo $it['ck_li_markup']; ?></li><?php endforeach; echo "\n      "; ?></ul>

      <h3 class="ck-h3"><?php echo $c['heading_text_5']; ?></h3>
      <?php $__i = 0; foreach ( $r['rep_p_ck_p_3'] as $it ) : if ( $__i ++ ) { echo '
      '; } ?><p class="ck-p <?php echo $it['_uew_item_class']; ?>"><?php echo $it['ck_p']; ?></p><?php endforeach; echo "\n      "; ?><ul class="ck-list">
        <li class="ck-li"><?php echo $c['item_text']; ?></li>
      </ul>
      <p class="ck-p"><?php echo $c['text_text_6']; ?></p>

      <h3 class="ck-h3"><?php echo $c['heading_text_6']; ?></h3>
      <p class="ck-p"><?php echo $c['text_text_7']; ?></p>

      <h3 class="ck-h3"><?php echo $c['heading_text_7']; ?></h3>
      <?php $__i = 0; foreach ( $r['rep_p_ck_p_4'] as $it ) : if ( $__i ++ ) { echo '
      '; } ?><p class="ck-p <?php echo $it['_uew_item_class']; ?>"><?php echo $it['ck_p']; ?></p><?php endforeach; echo "\n    "; ?></div>

    <!-- ═══════════ 4 ═══════════ -->
    <div class="ck-sec">
      <h2 class="ck-h2"><span class="ck-num"><?php echo $c['text_text_8']; ?></span><?php echo $c['heading_text_8']; ?></h2>
      <p class="ck-p"><?php echo $c['text_text_9']; ?></p>

      <!--
        Same CookieYes hook and same not-loaded guard as the footer's
        button. A <button>, not <a href="#">, so it never jumps the page
        to the top if CookieYes has not loaded.
      -->
      <div class="ck-prefs">
        <p class="ck-prefs-p"><?php echo $c['text_text_10']; ?></p>
        <button type="<?php echo $c['button_type']; ?>" class="ck-prefs-btn cky-banner-element" data-umoya-cookie-prefs<?php echo $c['button_disabled']; ?>><?php echo $c['button_text']; ?></button>
      </div>

      <?php $__i = 0; foreach ( $r['rep_p_ck_p_5'] as $it ) : if ( $__i ++ ) { echo '
      '; } ?><p class="ck-p <?php echo $it['_uew_item_class']; ?>"><?php echo $it['ck_p']; ?></p><?php endforeach; echo "\n      "; ?><ul class="ck-list">
        <?php $__i = 0; foreach ( $r['rep_li_ck_li_ck_li_link'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><li class="ck-li ck-li--link <?php echo $it['_uew_item_class']; ?>"><?php echo $it['link']; ?> <a href="<?php echo $it['href']; ?>" target="<?php echo $it['target']; ?>" rel="<?php echo $it['rel']; ?>"><?php echo $it['a']; ?></a></li><?php endforeach; echo "\n      "; ?></ul>
      <p class="ck-p"><?php echo $c['text_text_11']; ?></p>
    </div>

    <!-- ═══════════ 5 ═══════════ -->
    <div class="ck-sec">
      <h2 class="ck-h2"><span class="ck-num"><?php echo $c['text_text_12']; ?></span><?php echo $c['heading_text_9']; ?></h2>
      <p class="ck-p"><?php echo $c['text_text_13']; ?></p>
    </div>

    <!-- ═══════════ 6 ═══════════ -->
    <div class="ck-sec">
      <h2 class="ck-h2"><span class="ck-num"><?php echo $c['text_text_14']; ?></span><?php echo $c['heading_text_10']; ?></h2>
      <p class="ck-p"><?php echo $c['text_text_15']; ?></p>
    </div>

    <!-- ═══════════ 7 ═══════════ -->
    <div class="ck-sec">
      <h2 class="ck-h2"><span class="ck-num"><?php echo $c['text_text_16']; ?></span><?php echo $c['heading_text_11']; ?></h2>
      <div class="ck-ct">
        <?php echo $c['container_text']; echo "\n        "; ?><a href="<?php echo $c['link_href_2']; ?>"><?php echo $c['link_text_2']; ?></a><?php echo $c['container_text_2']; ?> <a href="<?php echo $c['link_href_3']; ?>"><?php echo $c['link_text_3']; ?></a><?php echo $c['container_text_3']; echo "\n      "; ?></div>
    </div>

  </div>
</section>
