<?php
/**
 * P&T Design Your Journey Form -- render template.
 *
 * GENERATED by tools/uew from private-tailormade/section-05-design-form.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — PRIVATE & TAILORMADE — SECTION 05: DESIGN YOUR JOURNEY
=================================================================
  Two-column: copy left, inquiry form right (stacks on mobile).

  INTEGRATION — matches the Founder's Circle form:
  • Posts to /wp-json/umoya/v1/submissions (WordPress stores the
    submission and forwards it to HubSpot).
  • If WordPress is unreachable, the browser falls back to posting
    directly to the HubSpot Forms API and queues the WP backup.
  • Submits to its OWN HubSpot form, "Private & Tailormade Inquiry"
    (GUID 28e4e3e3-9a47-47a5-b3de-851981535664), no longer the shared
    "Umoya Website Form Submissions" form.
  • The MERGE* input names are kept (they are just DOM field names)
    but now map to DEDICATED HubSpot contact properties:
      MERGE2 → trip_occasion            (was borrowing `country`)
      MERGE4 → preferred_travel_season  (carries MONTH)
      MERGE5 → preferred_travel_year
      MERGE6 → party_size               (was borrowing `preferred_journey_length`)
      MERGE7 → founders_circle_message  (the brief)
    class-submissions.php resolves these per-source, so the WordPress
    backup path writes the same properties as the direct path.

  ANCHOR: id="pt-design" — every "Design Your Journey" / "Make it
  yours" CTA on this page targets it.
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="pt-design" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="pt-df-c">
    <div class="pt-df-grid">

      <div class="pt-df-rv">
        <span class="pt-df-eye"><?php echo $c['eyebrow_text']; ?></span>
        <h2 class="pt-df-ttl"><?php echo $c['title_text']; ?></h2>
        <p class="pt-df-lead"><?php echo $c['text_text']; ?></p>
      </div>

      <div class="pt-df-card pt-df-rv d1">
        <!-- Hidden target keeps the native POST from navigating away if JS is off -->
        <iframe name="umoyaSubmissionFrame" style="<?php echo $s['embed_inline_style']; ?>" title="<?php echo $c['embed_title']; ?>" aria-hidden="true"<?php echo $c['embed_allowfullscreen']; ?>></iframe>

        <form
          data-hs-do-not-collect="<?php echo $c['form_data_hs_do_not_collect']; ?>"
          class="pt-df-form"
          id="ptDesignForm"
          action="<?php echo $c['form_action']; ?>"
          method="<?php echo $c['form_method']; ?>"
          target="<?php echo $c['form_target']; ?>"<?php echo $c['form_novalidate']; echo "\n          "; ?>aria-label="<?php echo $c['form_aria_label']; ?>"
          data-hubspot-portal-id="<?php echo $c['form_data_hubspot_portal_id']; ?>"
          data-hubspot-form-id="<?php echo $c['form_data_hubspot_form_id']; ?>"
          data-umoya-form-source="<?php echo $c['form_data_umoya_form_source']; ?>"
          data-wordpress-backup-endpoint="<?php echo $c['form_data_wordpress_backup_endpoint']; ?>"
          data-hubspot-consent-text="<?php echo $c['form_data_hubspot_consent_text']; ?>"
        >
          <input type="<?php echo $c['field_type']; ?>" name="<?php echo $c['field_name']; ?>" value="<?php echo $c['field_value']; ?>"<?php echo $c['field_required']; ?><?php echo $c['field_disabled']; ?><?php echo $c['field_readonly']; ?><?php echo $c['field_checked']; ?>>
          <input type="<?php echo $c['field_type_2']; ?>" name="<?php echo $c['field_name_2']; ?>" value="<?php echo $c['field_value_2']; ?>"<?php echo $c['field_required_2']; ?><?php echo $c['field_disabled_2']; ?><?php echo $c['field_readonly_2']; ?><?php echo $c['field_checked_2']; ?>>
          <input type="<?php echo $c['field_type_3']; ?>" name="<?php echo $c['field_name_3']; ?>" value="<?php echo $c['field_value_3']; ?>"<?php echo $c['field_required_3']; ?><?php echo $c['field_disabled_3']; ?><?php echo $c['field_readonly_3']; ?><?php echo $c['field_checked_3']; ?>>
          <input type="<?php echo $c['field_type_4']; ?>" name="<?php echo $c['field_name_4']; ?>" value="<?php echo $c['field_value_4']; ?>"<?php echo $c['field_required_4']; ?><?php echo $c['field_disabled_4']; ?><?php echo $c['field_readonly_4']; ?><?php echo $c['field_checked_4']; ?>>
          <input type="<?php echo $c['field_type_5']; ?>" name="<?php echo $c['field_name_5']; ?>" value="<?php echo $c['field_value_5']; ?>"<?php echo $c['field_required_5']; ?><?php echo $c['field_disabled_5']; ?><?php echo $c['field_readonly_5']; ?><?php echo $c['field_checked_5']; ?>>
          <input type="<?php echo $c['field_type_6']; ?>" name="<?php echo $c['field_name_6']; ?>" value="<?php echo $c['field_value_6']; ?>"<?php echo $c['field_required_6']; ?><?php echo $c['field_disabled_6']; ?><?php echo $c['field_readonly_6']; ?><?php echo $c['field_checked_6']; ?>>
          <input type="<?php echo $c['field_type_7']; ?>" name="<?php echo $c['field_name_7']; ?>" value="<?php echo $c['field_value_7']; ?>"<?php echo $c['field_required_7']; ?><?php echo $c['field_disabled_7']; ?><?php echo $c['field_readonly_7']; ?><?php echo $c['field_checked_7']; ?>>

          <div class="pt-df-row">
            <div class="pt-df-field">
              <label for="ptFirst"><?php echo $c['label_text']; ?></label>
              <input type="<?php echo $c['anchor_type']; ?>" id="ptFirst" name="<?php echo $c['anchor_name']; ?>"<?php echo $c['anchor_required']; ?> autocomplete="<?php echo $c['anchor_autocomplete']; ?>"<?php echo $c['anchor_disabled']; ?><?php echo $c['anchor_readonly']; ?><?php echo $c['anchor_checked']; ?>>
            </div>
            <div class="pt-df-field">
              <label for="ptLast"><?php echo $c['label_text_2']; ?></label>
              <input type="<?php echo $c['anchor_type_2']; ?>" id="ptLast" name="<?php echo $c['anchor_name_2']; ?>"<?php echo $c['anchor_required_2']; ?> autocomplete="<?php echo $c['anchor_autocomplete_2']; ?>"<?php echo $c['anchor_disabled_2']; ?><?php echo $c['anchor_readonly_2']; ?><?php echo $c['anchor_checked_2']; ?>>
            </div>
          </div>

          <div class="pt-df-row">
            <div class="pt-df-field">
              <label for="ptEmail"><?php echo $c['label_text_3']; ?></label>
              <input type="<?php echo $c['anchor_type_3']; ?>" id="ptEmail" name="<?php echo $c['anchor_name_3']; ?>"<?php echo $c['anchor_required_3']; ?> autocomplete="<?php echo $c['anchor_autocomplete_3']; ?>"<?php echo $c['anchor_disabled_3']; ?><?php echo $c['anchor_readonly_3']; ?><?php echo $c['anchor_checked_3']; ?>>
            </div>
            <div class="pt-df-field">
              <label for="ptPhone"><?php echo $c['label_text_4']; ?></label>
              <input type="<?php echo $c['anchor_type_4']; ?>" id="ptPhone" name="<?php echo $c['anchor_name_4']; ?>" autocomplete="<?php echo $c['anchor_autocomplete_4']; ?>"<?php echo $c['anchor_required_4']; ?><?php echo $c['anchor_disabled_4']; ?><?php echo $c['anchor_readonly_4']; ?><?php echo $c['anchor_checked_4']; ?>>
            </div>
          </div>

          <div class="pt-df-field">
            <label for="ptOccasion"><?php echo $c['label_text_5']; ?></label>
            <select id="ptOccasion" name="<?php echo $c['select_name']; ?>"<?php echo $c['select_required']; ?><?php echo $c['select_disabled']; ?><?php echo $c['select_multiple']; ?>>
              <?php $__i = 0; foreach ( $r['rep_option'] as $it ) : if ( $__i ++ ) { echo '
              '; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n            "; ?></select>
          </div>

          <div class="pt-df-row">
            <div class="pt-df-field">
              <label for="ptMonth"><?php echo $c['label_text_6']; ?></label>
              <select id="ptMonth" name="<?php echo $c['select_name_2']; ?>" aria-label="<?php echo $c['select_aria_label']; ?>"<?php echo $c['select_required_2']; ?><?php echo $c['select_disabled_2']; ?><?php echo $c['select_multiple_2']; ?>>
                <?php $__i = 0; foreach ( $r['rep_option_2'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n              "; ?></select>
            </div>
            <div class="pt-df-field">
              <label for="ptYear">&nbsp;</label>
              <select id="ptYear" name="<?php echo $c['select_name_3']; ?>" aria-label="<?php echo $c['select_aria_label_2']; ?>"<?php echo $c['select_required_3']; ?><?php echo $c['select_disabled_3']; ?><?php echo $c['select_multiple_3']; ?>>
                <?php $__i = 0; foreach ( $r['rep_option_3'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><option<?php echo $it['value']; ?><?php echo $it['disabled']; ?><?php echo $it['selected']; ?> class="<?php echo $it['_uew_item_class']; ?>"><?php echo $it['label']; ?></option><?php endforeach; echo "\n              "; ?></select>
            </div>
          </div>

          <div class="pt-df-field">
            <label for="ptGuests"><?php echo $c['label_text_7']; ?></label>
            <input type="<?php echo $c['anchor_type_5']; ?>" id="ptGuests" name="<?php echo $c['anchor_name_5']; ?>" placeholder="<?php echo $c['anchor_placeholder']; ?>" inputmode="<?php echo $c['anchor_inputmode']; ?>"<?php echo $c['anchor_required_5']; ?><?php echo $c['anchor_disabled_5']; ?><?php echo $c['anchor_readonly_5']; ?><?php echo $c['anchor_checked_5']; ?>>
          </div>

          <div class="pt-df-field">
            <label for="ptMessage"><?php echo $c['label_text_8']; ?> <span class="pt-df-opt"><?php echo $c['text_text_2']; ?></span></label>
            <textarea id="ptMessage" name="<?php echo $c['anchor_name_6']; ?>" rows="<?php echo $c['anchor_rows']; ?>"<?php echo $c['anchor_required_6']; ?><?php echo $c['anchor_disabled_6']; ?><?php echo $c['anchor_readonly_6']; ?>></textarea>
          </div>

          <label class="pt-df-consent" for="ptConsent">
            <input type="<?php echo $c['anchor_type_6']; ?>" id="ptConsent" name="<?php echo $c['anchor_name_7']; ?>"<?php echo $c['anchor_required_7']; ?><?php echo $c['anchor_disabled_7']; ?><?php echo $c['anchor_readonly_7']; ?><?php echo $c['anchor_checked_6']; ?>>
            <span><?php echo $c['text_text_3']; ?> <a href="<?php echo $c['link_href']; ?>" target="<?php echo $c['link_target']; ?>" rel="<?php echo $c['link_rel']; ?>"><?php echo $c['link_text']; ?></a><?php echo $c['text_text_2_2']; ?> <span class="pt-df-flag"><?php echo $c['text_text_4']; ?></span></span>
          </label>

          <label class="pt-df-consent" for="ptMarketing">
            <input type="<?php echo $c['anchor_type_7']; ?>" id="ptMarketing" name="<?php echo $c['anchor_name_8']; ?>"<?php echo $c['anchor_required_8']; ?><?php echo $c['anchor_disabled_8']; ?><?php echo $c['anchor_readonly_8']; ?><?php echo $c['anchor_checked_7']; ?>>
            <span><?php echo $c['text_text_5']; ?> <span class="pt-df-flag"><?php echo $c['text_text_6']; ?></span></span>
          </label>

          <button type="<?php echo $c['button_type']; ?>" class="pt-df-btn" id="ptDesignBtn"<?php echo $c['button_disabled']; ?>><?php echo $c['button_text']; ?></button>
          <p class="pt-df-legal"><?php echo $c['consent_text']; ?></p>
        </form>
      </div>

    </div>
  </div>
</section>
