<?php
/**
 * P&T How Tailoring Works -- render template.
 *
 * GENERATED by tools/uew from private-tailormade/section-04-how-it-works.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — PRIVATE & TAILORMADE — SECTION 04: HOW TAILORING WORKS
=================================================================
  Three numbered steps on the cream band.
  ANCHOR: id="pt-how"
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="pt-how" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="pt-hw-c">

    <div class="pt-hw-head pt-hw-rv">
      <span class="pt-hw-eye"><?php echo $c['eyebrow_text']; ?></span>
      <h2 class="pt-hw-ttl"><?php echo $c['title_text']; ?></h2>
    </div>

    <div class="pt-hw-steps" role="list">
      <?php $__i = 0; foreach ( $r['rep_div_pt_hw_step'] as $it ) : if ( $__i ++ ) { echo '

      '; } ?><div class="<?php echo 'pt-hw-step pt-hw-rv d' . $it['_uew_n']; ?> <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['role']; ?>">
        <div class="pt-hw-n"><?php echo $it['n']; ?></div>
        <h3 class="pt-hw-h"><?php echo $it['h']; ?></h3>
        <p class="pt-hw-p"><?php echo $it['p']; ?></p>
      </div><?php endforeach; echo "\n    "; ?></div>

  </div>
</section>
