<?php
/**
 * P&T Hero -- render template.
 *
 * GENERATED by tools/uew from private-tailormade/section-01-hero.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — PRIVATE & TAILORMADE — SECTION 01: HERO
=================================================================
  Full-bleed image hero with a cinematic overlay, centred content.
  ANCHOR: id="pt-hero" — first content widget after the site nav.
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="pt-hero" aria-label="<?php echo $c['c_section_aria_label']; ?>">

  <div class="pt-h-bg">
    <img
      src="<?php echo $c['c_img_src']; ?>"
      alt="<?php echo $c['c_img_alt']; ?>"
    />
  </div>

  <div class="pt-h-content">
    <span class="pt-h-eye"><?php echo $c['c_pt_h_eye_text']; ?></span>
    <h1 class="pt-h-title"><?php echo $c['c_pt_h_title_text']; ?></h1>
    <p class="pt-h-sub"><?php echo $c['c_pt_h_sub_text']; ?></p>
    <div class="pt-h-btns">
      <a href="<?php echo $c['c_pt_h_btn_primary_href']; ?>" class="pt-h-btn pt-h-btn-primary">
        <?php echo $c['c_pt_h_btn_primary_text']; echo "\n        "; ?><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" aria-hidden="true">
          <line x1="5" y1="12" x2="19" y2="12"/>
          <polyline points="13 6 19 12 13 18"/>
        </svg>
      </a>
      <a href="<?php echo $c['c_pt_h_btn_ghost_href']; ?>" class="pt-h-btn pt-h-btn-ghost"><?php echo $c['c_pt_h_btn_ghost_text']; ?></a>
    </div>
  </div>

</section>
