<?php
/**
 * Site Navigation -- render template.
 *
 * GENERATED by tools/uew from shared/section-00-nav.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — SITE-WIDE NAVIGATION
=================================================================
  The single navigation bar shared by every page (Signature
  Journey, Private & Tailormade, For Groups, About, Founder's
  Circle, Homepage). Adapted from the homepage-revamp nav.

  BEHAVIOUR — three states:
  1. DOCKED   At the very top of the page the bar sits in normal
              document flow, STACKED ABOVE the hero. It does not
              overlap the section below it, and it scrolls away
              with the page like any other element.
  2. STUCK    Once scrolled past, the bar detaches (position: fixed)
              and hides on a downward scroll, so it never covers
              content you are reading.
  3. RECALLED Any upward scroll slides it straight back into view.

  The mount wrapper RESERVES the bar's height at all times, so
  detaching to fixed never shifts the layout — no jump, no jitter.
  --nav-h on the mount is the single source of truth for that
  height (64px desktop / 58px ≤1024px) and the JS reads it back.

  • Links are absolute site URLs (not in-page anchors) so the same
    widget works on every page.
  • The link matching the current page is marked with .is-active
    automatically, by comparing pathnames on load.
  • Hamburger dropdown lives INSIDE the bar so it follows both the
    docked and fixed positions. The bar never hides while the
    mobile menu is open.

  ELEMENTOR: place this widget FIRST on every page. Do NOT wrap it
  in a section with overflow: hidden.

  THEME-HEADER TAKEOVER (Tevily / "Elementor Full Width" pages):
  On pages that use the Elementor Full Width template, the Tevily
  theme renders its OWN header with two sibling blocks:
    .header_default_screen  — holds this widget (hidden ≤1024px)
    .header-mobile          — the theme's own menu (shown ≤1024px)
  So below 1024px the theme swapped this nav out for its own menu,
  which pulls from the WP "primary" menu location and was showing
  stale links. The rules below hide the theme's block and keep this
  one visible at every width, so there is a single nav site-wide.

  These are the only selectors here that reach OUTSIDE this widget's
  root — unavoidable, since the elements being overridden are the
  widget's ANCESTOR and its SIBLING, which no descendant selector can
  target. They are kept safe by the .umoya-nav-takeover marker class,
  which the JS adds only to a theme header that actually contains
  this nav. If the widget is not inside one (e.g. Elementor Canvas
  pages), nothing is touched.

  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<div id="umoyaSiteNavMount">
  <nav id="umoyaSiteNav" aria-label="<?php echo $c['c_nav_aria_label']; ?>">
    <div class="umoya-nav-inner">

      <a class="umoya-nav-logo" href="<?php echo $c['c_umoya_nav_logo_href']; ?>" aria-label="<?php echo $c['c_umoya_nav_logo_aria_label']; ?>">
        <img
          src="<?php echo $c['c_img_src']; ?>"
          alt="<?php echo $c['c_img_alt']; ?>"
          onerror="this.style.display='none';document.getElementById('umoyaSiteNavLogoText').style.display='inline';"
        >
        <span class="umoya-nav-logo-text" id="umoyaSiteNavLogoText" style="<?php echo $s['c_umoya_nav_logo_text_inline_style']; ?>"><?php echo $c['c_umoya_nav_logo_text_text']; ?></span>
      </a>

      <ul class="umoya-nav-links" role="list">
        <?php $__i = 0; foreach ( $r['rep_li_umoya_nav_item'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><li class="umoya-nav-item <?php echo $it['_uew_item_class']; ?>" data-path="<?php echo $it['data_path']; ?>">
          <a class="umoya-nav-link" href="<?php echo $it['href']; ?>"><?php echo $it['link']; ?></a>
        </li><?php endforeach; echo "\n      "; ?></ul>

      <a class="umoya-nav-cta" href="<?php echo $c['c_umoya_nav_cta_href']; ?>"><?php echo $c['c_umoya_nav_cta_text']; ?></a>

      <button
        class="umoya-nav-burger"
        type="<?php echo $c['c_umoya_nav_burger_type']; ?>"
        aria-label="<?php echo $c['c_umoya_nav_burger_aria_label']; ?>"
        aria-expanded="false"
        aria-controls="umoyaSiteNavDropdown"<?php echo $c['c_umoya_nav_burger_disabled']; echo "\n      "; ?>>
        <span></span><span></span><span></span>
      </button>

      <div class="umoya-nav-dropdown" id="umoyaSiteNavDropdown" aria-label="<?php echo $c['c_umoya_nav_dropdown_aria_label']; ?>">
        <ul class="umoya-nav-dropdown-list" role="list">
          <?php $__i = 0; foreach ( $r['rep_li_umoya_nav_dropdown_item'] as $it ) : if ( $__i ++ ) { echo '
          '; } ?><li class="umoya-nav-dropdown-item <?php echo $it['_uew_item_class']; ?>" data-path="<?php echo $it['data_path']; ?>">
            <a class="umoya-nav-dropdown-link" href="<?php echo $it['href']; ?>"><?php echo $it['dropdown_link']; ?></a>
          </li><?php endforeach; echo "\n        "; ?></ul>

        <div class="umoya-nav-dropdown-cta-row">
          <a class="umoya-nav-dropdown-cta" href="<?php echo $c['c_umoya_nav_dropdown_cta_href']; ?>"><?php echo $c['c_umoya_nav_dropdown_cta_text']; ?></a>
        </div>
      </div>
    </div>

  </nav>
</div>
