<?php
/**
 * Site Footer -- render template.
 *
 * GENERATED by tools/uew from shared/section-99-footer.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — SITE-WIDE FOOTER  (Elementor HTML widget)
=================================================================
  Rebuilt 2026-08-29 from
    Mockups (footer, contact)/Umoya_Footer_Mockup.html
    Mockups (footer, contact)/Umoya_Footer_Routing_and_Implementation.docx
  Replaces BOTH the previous version of this file and the theme
  footer. Place LAST on every page — including Founder's Circle,
  which the routing doc calls out explicitly.

  Layout, column grouping, link set, fine print and bottom bar are
  the mockup's. Its colours are NOT: the routing doc states "the
  colors used in the mockup are illustrative so do not change the
  site's colors", so this uses the brand tokens and
  font-family: inherit throughout.

  ── FOUNDER'S CIRCLE SIGNUP ────────────────────────────────────
  Name + email, wired to the dedicated HubSpot form
    Portal 246097317 · Form 40d535ad-fc91-4831-8231-eddc05208624
    ("Footer Newsletter Signup" — fields: email + firstname)
  source = "footer_newsletter". Both properties resolve through the
  DEFAULT alias table in class-submissions.php, so this form needs
  no server-side change.

  Same submit path as every other Umoya form:
    1. POST /wp-json/umoya/v1/submissions (WordPress stores it,
       then forwards to HubSpot)
    2. if WordPress is unreachable → POST straight to the HubSpot
       Forms API and queue the WordPress backup in localStorage

  CONSENT: the routing doc requires the fine print to "ship exactly
  as written in the mockup", and the mockup states consent rather
  than collecting a tick ("By subscribing you consent to…"). That
  wording is reproduced verbatim below and is also sent as the
  submission's consentText, so the POPIA consent register records
  exactly what each subscriber agreed to and when. Note this is a
  deliberate change from the previous version of this file, which
  used a required checkbox — see _NOTES.

  ── COOKIE SETTINGS ────────────────────────────────────────────
  CookieYes exposes a built-in trigger: any element carrying the
  class `cky-banner-element` re-opens the preference centre. No
  href is needed, so this is a <button> rather than a dead "#" link.

  ── EMAIL OPT-OUT ──────────────────────────────────────────────
  Opens a popup carried at the bottom of this widget instead of
  navigating to /email-preferences/, so the reader is not taken off
  the page they were on. The copy is the routing doc's, verbatim, and
  identical to shared/page-email-preferences.html — that page is
  deliberately KEPT, unchanged, if we ever want the standalone route
  back. Switching between the two is a one-line edit; see the comment
  on the Email Opt-out list item.

  ── LINK SLUGS ─────────────────────────────────────────────────
  Every destination below was checked against the live site on
  2026-08-29. Four do not exist yet and are flagged in _NOTES.

  BRAND: font-family: inherit; palette tokens only. Scoped to
  #umoya-footer. ES5 IIFE. WCAG AA (44px targets, 16px input floor).
=================================================================
-->
<footer id="umoya-footer" role="contentinfo" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="umoya-ft-c">
    <div class="umoya-ft-main">

      <!-- ══════════ BRAND ══════════ -->
      <div class="umoya-ft-brand">
        <img
          src="<?php echo $c['image_src']; ?>"
          alt="<?php echo $c['image_alt']; ?>"
          width="1050"
          height="412"
          loading="<?php echo $c['image_loading']; ?>"
        >
        <p class="umoya-ft-descriptor"><?php echo $c['text_text']; ?></p>
        <div class="umoya-ft-contact">
          <a href="<?php echo $c['link_href']; ?>"><?php echo $c['link_text']; ?></a>
          <address class="umoya-ft-addr" style="<?php echo $s['addr_inline_style']; ?>">
            <?php echo $c['addr_text']; echo "\n          "; ?></address>
        </div>
      </div>

      <!-- ══════════ JOURNEYS ══════════ -->
      <nav class="umoya-ft-col" aria-label="<?php echo $c['column_aria_label']; ?>">
        <h3 class="umoya-ft-h"><?php echo $c['heading_text']; ?></h3>
        <ul>
          <?php $__i = 0; foreach ( $r['rep_li'] as $it ) : if ( $__i ++ ) { echo '
          '; } ?><li class="<?php echo $it['_uew_item_class']; ?>"><a href="<?php echo $it['href']; ?>"><?php echo $it['a']; ?></a></li><?php endforeach; echo "\n        "; ?></ul>
      </nav>

      <!-- ══════════ SUPPORT ══════════ -->
      <nav class="umoya-ft-col" aria-label="<?php echo $c['column_aria_label_2']; ?>">
        <h3 class="umoya-ft-h"><?php echo $c['heading_text_2']; ?></h3>
        <ul>
          <!-- ⚠ /travel-essentials/ does not exist yet — copy is in
               "Revised footer docs/Umoya_Travel_Essentials_Page_Copy.txt" -->
          <!-- ⚠ /travel-essentials/ not published yet - the ready-to-paste
               page is shared/page-travel-essentials.html -->
          <?php $__i = 0; foreach ( $r['rep_li_2'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><li class="<?php echo $it['_uew_item_class']; ?>"><a href="<?php echo $it['href']; ?>"<?php echo $it['extra_attributes']; ?>><?php echo $it['a']; ?></a></li><?php endforeach; echo "\n        "; ?></ul>
      </nav>

      <!-- ══════════ LEGAL ══════════ -->
      <nav class="umoya-ft-col" aria-label="<?php echo $c['column_aria_label_3']; ?>">
        <h3 class="umoya-ft-h"><?php echo $c['heading_text_3']; ?></h3>
        <ul>
          <li><a href="<?php echo $c['link_href_2']; ?>"><?php echo $c['link_text_2']; ?></a></li>
          <li><a href="<?php echo $c['link_href_3']; ?>"><?php echo $c['link_text_3']; ?></a></li>
          <!--
            CookieYes binds its own click handler to .cky-banner-element and
            re-opens the preference centre, so this needs no href. A <button>
            rather than <a href="#"> so it never jumps the page to the top if
            CookieYes has not loaded.
          -->
          <li><button type="<?php echo $c['button_type']; ?>" class="cky-banner-element" data-umoya-cookie-prefs<?php echo $c['button_disabled']; ?>><?php echo $c['button_text']; ?></button></li>
          <!--
            EMAIL OPT-OUT opens the popup at the bottom of this widget
            rather than navigating to /email-preferences/. The standalone
            page still exists, unchanged, at
            shared/page-email-preferences.html — to switch back to it,
            replace this <li> with:

              <li><a href="https://umoyaafrikatours.co.za/email-preferences/">Email Opt-out</a></li>

            and delete the popup block below.

            The href here is a REAL mailto, not "#" — it is what the item
            falls back to if the script has not run, and it does exactly
            what the popup copy tells the reader to do. The script calls
            preventDefault() and opens the dialog instead.
          -->
          <li><a href="<?php echo $c['link_href_4']; ?>" data-umoya-email-optout><?php echo $c['link_text_4']; ?></a></li>
          <!--
            umoya_paia_manual.pdf - underscores, umoya_ prefix. Uploaded and
            verified byte-identical to
            "Revised footer docs/Umoya_PAIA_Manual (final).pdf" on
            2026-09-01 (HTTP 200, 110300 bytes).

            Several other spellings of this file exist at the web root and
            are NOT interchangeable. Confirm with an HTTP request, never the
            Mountain Duck listing, which shows entries the server does not
            serve:
              /umoya_paia_manual.pdf   200  <- use this one
              /paia_manual.pdf         200  superseded, left in place
              /Umoya_PAIA_Manual.pdf   200  superseded, left in place
              /paia-manual.pdf         404  ghost listing only
            Nothing was deleted.
          -->
          <li><a href="<?php echo $c['link_href_5']; ?>" target="<?php echo $c['link_target']; ?>" rel="<?php echo $c['link_rel']; ?>"><?php echo $c['link_text_5']; ?></a></li>
        </ul>
      </nav>

      <!-- ══════════ FOUNDER'S CIRCLE SIGNUP ══════════ -->
      <div class="umoya-ft-signup">
        <h3 class="umoya-ft-h"><?php echo $c['heading_text_4']; ?></h3>

        <!-- Hidden target keeps a no-JS POST from navigating away -->
        <iframe name="umoyaFooterFrame" title="<?php echo $c['embed_title']; ?>" aria-hidden="true" style="<?php echo $s['embed_inline_style']; ?>"<?php echo $c['embed_allowfullscreen']; ?>></iframe>

        <form
          data-hs-do-not-collect="<?php echo $c['form_data_hs_do_not_collect']; ?>"
          id="umoyaFooterForm"
          action="<?php echo $c['form_action']; ?>"
          method="<?php echo $c['form_method']; ?>"
          target="<?php echo $c['form_target']; ?>"<?php echo $c['form_novalidate']; echo "\n          "; ?>aria-label="<?php echo $c['form_aria_label']; ?>"
          data-hubspot-portal-id="<?php echo $c['form_data_hubspot_portal_id']; ?>"
          data-hubspot-form-id="<?php echo $c['form_data_hubspot_form_id']; ?>"
          data-umoya-form-source="<?php echo $c['form_data_umoya_form_source']; ?>"
          data-wordpress-backup-endpoint="<?php echo $c['form_data_wordpress_backup_endpoint']; ?>"
          data-hubspot-consent-text="<?php echo $c['form_data_hubspot_consent_text']; ?>"
        >
          <input type="<?php echo $c['field_type']; ?>" name="<?php echo $c['field_name']; ?>" value="<?php echo $c['field_value']; ?>"<?php echo $c['field_required']; ?><?php echo $c['field_disabled']; ?><?php echo $c['field_readonly']; ?><?php echo $c['field_checked']; ?>>
          <input type="<?php echo $c['field_type_2']; ?>" name="<?php echo $c['field_name_2']; ?>" value="<?php echo $c['field_value_2']; ?>"<?php echo $c['field_required_2']; ?><?php echo $c['field_disabled_2']; ?><?php echo $c['field_readonly_2']; ?><?php echo $c['field_checked_2']; ?>>
          <input type="<?php echo $c['field_type_3']; ?>" name="<?php echo $c['field_name_3']; ?>" value="<?php echo $c['field_value_3']; ?>"<?php echo $c['field_required_3']; ?><?php echo $c['field_disabled_3']; ?><?php echo $c['field_readonly_3']; ?><?php echo $c['field_checked_3']; ?>>
          <input type="<?php echo $c['field_type_4']; ?>" name="<?php echo $c['field_name_4']; ?>" value="<?php echo $c['field_value_4']; ?>"<?php echo $c['field_required_4']; ?><?php echo $c['field_disabled_4']; ?><?php echo $c['field_readonly_4']; ?><?php echo $c['field_checked_4']; ?>>
          <input type="<?php echo $c['field_type_5']; ?>" name="<?php echo $c['field_name_5']; ?>" value="<?php echo $c['field_value_5']; ?>"<?php echo $c['field_required_5']; ?><?php echo $c['field_disabled_5']; ?><?php echo $c['field_readonly_5']; ?><?php echo $c['field_checked_5']; ?>>
          <input type="<?php echo $c['field_type_6']; ?>" name="<?php echo $c['field_name_6']; ?>" value="<?php echo $c['field_value_6']; ?>"<?php echo $c['field_required_6']; ?><?php echo $c['field_disabled_6']; ?><?php echo $c['field_readonly_6']; ?><?php echo $c['field_checked_6']; ?>>
          <input type="<?php echo $c['field_type_7']; ?>" name="<?php echo $c['field_name_7']; ?>" value="<?php echo $c['field_value_7']; ?>"<?php echo $c['field_required_7']; ?><?php echo $c['field_disabled_7']; ?><?php echo $c['field_readonly_7']; ?><?php echo $c['field_checked_7']; ?>>

          <label class="umoya-ft-sr" for="umoyaFtName"><?php echo $c['label_text']; ?></label>
          <input id="umoyaFtName" name="<?php echo $c['anchor_name']; ?>" type="<?php echo $c['anchor_type']; ?>" placeholder="<?php echo $c['anchor_placeholder']; ?>" autocomplete="<?php echo $c['anchor_autocomplete']; ?>"<?php echo $c['anchor_required']; ?><?php echo $c['anchor_disabled']; ?><?php echo $c['anchor_readonly']; ?><?php echo $c['anchor_checked']; ?>>

          <label class="umoya-ft-sr" for="umoyaFtEmail"><?php echo $c['label_text_2']; ?></label>
          <input id="umoyaFtEmail" name="<?php echo $c['anchor_name_2']; ?>" type="<?php echo $c['anchor_type_2']; ?>" placeholder="<?php echo $c['anchor_placeholder_2']; ?>"<?php echo $c['anchor_required_2']; ?> autocomplete="<?php echo $c['anchor_autocomplete_2']; ?>"<?php echo $c['anchor_disabled_2']; ?><?php echo $c['anchor_readonly_2']; ?><?php echo $c['anchor_checked_2']; ?>>

          <button type="<?php echo $c['button_type_2']; ?>" class="umoya-ft-submit" id="umoyaFtSubmit"<?php echo $c['button_disabled_2']; ?>><?php echo $c['button_text_2']; ?></button>
          <p class="umoya-ft-status" role="status" aria-live="polite"></p>
        </form>

        <!--
          VERBATIM from the mockup. The routing doc: "The consent fine print
          under the form must ship exactly as written in the mockup." The same
          wording is sent as consentText with every submission, so the POPIA
          consent register records exactly what was agreed to.
        -->
        <p class="umoya-ft-fine"><?php echo $c['text_text_2']; ?> <a href="<?php echo $c['link_href_6']; ?>" target="<?php echo $c['link_target_2']; ?>" rel="<?php echo $c['link_rel_2']; ?>"><?php echo $c['link_text_6']; ?></a><?php echo $c['text_text_2_2']; ?></p>
      </div>

    </div>
  </div>

  <!-- ══════════ BOTTOM BAR ══════════ -->
  <div class="umoya-ft-bottom">
    <div class="umoya-ft-bottom-inner">
      <p class="umoya-ft-legalline"><?php echo $c['text_text_3']; ?> <span data-umoya-year><?php echo $c['text_text_4']; ?></span> <?php echo $c['text_text_2_3']; ?></p>
      <p class="umoya-ft-tag"><?php echo $c['label_text_3']; ?></p>
      <div class="umoya-ft-social">
        <!-- Only accounts confirmed to exist on the live site are linked.
             The mockup also shows YouTube; no channel URL has been supplied,
             so it stays commented out rather than shipping as a dead link.

             INSTAGRAM GLYPH: not the mockup's. The mockup's path draws the
             lens as a same-direction subpath, so under the default nonzero
             fill rule it never punches through — it rendered as a solid
             rounded square with a filled dot, not a camera. Replaced with the
             official mark (Simple Icons), whose counters are wound to cut out
             correctly. Still a single filled path using currentColor, so it
             needs no CSS change and matches the weight of the other three. -->
        <a href="<?php echo $c['link_href_7']; ?>" target="<?php echo $c['link_target_3']; ?>" rel="<?php echo $c['link_rel_3']; ?>" aria-label="<?php echo $c['link_aria_label']; ?>">
          <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98C8.333 23.986 8.741 24 12 24c3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 1 0 0 12.324 6.162 6.162 0 0 0 0-12.324zM12 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm6.406-11.845a1.44 1.44 0 1 0 0 2.881 1.44 1.44 0 0 0 0-2.881z"/></svg>
        </a>
        <a href="<?php echo $c['link_href_8']; ?>" target="<?php echo $c['link_target_4']; ?>" rel="<?php echo $c['link_rel_4']; ?>" aria-label="<?php echo $c['link_aria_label_2']; ?>">
          <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M13.5 21v-8h2.7l.4-3.2h-3.1V7.7c0-.9.3-1.6 1.7-1.6h1.6V3.2c-.3 0-1.3-.1-2.4-.1-2.4 0-4 1.4-4 4.1v2.6H7.6V13h2.8v8h3.1z"/></svg>
        </a>
        <a href="<?php echo $c['link_href_9']; ?>" target="<?php echo $c['link_target_5']; ?>" rel="<?php echo $c['link_rel_5']; ?>" aria-label="<?php echo $c['link_aria_label_3']; ?>">
          <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M16.8 5.6c-.9-.6-1.5-1.6-1.7-2.6h-3v12.3a2.6 2.6 0 1 1-2.6-2.6c.3 0 .5 0 .8.1V9.7a5.7 5.7 0 1 0 4.9 5.6V9.4c1 .7 2.3 1.2 3.6 1.2V7.5c-.7 0-1.4-.2-2-.6-.4-.2-.7-.5-1-.8z"/></svg>
        </a>
        <a href="<?php echo $c['link_href_10']; ?>" target="<?php echo $c['link_target_6']; ?>" rel="<?php echo $c['link_rel_6']; ?>" aria-label="<?php echo $c['link_aria_label_4']; ?>">
          <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M4.98 3.5a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5zM3 9h4v12H3V9zm6 0h3.8v1.7h.05c.53-1 1.83-2.05 3.77-2.05 4.03 0 4.78 2.65 4.78 6.1V21h-4v-5.5c0-1.31-.02-3-1.83-3-1.83 0-2.11 1.43-2.11 2.9V21H9V9z"/></svg>
        </a>
        <!-- YouTube — enable once the channel URL is confirmed:
        <a href="REPLACE_WITH_YOUTUBE_CHANNEL_URL" target="_blank" rel="noopener" aria-label="Umoya Afrika Tours on YouTube">
          <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M21.6 7.2c-.2-.9-.9-1.6-1.8-1.8C18.2 5 12 5 12 5s-6.2 0-7.8.4c-.9.2-1.6.9-1.8 1.8C2 8.8 2 12 2 12s0 3.2.4 4.8c.2.9.9 1.6 1.8 1.8C5.8 19 12 19 12 19s6.2 0 7.8-.4c.9-.2 1.6-.9 1.8-1.8.4-1.6.4-4.8.4-4.8s0-3.2-.4-4.8zM10 15V9l5.2 3L10 15z"/></svg>
        </a>
        -->
      </div>
    </div>
  </div>
</footer>

<!--
=================================================================
  UMOYA — EMAIL OPT-OUT POPUP  (ships inside the footer widget)
=================================================================
  Added 2026-09-02, replacing the footer's link out to
  /email-preferences/. Same copy, shown in place instead of costing
  the visitor a page load away from whatever they were reading.

  THE STANDALONE PAGE IS DELIBERATELY KEPT.
  shared/page-email-preferences.html is unchanged and still ready to
  publish at /email-preferences/. To go back to it, see the note on
  the Email Opt-out list item above — it is a one-line edit, and this
  whole block can then be deleted.

  COPY is verbatim from
  "Mockups (footer, contact)/Umoya_Footer_Routing_and_Implementation.docx",
  identical to the page:

    "Point Email Opt-out at a short page with two elements: one line
     of copy … and a link to the HubSpot subscription preferences
     page for our portal, which I will send you once the HubSpot
     email domain setup is finalised. Until the HubSpot preference
     URL exists, ship the page with the copy and the mailto link
     only."

  So the HubSpot preferences CTA is COMMENTED OUT below, exactly as
  it is on the page. When that URL arrives, enable it in both files.

  ── WHY THIS IS ITS OWN ROOT, NOT SCOPED UNDER #umoya-footer ────
  The dialog is position: fixed, and a fixed element inside an
  ancestor carrying transform / filter / will-change is positioned
  against THAT ancestor instead of the viewport — which Elementor
  motion effects can introduce at any time. So, exactly like
  homepage-revamp/homepage-form-popup.html, this moves itself to
  document.body on init and therefore carries its own id and its own
  scoped CSS. The style block lives inside the element, so it travels
  with it.

  ⚠ NEVER WRITE A LITERAL style OR script TAG INSIDE A COMMENT IN
  THIS FILE. The live site minifies inline CSS BEFORE it strips HTML
  comments, and it finds style blocks by regex. A mention of that tag
  in a comment therefore opens a "stylesheet" that only closes at the
  next real closing tag — swallowing the comment's own terminator.
  The comment then runs on to the NEXT terminator further down the
  file and takes every element in between with it.

  This is not hypothetical: it silently deleted this popup's opening
  div, its entire stylesheet, the dialog wrapper, the close button,
  the eyebrow, the heading and the rule on the live site, leaving the
  body copy stranded and unstyled at the foot of every page. Write
  "style block" or "the script", never the tag itself.

  BRAND: font-family: inherit; palette tokens only. ES5 IIFE.
  WCAG AA (44px close target, focus trap, Esc, restored focus).
=================================================================
-->
<div id="umoya-email-optout" aria-hidden="true" hidden<?php echo $c['_uew_for']; ?>>
  <div class="umoya-ep-dialog" role="dialog" aria-modal="true"
       aria-labelledby="umoya-ep-title" aria-describedby="umoya-ep-body">

    <button type="<?php echo $c['button_type_3']; ?>" class="umoya-ep-close" data-umoya-ep-close aria-label="<?php echo $c['button_aria_label']; ?>"<?php echo $c['button_disabled_3']; ?>>
      <svg viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false"><path d="M6 6l12 12M18 6L6 18" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
    </button>

    <span class="umoya-ep-eye"><?php echo $c['eyebrow_text']; ?></span>
    <h2 class="umoya-ep-ttl" id="umoya-ep-title"><?php echo $c['title_text']; ?></h2>
    <hr class="umoya-ep-rule">

    <!-- Copy verbatim from the routing doc — identical to
         shared/page-email-preferences.html. -->
    <p class="umoya-ep-body" id="umoya-ep-body"><?php echo $c['content_text']; ?> <a href="<?php echo $c['link_href_11']; ?>"><?php echo $c['link_text_7']; ?></a> <?php echo $c['content_text_2']; ?> <strong><?php echo $c['strong_text']; ?></strong> <?php echo $c['content_text_3']; ?></p>

    <!--
      ENABLE ONCE THE HUBSPOT SUBSCRIPTION-PREFERENCES URL IS KNOWN.
      It arrives after the HubSpot email domain setup is finalised.
      Paste it into the href and delete these comment markers — then do
      the same in shared/page-email-preferences.html so the two stay in
      step.

    <a class="umoya-ep-cta" href="REPLACE_WITH_HUBSPOT_SUBSCRIPTION_PREFERENCES_URL" target="_blank" rel="noopener">Manage Email Preferences</a>
    -->
  </div>
</div>

<!--
=================================================================
  _NOTES — deployment & open points
=================================================================
  1. PLACE LAST ON EVERY PAGE, Founder's Circle included (the
     routing doc calls that page out by name). Then DELETE the old
     Elementor Form newsletter widget — otherwise the HubSpot
     WordPress plugin keeps auto-capturing it as
     ".elementor-form … converted (August 11, 2026)".

  2. SLUGS — checked live 2026-08-29:
       ✅ /signature-journey/          200 (redirects to
                                       /signature-journey-unpublished/)
       ✅ /private-and-tailormade/     200
       ✅ /for-groups/                 200
       ✅ /about-us/                   200
       ✅ /contact/                    200 — the real page is live; the
                                       Tevily demo copy is gone, and the
                                       duplicate /contact-us/ now 404s.
       ✅ /terms-and-conditions/       200 — this REPLACES the
                                       /booking-terms path in the old
                                       FOOTER URL MAP doc, which 404s.
       ⚠ /privacy/                    200, but still the v1.0 page with
                                       "Effective date: [INSERT DATE]".
                                       Replace with the v1.1 widget in
                                       shared/page-privacy-policy.html
       ⏳ /travel-essentials/          404 — page BUILT, not yet published:
                                       shared/page-travel-essentials.html
       — /email-preferences/          NO LONGER LINKED. Email Opt-out
                                       is now a popup inside this widget
                                       (see note 11), so the 404 no
                                       longer matters. The page is kept,
                                       unpublished, at
                                       shared/page-email-preferences.html
       ❌ /umoya_travel_brochure.pdf   404 — Ashley to supply. Upload
                                       under exactly this name.
       ✅ /umoya_paia_manual.pdf       200 — uploaded 2026-09-01,
                                       byte-identical to the final manual.
                                       Older spellings still resolve and
                                       were left in place; /paia-manual.pdf
                                       is a ghost listing and 404s.

     Not linked from this footer but part of the same set:
       ⚠ /cookie-policy/               200, but still v1.0 with
                                       "[INSERT DATE]". Replace with
                                       shared/page-cookie-policy.html.
                                       This is the URL to set as the
                                       cookie policy link in CookieYes.
     Re-checked 2026-09-01.

  3. COOKIE SETTINGS uses CookieYes's own `.cky-banner-element`
     trigger, so it needs no URL. The routing doc also asks for two
     CookieYes changes that are NOT code:
       • replace the current CookieYes script with the one for the
         new Umoya account (emailed separately), so consent records
         live under Umoya's own account;
       • publish the Cookie Policy from the Drive and set it as the
         cookie policy link inside the CookieYes banner config.

  4. CONSENT MODEL CHANGED. The previous version of this footer used
     a required, never-pre-ticked marketing checkbox. The mockup and
     routing doc instead specify statement-style consent ("By
     subscribing you consent to…") with no checkbox, and require that
     wording to ship exactly. That is what is implemented. Submitting
     the form is the affirmative act; the exact wording is stored with
     every submission. If legal counsel prefers the explicit tick,
     re-adding the checkbox is a small change — but it will then differ
     from the signed-off mockup.

  5. HUBSPOT FORM NAME. The signup still posts to the form named
     "Footer Newsletter Signup" (GUID unchanged). The routing doc says
     it should feed "the Founder's Circle list in HubSpot" — that is a
     HubSpot-side active list / workflow fed by this form, not a code
     change. Optionally rename the form in HubSpot to match the new
     footer label; the GUID, and therefore this file, stays the same.

  6. SOCIAL. Instagram, Facebook, TikTok and LinkedIn are all
     confirmed live accounts linked from the site. The mockup also
     shows YouTube; no channel URL exists, so it is commented out
     rather than shipped as a dead link.

  7. ADDRESS. The mockup omits "Maude Street"; the live site footer
     includes it. The fuller live version is used here and in
     contact/section-03-direct.html.

  8. INSTAGRAM GLYPH REPLACED (2026-09-01). The mockup's Instagram path
     drew the camera lens as a subpath wound the SAME direction as the
     outer squircle, so under SVG's default nonzero fill rule it never
     punched through — it rendered as a solid rounded square with a
     filled dot, no lens ring and no corner dot. Its lens radius was
     7.8 against the real mark's ~6.2 as well. Swapped for the official
     glyph (Simple Icons), whose counters are wound to cut out. Still a
     single filled path on currentColor, so no CSS change and the same
     visual weight as Facebook / TikTok / LinkedIn beside it. The
     commented-out YouTube path was checked at the same time and is
     fine — its play triangle knocks out correctly.

  9. FULL-BLEED WIDTH. Do not "simplify" --umoya-ft-vw back to a plain
     100vw. 100vw includes the vertical scrollbar, so on any page tall
     enough to scroll this footer became a scrollbar-width too wide and
     gave the WHOLE page a horizontal scrollbar. Measured before the
     fix: viewport 822px, footer 838px, starting at left: -8px.

 10. FOUNDER'S CIRCLE PAGE CAVEAT. As of 2026-09-01 /founders-circle/
     is served without most plugin assets, CookieYes included — so the
     Cookie Settings button on THAT page will hit the fallback rather
     than a preference centre even once CookieYes is installed
     site-wide. See CLAUDE.md Section 21.

 11. EMAIL OPT-OUT IS A POPUP (2026-09-02). It was a link to
     /email-preferences/, which has never been published and 404s.
     It now opens a dialog carried at the bottom of this widget, so
     it works the moment this footer is pasted in — no second page to
     create, and the reader is not taken off the page they were on.

     • The standalone page is UNCHANGED and still available at
       shared/page-email-preferences.html. Reverting is a one-line
       edit on the Email Opt-out <li> plus deleting the popup block.
     • The two carry the SAME verbatim copy. If the client revises
       the wording, or the HubSpot subscription-preferences URL
       arrives and the commented-out CTA is enabled, do it in BOTH
       or delete whichever one is not in use.
     • The dialog moves itself to document.body on init, so its CSS
       is scoped to #umoya-email-optout rather than #umoya-footer.
       Do not "tidy" it back under the footer's root — a fixed
       element inside a transformed ancestor stops being fixed to
       the viewport, and Elementor motion effects can add a
       transform at any time.
     • The trigger's href is a real mailto, not "#", so the item
       still does something useful before the script runs.
=================================================================
-->
