<?php
/**
 * SJ Journey Chapters -- render template.
 *
 * GENERATED by tools/uew from signature-journey/section-03-journey-chapters.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — THE SIGNATURE JOURNEY — SECTION 03: THE THREE CHAPTERS
=================================================================
  The journey told as three movements, each with a lead image +
  copy, then three "Signature Moment" cards.

  Chapter One  — History & Culture — Johannesburg & Soweto
  Chapter Two  — Safari            — The Sabi Sand
  Chapter Three— The Cape          — Cape Town

  Bands alternate white / cream for tonal rhythm; moment cards
  invert against their band. Built as ONE widget so the shared CSS
  is not triplicated across three Elementor HTML widgets.

  ANCHOR: id="sj-journey" is the nav target — do not change.

  IMAGES:
  • Chapter LEAD images still use live Umoya CDN placeholders — ★ SWAP
    (no chapter lead images were supplied in this feedback round).
  • The nine MOMENT cards now hold client-approved photos
    (.sj-ch-mom-pic), one per Signature Moment.

  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="sj-journey" aria-label="<?php echo $c['c_section_aria_label']; ?>">

  <!-- ═══════════ MOVEMENT I — HISTORY & CULTURE ═══════════ -->
  <div class="sj-ch-mv">
    <div class="sj-ch-c">
      <div class="sj-ch-head">
        <div class="sj-ch-rv">
          <div class="sj-ch-num"><?php echo $c['c_sj_ch_mv_div_div_div_div_text']; ?></div>
          <h2 class="sj-ch-ttl"><?php echo $c['c_sj_ch_mv_div_div_div_h2_text']; ?></h2>
          <div class="sj-ch-where"><?php echo $c['c_sj_ch_mv_div_div_div_div_text_2']; ?></div>
          <p class="sj-ch-lead"><?php echo $c['c_sj_ch_mv_div_div_div_p_text']; ?></p>
        </div>
        <!-- Chapter One lead image (Johannesburg / Soweto) -->
        <div class="sj-ch-img sj-ch-rv d1">
          <img src="<?php echo $c['c_sj_ch_mv_div_div_div_img_src']; ?>" alt="<?php echo $c['c_sj_ch_mv_div_div_div_img_alt']; ?>" loading="<?php echo $c['c_sj_ch_mv_div_div_div_img_loading']; ?>" />
        </div>
      </div>

      <div class="sj-ch-moments">
        <!-- Chapter One · The Welcome — umoya_compressed_ZAV_6216.png -->
        <?php $__i = 0; foreach ( $r['rep_article_sj_ch_mom'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><article class="<?php echo array( 'sj-ch-mom sj-ch-rv', 'sj-ch-mom sj-ch-rv d1', 'sj-ch-mom sj-ch-rv d2' )[ ( ( (int) $it['_uew_n'] ) - 1 ) % 3 ]; ?> <?php echo $it['_uew_item_class']; ?>">
          <div class="sj-ch-mom-img">
            <img class="sj-ch-mom-pic" src="<?php echo $it['src']; ?>" alt="<?php echo $it['alt']; ?>" loading="<?php echo $it['loading']; ?>" />
          </div>
          <div class="sj-ch-mom-body">
            <div class="sj-ch-mom-role"><?php echo $it['mom_role']; ?></div>
            <h3 class="sj-ch-mom-name"><?php echo $it['mom_name']; ?></h3>
            <p class="sj-ch-mom-desc"><?php echo $it['mom_desc']; ?></p>
          </div>
        </article><?php endforeach; echo "\n      "; ?></div>
    </div>
  </div>

  <!-- ═══════════ MOVEMENT II — SAFARI ═══════════ -->
  <div class="sj-ch-mv sj-ch-alt">
    <div class="sj-ch-c">
      <div class="sj-ch-head">
        <div class="sj-ch-rv">
          <div class="sj-ch-num"><?php echo $c['c_sj_ch_alt_sj_ch_c_sj_ch_head_sj_ch_rv_sj_ch_num_text']; ?></div>
          <h2 class="sj-ch-ttl"><?php echo $c['c_sj_ch_alt_sj_ch_c_sj_ch_head_sj_ch_rv_sj_ch_ttl_text']; ?></h2>
          <div class="sj-ch-where"><?php echo $c['c_sj_ch_alt_sj_ch_c_sj_ch_head_sj_ch_rv_sj_ch_where_text']; ?></div>
          <p class="sj-ch-lead"><?php echo $c['c_sj_ch_alt_sj_ch_c_sj_ch_head_sj_ch_rv_sj_ch_lead_text']; ?></p>
        </div>
        <!-- Chapter Two lead image (the Sabi Sand) -->
        <div class="sj-ch-img sj-ch-rv d1">
          <img src="<?php echo $c['c_sj_ch_alt_sj_ch_c_sj_ch_head_sj_ch_img_img_src']; ?>" alt="<?php echo $c['c_sj_ch_alt_sj_ch_c_sj_ch_head_sj_ch_img_img_alt']; ?>" loading="<?php echo $c['c_sj_ch_alt_sj_ch_c_sj_ch_head_sj_ch_img_img_loading']; ?>" />
        </div>
      </div>

      <div class="sj-ch-moments">
        <!-- Chapter Two · The Wild — umoya_compressed_SAT001232.jpeg -->
        <?php $__i = 0; foreach ( $r['rep_article_sj_ch_mom_2'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><article class="<?php echo array( 'sj-ch-mom sj-ch-rv', 'sj-ch-mom sj-ch-rv d1', 'sj-ch-mom sj-ch-rv d2' )[ ( ( (int) $it['_uew_n'] ) - 1 ) % 3 ]; ?> <?php echo $it['_uew_item_class']; ?>">
          <div class="sj-ch-mom-img">
            <img class="sj-ch-mom-pic" src="<?php echo $it['src']; ?>" alt="<?php echo $it['alt']; ?>" loading="<?php echo $it['loading']; ?>" />
          </div>
          <div class="sj-ch-mom-body">
            <div class="sj-ch-mom-role"><?php echo $it['mom_role']; ?></div>
            <h3 class="sj-ch-mom-name"><?php echo $it['mom_name']; ?></h3>
            <p class="sj-ch-mom-desc"><?php echo $it['mom_desc']; ?></p>
          </div>
        </article><?php endforeach; echo "\n      "; ?></div>
    </div>
  </div>

  <!-- ═══════════ MOVEMENT III — THE CAPE ═══════════ -->
  <div class="sj-ch-mv">
    <div class="sj-ch-c">
      <div class="sj-ch-head">
        <div class="sj-ch-rv">
          <div class="sj-ch-num"><?php echo $c['c_sj_ch_mv_div_div_div_div_text_3']; ?></div>
          <h2 class="sj-ch-ttl"><?php echo $c['c_sj_ch_mv_div_div_div_h2_text_2']; ?></h2>
          <div class="sj-ch-where"><?php echo $c['c_sj_ch_mv_div_div_div_div_text_4']; ?></div>
          <p class="sj-ch-lead"><?php echo $c['c_sj_ch_mv_div_div_div_p_text_2']; ?></p>
        </div>
        <!-- Chapter Three lead image (Cape Town) -->
        <div class="sj-ch-img sj-ch-rv d1">
          <img src="<?php echo $c['c_sj_ch_mv_div_div_div_img_src_2']; ?>" alt="<?php echo $c['c_sj_ch_mv_div_div_div_img_alt_2']; ?>" loading="<?php echo $c['c_sj_ch_mv_div_div_div_img_loading_2']; ?>" />
        </div>
      </div>

      <div class="sj-ch-moments">
        <!-- Chapter Three · Robben Island — umoya_compressed_ZAV_1363.png -->
        <?php $__i = 0; foreach ( $r['rep_article_sj_ch_mom_3'] as $it ) : if ( $__i ++ ) { echo $it['_uew_sep']; } ?><article class="<?php echo array( 'sj-ch-mom sj-ch-rv', 'sj-ch-mom sj-ch-rv d1', 'sj-ch-mom sj-ch-rv d2' )[ ( ( (int) $it['_uew_n'] ) - 1 ) % 3 ]; ?> <?php echo $it['_uew_item_class']; ?>">
          <div class="sj-ch-mom-img">
            <img class="sj-ch-mom-pic"<?php echo $it['extra_attributes']; ?> src="<?php echo $it['src']; ?>" alt="<?php echo $it['alt']; ?>" loading="<?php echo $it['loading']; ?>" />
          </div>
          <div class="sj-ch-mom-body">
            <div class="sj-ch-mom-role"><?php echo $it['mom_role']; ?></div>
            <h3 class="sj-ch-mom-name"><?php echo $it['mom_name']; ?></h3>
            <p class="sj-ch-mom-desc"><?php echo $it['mom_desc']; ?></p>
          </div>
        </article><?php endforeach; echo "\n      "; ?></div>
    </div>
  </div>

</section>
