<?php
/**
 * SJ Extensions -- render template.
 *
 * GENERATED by tools/uew from signature-journey/section-04-extensions.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — THE SIGNATURE JOURNEY — SECTION 04: OPTIONAL EXTENSIONS
=================================================================
  The page's dark-brown accent section (tonal contrast against the
  cream/white bands around it). Two extension tiles:
    • Extension One — Victoria Falls
    • Extension Two — Chobe (builds on One)

  ANCHOR: id="sj-extensions" is the nav target — do not change.
  IMAGES: both tiles now use client-approved images.
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="sj-extensions" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="sj-ext-c">

    <div class="sj-ext-head sj-ext-rv">
      <span class="sj-ext-eye"><?php echo $c['eyebrow_text']; ?></span>
      <h2 class="sj-ext-ttl"><?php echo $c['title_text']; ?></h2>
      <p class="sj-ext-sub"><?php echo $c['subtitle_text']; ?></p>
    </div>

    <div class="sj-ext-grid">

      <!-- Extension One — Victoria Falls -->
      <article class="sj-ext-tile sj-ext-rv d1">
        <!-- Extension One · Victoria Falls — umoya_compressed_img233195226.jpeg -->
        <div class="sj-ext-img">
          <img src="<?php echo $c['image_src']; ?>" alt="<?php echo $c['image_alt']; ?>" loading="<?php echo $c['image_loading']; ?>" />
        </div>
        <div class="sj-ext-body">
          <div class="sj-ext-num"><?php echo $c['text_text']; ?></div>
          <h3 class="sj-ext-name"><?php echo $c['heading_text']; ?></h3>
          <div class="sj-ext-where"><?php echo $c['text_text_2']; ?></div>
          <p class="sj-ext-desc"><?php echo $c['text_text_3']; ?></p>
        </div>
      </article>

      <!-- Extension Two — Chobe -->
      <article class="sj-ext-tile sj-ext-rv d2">
        <!-- Extension Two · Chobe — umoya_compressed_Chobe-Princess_Exterior_at-Sunset-709-1600x1066.jpg -->
        <div class="sj-ext-img">
          <img src="<?php echo $c['image_src_2']; ?>" alt="<?php echo $c['image_alt_2']; ?>" loading="<?php echo $c['image_loading_2']; ?>" />
        </div>
        <div class="sj-ext-body">
          <div class="sj-ext-num"><?php echo $c['text_text_4']; ?></div>
          <h3 class="sj-ext-name"><?php echo $c['heading_text_2']; ?></h3>
          <div class="sj-ext-where"><?php echo $c['text_text_5']; ?></div>
          <p class="sj-ext-desc"><?php echo $c['text_text_6']; ?></p>
        </div>
      </article>

    </div>
  </div>
</section>
