<?php
/**
 * SJ Extensions -- render template.
 *
 * GENERATED by tools/uew from signature-journey/section-04-extensions.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — THE SIGNATURE JOURNEY — SECTION 04: OPTIONAL EXTENSIONS
=================================================================
  The page's dark-brown accent section (tonal contrast against the
  cream/white bands around it). Two extension tiles:
    • Extension One — Victoria Falls
    • Extension Two — Chobe (builds on One)

  ANCHOR: id="sj-extensions" is the nav target — do not change.
  IMAGES: both tiles now use client-approved images.
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="sj-extensions" aria-label="<?php echo $c['section_aria_label']; ?>">
  <div class="sj-ext-c">

    <div class="sj-ext-head sj-ext-rv">
      <span class="sj-ext-eye"><?php echo $c['eyebrow_text']; ?></span>
      <h2 class="sj-ext-ttl"><?php echo $c['title_text']; ?></h2>
      <p class="sj-ext-sub"><?php echo $c['subtitle_text']; ?></p>
    </div>

    <div class="sj-ext-grid">

      <!-- Extension One — Victoria Falls -->
      <?php $__i = 0; foreach ( $r['rep_article_sj_ext_tile'] as $it ) : if ( $__i ++ ) { echo '

      <!-- Extension Two — Chobe -->
      '; } ?><article class="<?php echo 'sj-ext-tile sj-ext-rv d' . $it['_uew_n']; ?> <?php echo $it['_uew_item_class']; ?>"><?php echo $it['notes']; ?><div class="sj-ext-img">
          <img src="<?php echo $it['src']; ?>" alt="<?php echo $it['alt']; ?>" loading="<?php echo $it['loading']; ?>" />
        </div>
        <div class="sj-ext-body">
          <div class="sj-ext-num"><?php echo $it['num']; ?></div>
          <h3 class="sj-ext-name"><?php echo $it['name']; ?></h3>
          <div class="sj-ext-where"><?php echo $it['where']; ?></div>
          <p class="sj-ext-desc"><?php echo $it['desc']; ?></p>
        </div>
      </article><?php endforeach; echo "\n\n    "; ?></div>
  </div>
</section>
