<?php
/**
 * SJ Hero -- render template.
 *
 * GENERATED by tools/uew from signature-journey/section-01-hero.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — THE SIGNATURE JOURNEY — SECTION 01: HERO
  Layout: CENTRE-ALIGNED — eyebrow, title, sub, buttons (per mockup)
=================================================================
  ELEMENTOR: First content HTML widget after the nav.
  id="sj-hero" is the nav's active-section target.

  IMAGE ONLY — no video. ★ SWAP: hero background image.
=================================================================
-->
<section id="sj-hero" aria-label="<?php echo $c['section_aria_label']; ?>">

  <div class="sj-h1-bg">
    <!-- Hero image -->
    <img
      src="<?php echo $c['image_src']; ?>"
      alt="<?php echo $c['image_alt']; ?>"
      style="<?php echo $s['image_inline_style']; ?>"
    />
  </div>

  <div class="sj-h1-content">
    <div class="sj-h1-brand">
      <img
        src="<?php echo $c['image_src_2']; ?>"
        alt="<?php echo $c['image_alt_2']; ?>"
      />
    </div>
    <span class="sj-h1-eye"><?php echo $c['eyebrow_text']; ?></span>
    <h1 class="sj-h1-title"><?php echo $c['title_text']; ?></h1>
    <p class="sj-h1-sub"><?php echo $c['subtitle_text']; ?></p>
    <div class="sj-h1-btns">
      <!-- ★ SWAP: link the primary button to the brochure PDF/download when ready -->
      <a href="<?php echo $c['button_href']; ?>" class="sj-h1-btn sj-h1-btn-primary">
        <?php echo $c['button_text']; echo "\n        "; ?><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" aria-hidden="true">
          <line x1="12" y1="4" x2="12" y2="16"/>
          <polyline points="6 11 12 17 18 11"/>
        </svg>
      </a>
    </div>
  </div>

  <!-- The "Scroll" indicator was removed at client request: at 9.6px / 42%
       opacity, sitting just under the CTA on the shortened hero, it read as
       stray small text behind the button. Its CSS is kept above (unused) in
       case the cue is ever wanted back — do NOT re-add this markup. -->

</section>
