<?php
/**
 * SJ Navigation -- render template.
 *
 * GENERATED by tools/uew from signature-journey/section-00-nav.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — THE SIGNATURE JOURNEY — SECTION 00: TOP NAVIGATION
=================================================================
  Matches the homepage nav pattern: a fixed bar pinned to the top
  of the page at all times (no hide/reveal on hero scroll).

  BEHAVIOUR:
  • position: fixed; top: 0 — always visible from first paint.
  • Active section is tracked via IntersectionObserver and gets a
    terracotta underline.
  • Hamburger dropdown lives INSIDE the bar so it follows the
    fixed position.

  IMPORTANT — ELEMENTOR:
  • Place this widget FIRST, immediately before the hero widget.
  • Do NOT wrap in an Elementor section with overflow: hidden.

  BRAND: font-family: inherit everywhere. Palette tokens only.
=================================================================
-->
<!-- ── NAV BAR (fixed) ──────────────────────────────────────────── -->
<nav id="sjNavBar" aria-label="<?php echo $c['section_aria_label']; ?>">

  <div class="sj-nav-inner">

    <!-- Logo -->
    <a class="sj-nav-logo" href="<?php echo $c['logo_href']; ?>" aria-label="<?php echo $c['logo_aria_label']; ?>">
      <img
        src="<?php echo $c['image_src']; ?>"
        alt="<?php echo $c['image_alt']; ?>"
        onerror="this.style.display='none';document.getElementById('sjNLT').style.display='inline';"
      />
      <span class="sj-nav-logo-text" id="sjNLT" style="<?php echo $s['text_inline_style']; ?>"><?php echo $c['text_text']; ?></span>
    </a>

    <!-- Desktop section links -->
    <ul class="sj-nav-links" role="list">
      <?php $__i = 0; foreach ( $r['rep_li_sj_nav_item'] as $it ) : if ( $__i ++ ) { echo '
      '; } ?><li class="sj-nav-item <?php echo $it['_uew_item_class']; ?>" data-s="<?php echo $it['data_s']; ?>"><a class="sj-nav-link" href="<?php echo $it['href']; ?>"><?php echo $it['link']; ?></a></li><?php endforeach; echo "\n    "; ?></ul>

    <!-- Desktop CTA -->
    <a class="sj-nav-cta" href="<?php echo $c['button_href']; ?>"><?php echo $c['button_text']; ?></a>

    <!-- Hamburger -->
    <button
      class="sj-nav-burger"
      id="sjNavBurger"
      aria-label="<?php echo $c['button_aria_label']; ?>"
      aria-expanded="false"
      aria-controls="sjNavDropdown"<?php echo $c['button_disabled']; echo "\n    "; ?>>
      <span></span><span></span><span></span>
    </button>

    <!-- Mobile dropdown — inside the nav so it follows fixed position -->
    <div class="sj-nav-dropdown" id="sjNavDropdown" role="menu" aria-label="<?php echo $c['container_aria_label']; ?>">
      <ul class="sj-nav-dropdown-list" role="list">
        <?php $__i = 0; foreach ( $r['rep_li_sj_nav_dropdown_item'] as $it ) : if ( $__i ++ ) { echo '
        '; } ?><li class="sj-nav-dropdown-item <?php echo $it['_uew_item_class']; ?>" data-s="<?php echo $it['data_s']; ?>"><a class="sj-nav-dropdown-link" href="<?php echo $it['href']; ?>" role="<?php echo $it['role']; ?>"><?php echo $it['dropdown_link']; ?></a></li><?php endforeach; echo "\n      "; ?></ul>
      <div class="sj-nav-dropdown-cta-row">
        <a class="sj-nav-dropdown-cta" href="<?php echo $c['button_href_2']; ?>"><?php echo $c['button_text_2']; ?></a>
      </div>
    </div><!-- /.sj-nav-dropdown -->

  </div><!-- /.sj-nav-inner -->

</nav>
