<?php
/**
 * SJ Overview -- render template.
 *
 * GENERATED by tools/uew from signature-journey/section-02-intro.html. Do not edit by hand:
 * edit the section HTML and re-run `node tools/uew/build.mjs`.
 *
 * @var array $c Escaped scalar content values, keyed by control id.
 * @var array $r Repeater rows, each row an array of escaped values.
 * @var array $s Rebuilt inline style attributes, keyed by property-id list.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!--
=================================================================
  UMOYA — THE SIGNATURE JOURNEY — SECTION 02: OVERVIEW + INTRO
=================================================================
  Two stacked bands in one widget, in this order:
   1. Cream intro — centred heading + lead paragraph
   2. Brown overview stat bar
      (10 Days · 3 Chapters · 2 Extensions · 7 Signature Moments)

  The stat bar used to come FIRST, directly under the hero, where it
  stated the shape of a journey the reader had not been introduced to
  yet. It now closes the section, so the intro sets the scene and the
  numbers summarise it.

  The bar is safe as the section's last band: section 03 below is white
  and the intro above is cream, so the brown reads as a deliberate rule
  between them.

  ANCHOR: id="sj-overview" is the nav target — do not change.
  BRAND: font-family: inherit; palette tokens only.
=================================================================
-->
<section id="sj-overview" aria-label="<?php echo $c['c_section_aria_label']; ?>">

  <!-- Intro -->
  <div class="sj-ov-intro">
    <div class="sj-ov-narrow sj-ov-rv">
      <span class="sj-ov-eye"><?php echo $c['c_sj_ov_eye_text']; ?></span>
      <h2 class="sj-ov-ttl"><?php echo $c['c_sj_ov_ttl_text']; ?></h2>
      <p class="sj-ov-lead"><?php echo $c['c_sj_ov_lead_text']; ?></p>
    </div>
  </div>

  <!-- Overview stat bar -->
  <div class="sj-ov-bar">
    <div class="sj-ov-bar-in" role="list">
      <?php $__i = 0; foreach ( $r['rep_div_sj_ov_stat'] as $it ) : if ( $__i ++ ) { echo '
      '; } ?><div class="sj-ov-stat <?php echo $it['_uew_item_class']; ?>" role="<?php echo $it['role']; ?>">
        <div class="sj-ov-stat-n"><?php echo $it['stat_n']; ?></div>
        <div class="sj-ov-stat-l" data-short="<?php echo $it['data_short']; ?>"><?php echo $it['stat_l']; ?></div>
      </div><?php endforeach; echo "\n    "; ?></div>
  </div>

</section>
