<?php
/**
 * Base class for every generated Umoya section widget.
 *
 * A section widget is a normal Elementor widget: it declares controls in
 * register_controls(), reads them with get_settings_for_display(), and renders
 * server-side. It has no content_template(), so Elementor renders it through
 * PHP in the editor as well -- the same code path as the front end, which is
 * why what you see in the canvas is what ships.
 *
 * Everything specific to a section lives in includes/sections/<key>.json,
 * generated by tools/uew from the section's HTML.
 *
 * @package Umoya_EW
 */

namespace Umoya_EW;

use Elementor\Controls_Manager;
use Elementor\Repeater;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

abstract class Section_Widget extends \Elementor\Widget_Base {

	/** @return string Key into the section registry. */
	abstract protected function section_key();

	protected function config() {
		return Section_Registry::get( $this->section_key() );
	}

	/* ------------------------------------------------------------- identity */

	public function get_name() {
		$config = $this->config();

		return ! empty( $config['name'] ) ? $config['name'] : 'umoya-section';
	}

	public function get_title() {
		$config = $this->config();

		return ! empty( $config['title'] ) ? $config['title'] : 'Umoya Section';
	}

	public function get_icon() {
		$config = $this->config();

		return ! empty( $config['icon'] ) ? $config['icon'] : 'eicon-globe';
	}

	public function get_categories() {
		$config = $this->config();

		return array( ! empty( $config['category'] ) ? $config['category'] : 'umoya-fc' );
	}

	public function get_keywords() {
		$config = $this->config();

		return ! empty( $config['keywords'] ) ? (array) $config['keywords'] : array( 'umoya' );
	}

	public function get_style_depends() {
		$config = $this->config();

		return empty( $config['style']['handle'] ) ? array() : array( $config['style']['handle'] );
	}

	public function get_script_depends() {
		$config = $this->config();

		return empty( $config['script']['handle'] ) ? array() : array( $config['script']['handle'] );
	}

	/**
	 * Track Elementor's optimized-markup experiment, exactly as its own widgets
	 * do (see `Widget_Html::has_widget_inner_wrapper`).
	 *
	 * These sections are deployed today by pasting them into Elementor's HTML
	 * widget, so matching that widget's DOM depth means the surrounding boxes
	 * are identical and nothing in the sections' CSS lands one level out. It
	 * also means the answer follows the site's setting rather than a hardcoded
	 * guess about it.
	 */
	public function has_widget_inner_wrapper(): bool {
		if ( ! class_exists( '\Elementor\Plugin' ) || ! isset( \Elementor\Plugin::$instance->experiments ) ) {
			return true;
		}

		return ! \Elementor\Plugin::$instance->experiments->is_feature_active( 'e_optimized_markup' );
	}

	/* ------------------------------------------------------------- controls */

	/** Portals of the section being registered, for controls that write CSS. */
	private $uew_portals = array();

	protected function register_controls() {
		$config = $this->config();
		if ( empty( $config ) ) {
			return;
		}

		$this->uew_portals = isset( $config['portals'] ) ? (array) $config['portals'] : array();

		$this->register_content_panels( $config );
		$this->register_style_panels( $config );
		$this->register_advanced_panels( $config );
		$this->register_advanced_controls( $config );
	}

	/**
	 * Content tab: one panel per visible block of the section, in page order.
	 *
	 * Each entry is one thing a person sees. An entry with several settings --
	 * a field's label and placeholder, a button's link and wording -- gets a
	 * heading; a single setting is already named after its element. Lists sit
	 * in the block they belong to, where they appear on the page.
	 */
	private function register_content_panels( array $config ) {
		$lists = array();
		foreach ( (array) $config['repeaters'] as $definition ) {
			$lists[ $definition['id'] ] = $definition;
		}

		foreach ( (array) $config['content_panels'] as $panel ) {
			$this->start_controls_section(
				$panel['id'],
				array(
					'label' => $panel['label'],
					'tab'   => Controls_Manager::TAB_CONTENT,
				)
			);

			$items = isset( $panel['items'] ) ? (array) $panel['items'] : array();
			$alone = 1 === count( $items );

			foreach ( $items as $index => $item ) {
				if ( 'list' === $item['kind'] ) {
					if ( isset( $lists[ $item['id'] ] ) ) {
						$this->add_list_control( $lists[ $item['id'] ], ! $alone, $index > 0, isset( $item['label'] ) ? (string) $item['label'] : '' );
					}
					continue;
				}

				if ( count( $item['controls'] ) > 1 ) {
					$this->add_control(
						$panel['id'] . '_h' . $index,
						array(
							'label'     => $item['label'],
							'type'      => Controls_Manager::HEADING,
							'separator' => $index > 0 ? 'before' : 'none',
						)
					);
				}

				foreach ( $item['controls'] as $field ) {
					$this->add_field_control( $this, $field );
				}
			}

			$this->end_controls_section();
		}
	}

	/**
	 * One list (an Elementor repeater) inside the current panel.
	 *
	 * @param array $definition Repeater definition from the schema.
	 * @param bool  $heading    Whether other entries share the panel, so the list needs a heading.
	 * @param bool  $separate   Whether a rule should separate it from what comes before.
	 * @param string $label     Its name within the panel ("Links"), which can be
	 *                          shorter than its name across the widget.
	 */
	private function add_list_control( array $definition, $heading, $separate, $label = '' ) {
		$label    = '' !== $label ? $label : $definition['label'];
		$repeater = new Repeater();

		foreach ( $definition['controls'] as $field ) {
			$this->add_field_control( $repeater, $field );
		}

		// Per-row style overrides. `{{CURRENT_ITEM}}` resolves to the
		// elementor-repeater-item-<id> class the template prints on each row.
		// A list inside a dialog that moves to <body> needs the portal branch
		// too, or its rows stop being styleable the moment the dialog opens.
		$item = '{{WRAPPER}} {{CURRENT_ITEM}}';
		if ( ! empty( $definition['portal'] ) ) {
			$item .= ', ' . $definition['portal'] . Control_Factory::PORTAL_HOOK . ' {{CURRENT_ITEM}}';
		}
		$repeater->add_control(
			'uew_row_style_heading',
			array( 'label' => 'This row only', 'type' => Controls_Manager::HEADING, 'separator' => 'before' )
		);
		$repeater->add_control(
			'uew_row_color',
			array(
				'label'     => 'Text Color',
				'type'      => Controls_Manager::COLOR,
				'selectors' => array( $item => 'color: {{VALUE}};' ),
			)
		);
		$repeater->add_control(
			'uew_row_background',
			array(
				'label'     => 'Background Color',
				'type'      => Controls_Manager::COLOR,
				'selectors' => array( $item => 'background-color: {{VALUE}};' ),
			)
		);
		$repeater->add_control(
			'uew_row_border_color',
			array(
				'label'     => 'Border Color',
				'type'      => Controls_Manager::COLOR,
				'selectors' => array( $item => 'border-color: {{VALUE}};' ),
			)
		);

		if ( $heading ) {
			$this->add_control(
				$definition['id'] . '_heading',
				array(
					'label'     => $label,
					'type'      => Controls_Manager::HEADING,
					'separator' => $separate ? 'before' : 'none',
				)
			);
		}

		// Option lists submit their values; the compiler explains that here,
		// and the registry adds a sharper warning where a HubSpot dropdown
		// property must match the list exactly.
		if ( ! empty( $definition['notice'] ) ) {
			$this->add_control(
				$definition['id'] . '_notice',
				array(
					'type'            => Controls_Manager::RAW_HTML,
					'raw'             => wp_kses_post( $definition['notice'] ),
					'content_classes' => 'elementor-descriptor',
				)
			);
		}

		$this->add_control(
			$definition['id'],
			array(
				'label'       => $label,
				'show_label'  => ! $heading,
				'type'        => Controls_Manager::REPEATER,
				'fields'      => $repeater->get_controls(),
				'default'     => $this->repeater_defaults( $definition ),
				'title_field' => ! empty( $definition['item_label'] ) ? $definition['item_label'] : '',
			)
		);
	}

	private function repeater_defaults( array $definition ) {
		$defaults = array();

		foreach ( $definition['rows'] as $index => $row ) {
			// Elementor generates `_id` for rows an editor adds, but not for rows
			// declared as a control default. Without one `{{CURRENT_ITEM}}` has
			// nothing to resolve to and per-row styling silently does nothing.
			$prepared = array( '_id' => substr( md5( $definition['id'] . '|' . $index ), 0, 7 ) );
			foreach ( $definition['controls'] as $field ) {
				$id    = $field['id'];
				$value = isset( $row[ $id ] ) ? $row[ $id ] : ( isset( $field['default'] ) ? $field['default'] : '' );

				if ( in_array( $field['control'], array( 'url', 'media' ), true ) ) {
					$prepared[ $id ] = array( 'url' => $value );
					continue;
				}

				$prepared[ $id ] = $value;
			}
			$defaults[] = $prepared;
		}

		return $defaults;
	}

	/**
	 * Style tab: "Section" first -- the section's colours, its own box, and
	 * anything styled section-wide -- then one panel per block. Each element is
	 * one row whose settings open in a pop-out (see Control_Factory).
	 */
	private function register_style_panels( array $config ) {
		$root    = ! empty( $config['root_selector'] ) ? $config['root_selector'] : '';
		$portals = isset( $config['portals'] ) ? (array) $config['portals'] : array();

		$parts = array();
		foreach ( (array) $config['style_parts'] as $part ) {
			$parts[ $part['id'] ] = $part;
		}

		$add_field = function ( array $field ) {
			$this->add_field_control( $this, $field );
		};

		foreach ( (array) $config['style_panels'] as $panel ) {
			$this->start_controls_section(
				$panel['id'],
				array(
					'label' => $panel['label'],
					'tab'   => Controls_Manager::TAB_STYLE,
				)
			);

			if ( ! empty( $panel['tokens'] ) ) {
				$this->add_token_controls( $config );
			}

			foreach ( (array) $panel['rows'] as $index => $row ) {
				if ( ! empty( $row['heading'] ) ) {
					$this->add_control(
						$panel['id'] . '_h' . $index,
						array(
							'label'     => $row['heading'],
							'type'      => Controls_Manager::HEADING,
							'separator' => 'before',
						)
					);
				}
				if ( empty( $parts[ $row['part'] ] ) ) {
					continue;
				}
				Control_Factory::add_part_popover(
					$this,
					$parts[ $row['part'] ],
					$root,
					$portals,
					$row['label'],
					isset( $row['inline'] ) ? (array) $row['inline'] : array(),
					isset( $row['inline_props'] ) ? (array) $row['inline_props'] : array(),
					$add_field
				);
			}

			$this->end_controls_section();
		}
	}

	/**
	 * The section's own CSS variables, at the top of its Section style panel:
	 * its colours first, since a colour changed here changes every element
	 * that uses it, in one move.
	 */
	private function add_token_controls( array $config ) {
		if ( empty( $config['tokens'] ) ) {
			return;
		}

		$root    = ! empty( $config['root_selector'] ) ? $config['root_selector'] : '';
		$portals = isset( $config['portals'] ) ? (array) $config['portals'] : array();

		$colors = array_filter( $config['tokens'], function ( $token ) {
			return 'color' === $token['kind'];
		} );
		$others = array_filter( $config['tokens'], function ( $token ) {
			return 'color' !== $token['kind'];
		} );

		foreach ( array( 'Colours' => $colors, 'Other Values' => $others ) as $heading => $tokens ) {
			if ( ! $tokens ) {
				continue;
			}

			$this->add_control(
				'uew_tokens_' . sanitize_key( $heading ),
				array(
					'label'     => $heading,
					'type'      => Controls_Manager::HEADING,
					'separator' => 'Colours' === $heading ? 'none' : 'before',
				)
			);
			if ( 'Colours' === $heading ) {
				$this->add_control(
					'uew_tokens_notice',
					array(
						'type'            => Controls_Manager::RAW_HTML,
						'raw'             => 'The section&rsquo;s own palette. Changing a colour here re-colours every element that uses it.',
						'content_classes' => 'elementor-descriptor',
					)
				);
			}

			foreach ( $tokens as $token ) {
				// A token is written where the stylesheet declares it, not on the
				// root: a child that redeclares it would otherwise shadow the value.
				$declared = ! empty( $token['selectors'] ) ? (array) $token['selectors'] : array( $root );
				$branches = array();
				foreach ( $declared as $selector ) {
					$branches[] = Control_Factory::scoped( $selector, $portals );
				}

				$this->add_control(
					! empty( $token['id'] ) ? $token['id'] : 'uew_token_' . sanitize_key( str_replace( '-', '_', $token['name'] ) ),
					array(
						'label'       => $token['label'],
						'type'        => 'color' === $token['kind'] ? Controls_Manager::COLOR : Controls_Manager::TEXT,
						'placeholder' => $token['value'],
						'selectors'   => array(
							implode( ', ', $branches ) => '--' . $token['name'] . ': {{VALUE}};',
						),
					)
				);
			}
		}
	}

	/**
	 * Advanced tab: accessibility, link and media behaviour, form rules and the
	 * HubSpot wiring -- for whoever maintains the site. Each element is a
	 * heading naming its block and itself ("Sign-up › Email address").
	 */
	private function register_advanced_panels( array $config ) {
		foreach ( (array) ( isset( $config['advanced_panels'] ) ? $config['advanced_panels'] : array() ) as $panel ) {
			$this->start_controls_section(
				$panel['id'],
				array(
					'label' => $panel['label'],
					'tab'   => Controls_Manager::TAB_ADVANCED,
				)
			);

			if ( ! empty( $panel['notice'] ) ) {
				$this->add_control(
					$panel['id'] . '_notice',
					array(
						'type'            => Controls_Manager::RAW_HTML,
						'raw'             => $panel['notice'],
						'content_classes' => 'elementor-descriptor',
					)
				);
			}

			foreach ( (array) $panel['groups'] as $index => $group ) {
				$this->add_control(
					$panel['id'] . '_h' . $index,
					array(
						'label'     => $group['label'],
						'type'      => Controls_Manager::HEADING,
						'separator' => ( $index > 0 || ! empty( $panel['notice'] ) ) ? 'before' : 'none',
					)
				);
				foreach ( $group['controls'] as $field ) {
					$this->add_field_control( $this, $field );
				}
			}

			$this->end_controls_section();
		}
	}

	private function register_advanced_controls( array $config ) {
		$root = ! empty( $config['root_selector'] ) ? $config['root_selector'] : '';

		$this->start_controls_section(
			'uew_advanced',
			array(
				'label' => 'Section Escape Hatches',
				'tab'   => Controls_Manager::TAB_ADVANCED,
			)
		);

		$this->add_control(
			'uew_extra_class',
			array(
				'label'       => 'Additional CSS Class',
				'type'        => Controls_Manager::TEXT,
				'description' => 'Added to the section root, for targeting from theme CSS.',
				'label_block' => true,
			)
		);

		$description = 'Use <code>{{WRAPPER}}</code> for this widget instance, e.g. <code>{{WRAPPER}} ' . esc_html( $root ) . ' { }</code>';
		foreach ( isset( $config['portals'] ) ? (array) $config['portals'] : array() as $portal ) {
			// The dialog leaves the wrapper when it moves to <body>, so a
			// {{WRAPPER}} rule cannot follow it there; its own hook can.
			$description .= '<br><code>' . esc_html( $portal['selector'] ) . '</code> moves to the end of the page when it opens: target it as <code>' .
				esc_html( $portal['selector'] ) . '[data-uew-for="{{ID}}"]</code>.';
		}

		$this->add_control(
			'uew_custom_css',
			array(
				'label'       => 'Custom CSS',
				'type'        => Controls_Manager::CODE,
				'language'    => 'css',
				'rows'        => 12,
				'description' => $description,
			)
		);

		$this->add_control(
			'uew_source_notice',
			array(
				'type'            => Controls_Manager::RAW_HTML,
				'raw'             => 'Generated from <code>' . esc_html( isset( $config['source'] ) ? $config['source'] : '' ) . '</code>. Structural changes belong in that file, followed by <code>node tools/uew/build.mjs</code>.',
				'content_classes' => 'elementor-descriptor',
				'separator'       => 'before',
			)
		);

		$this->end_controls_section();
	}

	/**
	 * Map one schema field onto the matching native Elementor control.
	 *
	 * @param \Elementor\Widget_Base|Repeater $host  Widget or repeater to add to.
	 * @param array                           $field Schema field.
	 */
	private function add_field_control( $host, array $field ) {
		$args = array(
			'label'       => $field['label'],
			'label_block' => true,
		);

		if ( ! empty( $field['description'] ) ) {
			$args['description'] = $field['description'];
		}

		switch ( $field['control'] ) {
			case 'media':
				$args['type']    = Controls_Manager::MEDIA;
				$args['default'] = is_array( $field['default'] ) ? $field['default'] : array( 'url' => $field['default'] );
				$args['dynamic'] = array( 'active' => true );

				// A photo the stylesheet paints is replaced with CSS, the way
				// Elementor's own background controls do it, not in the markup.
				// The compiler supplies the declaration with every other layer --
				// an overlay gradient -- kept, and only the photo templated.
				if ( ! empty( $field['css_selector'] ) ) {
					$args['selectors'] = array(
						Control_Factory::scoped( $field['css_selector'], $this->uew_portals ) =>
							! empty( $field['css_value'] ) ? $field['css_value'] : 'background-image: url("{{URL}}");',
					);
				}
				break;

			case 'url':
				$args['type']    = Controls_Manager::URL;
				$args['default'] = is_array( $field['default'] ) ? $field['default'] : array( 'url' => $field['default'] );
				$args['dynamic'] = array( 'active' => true );
				$args['options'] = false; // No target/nofollow toggles: the markup owns those attributes.
				break;

			case 'select':
				$args['type']    = Controls_Manager::SELECT;
				$args['default'] = isset( $field['default'] ) ? $field['default'] : '';
				$args['options'] = array();
				foreach ( (array) $field['options'] as $option ) {
					$args['options'][ $option ] = ucfirst( $option );
				}
				break;

			case 'color':
				$args['type']    = Controls_Manager::COLOR;
				$args['default'] = isset( $field['default'] ) ? $field['default'] : '';
				break;

			case 'switcher':
				$args['type']         = Controls_Manager::SWITCHER;
				$args['default']      = isset( $field['default'] ) ? $field['default'] : '';
				$args['label_on']     = 'Yes';
				$args['label_off']    = 'No';
				$args['return_value'] = 'yes';
				$args['label_block']  = false;
				break;

			case 'hidden':
				$args['type']    = Controls_Manager::HIDDEN;
				$args['default'] = isset( $field['default'] ) ? $field['default'] : '';
				break;

			case 'textarea':
				$args['type']    = Controls_Manager::TEXTAREA;
				$args['rows']    = 5;
				$args['default'] = isset( $field['default'] ) ? $field['default'] : '';
				$args['dynamic'] = array( 'active' => true );
				break;

			case 'text':
			default:
				$args['type']    = Controls_Manager::TEXT;
				$args['default'] = isset( $field['default'] ) ? $field['default'] : '';
				$args['dynamic'] = array( 'active' => true );
				break;
		}

		$host->add_control( $field['id'], $args );
	}

	/* --------------------------------------------------------------- render */

	protected function render() {
		$config = $this->config();
		if ( empty( $config['template'] ) ) {
			return;
		}

		$template = UMOYA_EW_PATH . ltrim( $config['template'], '/\\' );
		if ( ! file_exists( $template ) ) {
			return;
		}

		$settings = $this->get_settings_for_display();

		// Names matter: the generated templates read exactly these.
		$c = $this->prepare_scalars( $config, $settings );
		$r = $this->prepare_repeaters( $config, $settings );
		$s = $this->prepare_inline_styles( $config, $settings );

		// The hook a dialog carries when it moves itself to <body>, so the
		// controls' portal selector branch can still find it there. Field ids
		// never start with an underscore, so this cannot collide with one.
		$c['_uew_for'] = empty( $config['portals'] ) ? '' : ' data-uew-for="' . esc_attr( $this->get_id() ) . '"';

		$extra_class = $this->extra_class( $settings );
		if ( '' !== $extra_class ) {
			// Applied to the wrapper rather than spliced into the markup, so the
			// template stays exactly what the compiler verified.
			$this->add_render_attribute( '_wrapper', 'class', $extra_class );
		}

		include $template;

		$this->print_custom_css( $settings );
	}

	private function prepare_scalars( array $config, array $settings ) {
		$values = array();

		foreach ( (array) $config['fields'] as $field ) {
			// Controls that write CSS rather than markup have nothing to print.
			if ( ! empty( $field['css_only'] ) ) {
				continue;
			}

			$id  = $field['id'];
			$esc = isset( $field['esc'] ) ? $field['esc'] : 'post';

			$value = array_key_exists( $id, $settings ) ? $settings[ $id ] : ( isset( $field['default'] ) ? $field['default'] : '' );

			if ( ! empty( $field['flag_attr'] ) ) {
				$values[ $id ] = Value_Formatter::flag(
					$value,
					$field['flag_attr'],
					isset( $field['flag_prefix'] ) ? $field['flag_prefix'] : ' '
				);
				continue;
			}

			$values[ $id ] = Value_Formatter::scalar( $value, $esc, isset( $field['default'] ) ? $field['default'] : null );
		}

		return $values;
	}

	private function prepare_repeaters( array $config, array $settings ) {
		$values = array();

		foreach ( (array) $config['repeaters'] as $definition ) {
			$id   = $definition['id'];
			$rows = ! empty( $settings[ $id ] ) && is_array( $settings[ $id ] ) ? $settings[ $id ] : array();
			$out  = array();

			// Every value the compiler produced for each field, so `raw` markup
			// straight from the section file passes through untouched while an
			// editor's own markup is still filtered.
			$trusted = array();
			foreach ( $definition['controls'] as $field ) {
				$trusted[ $field['id'] ] = array();
				foreach ( $definition['rows'] as $compiled_row ) {
					if ( isset( $compiled_row[ $field['id'] ] ) ) {
						$trusted[ $field['id'] ][] = $compiled_row[ $field['id'] ];
					}
				}
				if ( isset( $field['default'] ) ) {
					$trusted[ $field['id'] ][] = $field['default'];
				}
			}

			// Position and total come from the loop, never from stored data, so
			// ids, "2 of 5" labels and the active first item stay right however
			// rows are added, removed or reordered.
			foreach ( array_values( $rows ) as $index => $row ) {
				$prepared = array(
					'_uew_n'          => (string) ( $index + 1 ),
					'_uew_count'      => (string) count( $rows ),
					'_uew_item_class' => isset( $row['_id'] ) ? 'elementor-repeater-item-' . sanitize_html_class( $row['_id'] ) : '',
				);

				foreach ( $definition['controls'] as $field ) {
					$field_id = $field['id'];
					$value    = isset( $row[ $field_id ] ) ? $row[ $field_id ] : '';

					$prepared[ $field_id ] = Value_Formatter::scalar(
						$value,
						isset( $field['esc'] ) ? $field['esc'] : 'post',
						$trusted[ $field_id ]
					);
				}

				$out[] = $prepared;
			}

			$values[ $id ] = $out;
		}

		return $values;
	}

	private function prepare_inline_styles( array $config, array $settings ) {
		$values = array();

		foreach ( (array) $config['inline_styles'] as $group ) {
			$values[ $group['id'] ] = Value_Formatter::inline_style( $group, $settings );
		}

		return $values;
	}

	private function extra_class( array $settings ) {
		if ( empty( $settings['uew_extra_class'] ) ) {
			return '';
		}

		$classes = array_filter( array_map( 'sanitize_html_class', preg_split( '/\s+/', (string) $settings['uew_extra_class'] ) ) );

		return implode( ' ', $classes );
	}

	private function print_custom_css( array $settings ) {
		if ( empty( $settings['uew_custom_css'] ) ) {
			return;
		}

		$css = str_replace(
			array( '{{WRAPPER}}', '{{ID}}' ),
			array( '.elementor-element-' . $this->get_id(), $this->get_id() ),
			(string) $settings['uew_custom_css']
		);
		$css = wp_strip_all_tags( $css );
		$css = str_replace( array( '</', '<' ), array( '<\/', '' ), $css );

		if ( '' === trim( $css ) ) {
			return;
		}

		echo '<style id="uew-custom-css-' . esc_attr( $this->get_id() ) . '">' . $css . '</style>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	}
}
